import {useEffect,useState} from 'react';
import {CheckCircle2,Clock3,FileSignature,RefreshCw,ShieldCheck,WalletCards} from 'lucide-react';
import {Card,SecondaryButton,Pill} from '../../components/Primitives';
import {supabase} from '../../lib/supabase';

type Deal={room_id:string;portfolio_name:string;buyer_name:string;buyer_company:string;agreed_price:number;current_stage:string;stage_rank:number;nda_signed_at?:string;masked_access_at?:string;price_agreed_at?:string;agreement_generated_at?:string;agreement_sent_at?:string;buyer_signed_at?:string;owner_signed_at?:string;agreement_executed_at?:string;payment_verified_at?:string;file_released_at?:string;buyer_downloaded_at?:string;closed_at?:string;commission_amount:number;commission_status:string;commission_paid_at?:string;commission_requirement:string};
const money=(n=0)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const when=(v?:string)=>v?new Date(v).toLocaleString():'Pending';
const milestones=(d:Deal)=>[
 ['NDA signed',d.nda_signed_at],['Masked portfolio accessed',d.masked_access_at],['Price agreed',d.price_agreed_at],
 ['Agreement generated',d.agreement_generated_at],['Agreement sent',d.agreement_sent_at],['Buyer signed',d.buyer_signed_at],
 ['Owner countersigned',d.owner_signed_at],['Agreement executed',d.agreement_executed_at],['Payment verified',d.payment_verified_at],
 ['Files released',d.file_released_at],['Buyer downloaded',d.buyer_downloaded_at],['Sale completed',d.closed_at]
] as const;
export default function EmployeePerformance(){
 const [deals,setDeals]=useState<Deal[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');const {data,error}=await supabase.rpc('dmh_employee_deal_transparency');if(error)setError(error.message);else setDeals((data||[]) as Deal[]);setLoading(false)};
 useEffect(()=>{load()},[]);
 const potential=deals.reduce((s,d)=>s+(Number(d.commission_amount)||0),0),earned=deals.filter(d=>['earned','approved','paid'].includes(d.commission_status)).reduce((s,d)=>s+(Number(d.commission_amount)||0),0);
 return <div className="mx-auto max-w-[1400px] p-5 md:p-8 lg:p-10"><header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold text-blue-600">Employee Deal Transparency · v3.1.3</p><h1 className="mt-1 text-3xl font-semibold">Your sales. Verified by the system.</h1><p className="mt-2 text-slate-500">Every milestone comes from signed documents, verified payment, file release, and recorded downloads.</p></div><SecondaryButton onClick={load}><RefreshCw className="mr-2" size={17}/>Refresh</SecondaryButton></header>
 {error&&<div className="mt-5 rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}
 <div className="mt-7 grid gap-4 sm:grid-cols-3"><Card className="p-5"><WalletCards className="text-blue-600"/><p className="mt-4 text-3xl font-semibold">{money(potential)}</p><p className="text-sm text-slate-500">Potential commission</p></Card><Card className="p-5"><CheckCircle2 className="text-emerald-600"/><p className="mt-4 text-3xl font-semibold">{money(earned)}</p><p className="text-sm text-slate-500">Earned or paid</p></Card><Card className="p-5"><ShieldCheck className="text-blue-600"/><p className="mt-4 text-3xl font-semibold">{deals.length}</p><p className="text-sm text-slate-500">Tracked transactions</p></Card></div>
 <div className="mt-7 space-y-5">{loading?<Card className="p-8 text-slate-500">Loading verified deal records…</Card>:deals.length===0?<Card className="p-8 text-center text-slate-500">No transactions are assigned to your employee account yet.</Card>:deals.map(d=><Card key={d.room_id} className="p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-600">{d.buyer_company}</p><h2 className="mt-1 text-xl font-semibold">{d.portfolio_name}</h2><p className="mt-1 text-sm text-slate-500">{d.buyer_name} · Agreed price {money(d.agreed_price)}</p></div><div className="text-right"><Pill tone={d.current_stage==='Completed'?'success':'blue'}>{d.current_stage}</Pill><p className="mt-2 text-sm font-semibold">Commission {money(d.commission_amount)}</p><p className="text-xs capitalize text-slate-500">{d.commission_status} · {d.commission_requirement}</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{milestones(d).map(([label,value])=><div key={label} className={`rounded-2xl p-4 ${value?'bg-emerald-50 text-emerald-800':'bg-slate-50 text-slate-500'}`}>{value?<CheckCircle2 size={18}/>:<Clock3 size={18}/>}<p className="mt-2 text-sm font-semibold">{label}</p><p className="mt-1 text-[11px]">{when(value)}</p></div>)}</div><div className="mt-5 flex items-center gap-2 rounded-2xl bg-slate-950 p-4 text-sm text-white"><FileSignature size={18}/><span>The owner cannot manually fabricate these milestones; they are read from recorded transaction events.</span></div></Card>)}</div></div>}
