import { useState } from 'react';
import { Check, Eye, LockKeyhole, ShieldCheck, Trophy, X } from 'lucide-react';
import { Card, Pill, PrimaryButton, SecondaryButton } from '../../components/Primitives';
import { usePortfolioStore } from '../../store/PortfolioStore';
import { supabase } from '../../lib/supabase';
const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v);
type Preview={portfolio_name:string;file_name:string;version:number;headers:string[];rows:string[][];truncated:boolean;preview_only:boolean};
export default function EmployeePortfolio(){
 const {active}=usePortfolioStore();const [preview,setPreview]=useState<Preview|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 if(!active)return <div className="p-10">No active portfolio.</div>;
 const payout=active.employeeCommissionType==='percentage'?active.askingPrice*(active.employeeCommissionValue/100):active.employeeCommissionValue;
 async function view(){setBusy(true);setError('');try{const {data,error}=await supabase.functions.invoke('view-masked-portfolio',{body:{portfolio_id:active!.id}});if(error)throw error;if(data?.error)throw new Error(data.error);setPreview(data as Preview)}catch(e){setError(e instanceof Error?e.message:'Preview unavailable')}finally{setBusy(false)}}
 return <div className="mx-auto max-w-6xl p-5 md:p-8 lg:p-10"><header className="mb-8"><Pill tone="success">Active</Pill><h2 className="mt-3 text-3xl font-semibold">{active.name}</h2><p className="mt-2 text-slate-500">Approved employee sales workspace</p></header>
 {active.employeeCommissionVisible&&<Card className="mb-6 overflow-hidden border-emerald-200 bg-emerald-50 p-7 md:p-9"><div className="flex flex-col gap-5 md:flex-row md:items-center"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-white text-emerald-700 shadow-sm"><Trophy size={28}/></div><div className="flex-1"><p className="text-sm font-bold uppercase tracking-wider text-emerald-700">Your payout if sold at asking price</p><p className="mt-2 text-4xl font-bold text-emerald-950">{money(payout)}</p><p className="mt-2 text-sm text-emerald-800">{active.employeeCommissionType==='percentage'?`${active.employeeCommissionValue}% commission on a ${money(active.askingPrice)} sale`:'Flat commission for closing this portfolio'}</p></div></div></Card>}
 <div className="grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><Card className="p-7 md:p-9"><p className="text-sm text-slate-500">Portfolio story</p><p className="mt-3 text-lg leading-8 text-slate-700">{active.description}</p><div className="mt-7 space-y-3">{active.sellingPoints.map(x=><div className="flex gap-3 rounded-2xl bg-slate-50 p-4" key={x}><Check className="text-emerald-600" size={19}/><span className="text-sm font-medium">{x}</span></div>)}</div></Card><div className="space-y-6"><Card className="p-6"><p className="text-sm text-slate-500">Asking price</p><p className="mt-2 text-3xl font-semibold">{money(active.askingPrice)}</p><p className="mt-4 text-sm text-slate-500">Use the approved asking price. All offers still require owner review.</p></Card>
 <Card className="p-6"><div className="flex items-center gap-3"><Eye className="text-blue-600"/><div><p className="font-semibold">Masked portfolio — view only</p><p className="mt-1 text-sm text-slate-500">{active.file?.name||'No approved masked file'}</p></div></div><PrimaryButton className="mt-5 w-full" disabled={!active.file||busy} onClick={view}><Eye className="mr-2" size={17}/>{busy?'Opening protected preview…':'View Protected Preview'}</PrimaryButton>{error&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-xs text-red-700">{error}</p>}<p className="mt-3 text-xs leading-5 text-slate-400">Download, export, signed links and raw storage access are disabled for employees. Buyers receive the masked file only after signing the NDA.</p></Card>
 <Card className="flex gap-3 p-5"><LockKeyhole className="shrink-0 text-blue-600"/><div><p className="text-sm font-semibold">File custody protected</p><p className="mt-1 text-xs leading-5 text-slate-500">Employees may inspect the controlled preview only. Unmasked files are never available in the employee workspace.</p></div></Card></div></div>
 {preview&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 p-4"><div className="flex max-h-[92vh] w-full max-w-7xl flex-col overflow-hidden rounded-3xl bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-slate-200 p-5"><div><div className="flex items-center gap-2 text-emerald-700"><ShieldCheck size={18}/><span className="text-xs font-bold tracking-[.18em]">PROTECTED VIEW-ONLY PREVIEW</span></div><h3 className="mt-2 text-xl font-semibold">{preview.portfolio_name}</h3><p className="mt-1 text-sm text-slate-500">{preview.file_name} · Version {preview.version}</p></div><button className="rounded-xl p-2 hover:bg-slate-100" onClick={()=>setPreview(null)} aria-label="Close preview"><X/></button></div><div className="overflow-auto p-5"><table className="min-w-full border-separate border-spacing-0 text-xs"><thead className="sticky top-0 bg-white"> <tr>{preview.headers.map((h,i)=><th key={i} className="whitespace-nowrap border-b border-slate-200 px-3 py-3 text-left font-semibold text-slate-600">{h||`Column ${i+1}`}</th>)}</tr></thead><tbody>{preview.rows.map((r,i)=><tr key={i} className="odd:bg-slate-50">{preview.headers.map((_,j)=><td key={j} className="max-w-xs truncate border-b border-slate-100 px-3 py-2 text-slate-700" title={r[j]||''}>{r[j]||''}</td>)}</tr>)}</tbody></table></div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 bg-slate-50 p-4"><p className="text-xs text-slate-500">Preview capped at 250 rows. No raw file URL is exposed to the employee browser.</p><SecondaryButton onClick={()=>setPreview(null)}>Close Preview</SecondaryButton></div></div></div>}
 </div>
}
