import { useMemo, useState } from 'react';
import { AlertTriangle, Check, Clock3, DollarSign, RotateCcw, ShieldCheck, X } from 'lucide-react';
import { Card, Pill, PrimaryButton, SecondaryButton, inputClass } from '../../components/Primitives';
import { useApprovalStore, type ApprovalRequest, type ApprovalStatus } from '../../store/ApprovalStore';
import { usePortfolioStore } from '../../store/PortfolioStore';
const money=(v?:number)=>v==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v);
const labels:Record<string,string>={below_floor_offer:'Below-floor offer',discount_exception:'Discount exception',marketing_override:'Marketing override',as_is_override:'AS-IS override',deal_reassignment:'Deal reassignment',commission_exception:'Commission exception',buyer_suppression_removal:'Suppression removal',funding_extension:'Funding extension',closing_document_exception:'Closing document exception',high_value_campaign:'High-value campaign',reservation_extension:'Reservation extension',other:'Other exception'};
const tone=(s:ApprovalStatus):'neutral'|'success'|'warning'|'danger'|'blue'=>s==='approved'||s==='executed'?'success':s==='pending'?'warning':s==='returned'?'blue':s==='rejected'||s==='expired'||s==='cancelled'?'danger':'neutral';
export default function ApprovalCenter(){const {requests,loading,error,refresh,decide}=useApprovalStore();const {portfolios}=usePortfolioStore();const [filter,setFilter]=useState<ApprovalStatus|'all'>('pending');const [selected,setSelected]=useState<ApprovalRequest|null>(null);const [notes,setNotes]=useState('');const [approvedValue,setApprovedValue]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const visible=useMemo(()=>requests.filter(r=>filter==='all'||r.status===filter),[requests,filter]);const counts=useMemo(()=>({pending:requests.filter(r=>r.status==='pending').length,approved:requests.filter(r=>r.status==='approved').length,returned:requests.filter(r=>r.status==='returned').length,closed:requests.filter(r=>['rejected','expired','cancelled','executed'].includes(r.status)).length}),[requests]);
 const open=(r:ApprovalRequest)=>{setSelected(r);setNotes(r.ownerNotes||'');setApprovedValue(r.approvedValue?.toString()||r.requestedValue?.toString()||'');setMessage('')};
 const act=async(status:'approved'|'rejected'|'returned'|'cancelled'|'executed')=>{if(!selected)return;setBusy(true);setMessage('');try{await decide(selected.id,status,notes,approvedValue===''?undefined:Number(approvedValue));setMessage(`Request ${status}.`);setSelected(null)}catch(e){setMessage(e instanceof Error?e.message:'Decision failed.')}finally{setBusy(false)}};
 return <div className="mx-auto max-w-[1600px] p-5 md:p-8 lg:p-10"><header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold text-blue-600">Owner Approval & Exception Control Engine · v2.3.1</p><h2 className="mt-1 text-3xl font-semibold">Approval Center</h2><p className="mt-2 max-w-3xl text-slate-500">Review restricted actions, understand the financial impact, make the decision, and preserve the audit trail.</p></div><SecondaryButton onClick={refresh} disabled={loading}><RotateCcw size={17} className="mr-2"/>Refresh queue</SecondaryButton></header>
 {error&&<Card className="mt-6 border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}. Run migration 037 if this engine is not installed.</Card>}{message&&<Card className="mt-6 border-blue-200 bg-blue-50 p-4 text-sm text-blue-800">{message}</Card>}
 <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Pending owner review" value={counts.pending} icon={Clock3}/><Metric label="Approved" value={counts.approved} icon={Check}/><Metric label="Returned for changes" value={counts.returned} icon={RotateCcw}/><Metric label="Closed decisions" value={counts.closed} icon={ShieldCheck}/></section>
 <div className="mt-7 flex flex-wrap gap-2">{(['pending','approved','returned','all'] as const).map(x=><button key={x} onClick={()=>setFilter(x)} className={`rounded-full px-4 py-2 text-sm font-semibold ${filter===x?'bg-slate-950 text-white':'bg-white text-slate-600 ring-1 ring-slate-200'}`}>{x==='all'?'All requests':x[0].toUpperCase()+x.slice(1)}</button>)}</div>
 <div className="mt-5 grid gap-4">{visible.length?visible.map(r=>{const portfolio=portfolios.find(p=>p.id===r.portfolioId);return <button key={r.id} onClick={()=>open(r)} className="rounded-[24px] border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:border-blue-300"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Pill tone={tone(r.status)}>{r.status.replace('_',' ')}</Pill><Pill tone="neutral">{labels[r.requestType]}</Pill>{r.expiresAt&&<Pill tone="neutral">Due {new Date(r.expiresAt).toLocaleDateString()}</Pill>}</div><h3 className="mt-3 text-lg font-semibold">{r.title}</h3><p className="mt-1 text-sm text-slate-500">{portfolio?.name||r.entityType} · {r.reason}</p></div><div className="grid shrink-0 grid-cols-3 gap-5 text-right"><Mini label="Original" value={money(r.originalValue)}/><Mini label="Requested" value={money(r.requestedValue)}/><Mini label="Impact" value={money(r.financialImpact)}/></div></div></button>}):<Card className="p-8 text-center text-slate-500">No approval requests in this view.</Card>}</div>
 {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><Card className="max-h-[92vh] w-full max-w-3xl overflow-y-auto p-6 md:p-8"><div className="flex items-start justify-between gap-4"><div><Pill tone={tone(selected.status)}>{selected.status}</Pill><h3 className="mt-3 text-2xl font-semibold">{selected.title}</h3><p className="mt-1 text-sm text-slate-500">{labels[selected.requestType]}</p></div><button onClick={()=>setSelected(null)} className="rounded-xl p-2 hover:bg-slate-100"><X/></button></div>
 <div className="mt-6 grid gap-4 sm:grid-cols-3"><Fact label="Original value" value={money(selected.originalValue)}/><Fact label="Requested value" value={money(selected.requestedValue)}/><Fact label="Financial impact" value={money(selected.financialImpact)}/></div>
 <div className="mt-6 grid gap-4"><Block label="Reason" value={selected.reason}/><Block label="Recommended decision" value={selected.recommendation||'No recommendation entered.'}/><Block label="Supporting notes" value={selected.supportingNotes||'No supporting notes.'}/></div>
 <label className="mt-6 block text-sm font-semibold text-slate-700">Final approved value<input type="number" className={inputClass+' mt-2'} value={approvedValue} onChange={e=>setApprovedValue(e.target.value)} placeholder="Optional"/></label><label className="mt-4 block text-sm font-semibold text-slate-700">Owner decision notes<textarea className={inputClass+' mt-2 min-h-28'} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Explain the decision and any conditions."/></label>
 {selected.status==='pending'||selected.status==='returned'?<div className="mt-6 grid gap-3 sm:grid-cols-3"><PrimaryButton disabled={busy} onClick={()=>act('approved')}><Check size={17} className="mr-2"/>Approve</PrimaryButton><SecondaryButton disabled={busy} onClick={()=>act('returned')}><RotateCcw size={17} className="mr-2"/>Return</SecondaryButton><SecondaryButton disabled={busy} onClick={()=>act('rejected')} className="border-red-200 text-red-700"><X size={17} className="mr-2"/>Reject</SecondaryButton></div>:selected.status==='approved'?<PrimaryButton disabled={busy} className="mt-6 w-full" onClick={()=>act('executed')}><ShieldCheck size={17} className="mr-2"/>Mark action executed</PrimaryButton>:null}</Card></div>}
 </div>}
function Metric({label,value,icon:Icon}:{label:string;value:number;icon:any}){return <Card className="p-5"><Icon size={18} className="text-blue-600"/><p className="mt-4 text-3xl font-semibold">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p></Card>}
function Mini({label,value}:{label:string;value:string}){return <div><p className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 font-semibold">{value}</p></div>}
function Fact({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>}
function Block({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-slate-200 p-4"><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-sm leading-6 text-slate-700">{value}</p></div>}
