import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, FileCheck2, Save, ShieldAlert, Sparkles } from 'lucide-react';
import { Card, Pill, PrimaryButton, SecondaryButton, inputClass } from '../../components/Primitives';
import { usePortfolioStore } from '../../store/PortfolioStore';
import { useAsIsReviewStore, type AsIsReview, type DetectedIssue, type ReviewStatus } from '../../store/AsIsReviewStore';
const split=(v:string)=>v.split(',').map(x=>x.trim()).filter(Boolean);
const statusLabel:Record<ReviewStatus,string>={not_reviewed:'Not Reviewed',review_complete:'AS-IS Review Complete',disclosure_required:'Disclosure Required',material_discrepancy:'Material Discrepancy',hold_from_marketing:'Hold From Marketing',owner_approved_with_disclosure:'Owner Approved With Disclosure'};
const tone=(s:ReviewStatus):'neutral'|'success'|'warning'|'danger'|'blue'=>s==='review_complete'?'success':s==='owner_approved_with_disclosure'?'blue':s==='hold_from_marketing'||s==='material_discrepancy'?'danger':s==='disclosure_required'?'warning':'neutral';
const blank=(portfolio:any):AsIsReview=>({id:'',portfolioId:portfolio?.id||'',status:'not_reviewed',saleCondition:'as_is',chainOfTitleProvided:false,accountMediaProvided:false,priorSaleHistoryProvided:false,originalAgreementsProvided:false,paymentHistoryProvided:false,advertisedAccountCount:portfolio?.accountCount,advertisedFaceValue:portfolio?.faceValue,duplicateCount:0,availableFields:[],missingFields:['Chain of title','Account-level media','Prior-sale history','Original agreements','Payment history'],detectedIssues:[],sellerDescription:'',reviewerNotes:'',disclosureText:'',ownerOverrideReason:''});
export default function AsIsReviewCenter(){const {portfolios}=usePortfolioStore();const {reviews,loading,error,save,generateDisclosure}=useAsIsReviewStore();const [portfolioId,setPortfolioId]=useState(portfolios[0]?.id||'');const portfolio=portfolios.find(p=>p.id===portfolioId);const existing=reviews.find(r=>r.portfolioId===portfolioId);const [form,setForm]=useState<AsIsReview>(()=>existing||blank(portfolio));const [issueText,setIssueText]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 useEffect(()=>{setForm(existing||blank(portfolio));setIssueText('')},[existing?.id,portfolioId]);
 const metrics=useMemo(()=>({complete:reviews.filter(r=>r.status==='review_complete').length,disclosure:reviews.filter(r=>['disclosure_required','owner_approved_with_disclosure'].includes(r.status)).length,hold:reviews.filter(r=>['hold_from_marketing','material_discrepancy'].includes(r.status)).length,unreviewed:portfolios.filter(p=>!reviews.some(r=>r.portfolioId===p.id)).length}),[reviews,portfolios]);
 const act=async(fn:()=>Promise<any>,ok:string)=>{setBusy(true);setMessage('');try{await fn();setMessage(ok)}catch(e){setMessage(e instanceof Error?e.message:'Action failed.')}finally{setBusy(false)}};
 const patch=(p:Partial<AsIsReview>)=>setForm(f=>({...f,...p}));const addIssue=()=>{if(!issueText.trim())return;patch({detectedIssues:[...form.detectedIssues,{severity:'warning',message:issueText.trim()}]});setIssueText('')};
 return <div className="mx-auto max-w-[1500px] p-5 md:p-8 lg:p-10"><header className="mb-8"><p className="text-sm font-semibold text-blue-600">AS-IS Portfolio Review & Disclosure Engine</p><h2 className="mt-1 text-3xl font-semibold">Review what is actually in the file</h2><p className="mt-2 max-w-4xl text-slate-500">Document missing history, verify the seller’s description, record discrepancies, and create a buyer-facing AS-IS disclosure without pretending the paper has chain or media.</p></header>
 {error&&<Card className="mb-5 border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</Card>}{message&&<Card className="mb-5 border-blue-200 bg-blue-50 p-4 text-sm text-blue-800">{message}</Card>}
 <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Review complete" value={metrics.complete}/><Metric label="Disclosure required" value={metrics.disclosure}/><Metric label="On hold" value={metrics.hold}/><Metric label="Not reviewed" value={metrics.unreviewed}/></div>
 <div className="grid gap-6 xl:grid-cols-[1.35fr_.8fr]"><div className="space-y-6"><Card className="p-5"><label className="text-sm font-semibold text-slate-700">Portfolio<select value={portfolioId} onChange={e=>setPortfolioId(e.target.value)} className="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3">{portfolios.map(p=><option key={p.id} value={p.id}>{p.name} · {p.accountCount.toLocaleString()} accounts</option>)}</select></label><div className="mt-4 flex flex-wrap gap-2"><Pill tone={tone(form.status)}>{statusLabel[form.status]}</Pill><Pill tone="neutral">AS IS</Pill>{existing?.reviewedAt&&<Pill tone="neutral">Reviewed {new Date(existing.reviewedAt).toLocaleDateString()}</Pill>}</div></Card>
 <Card className="p-5"><h3 className="font-semibold">Documentation actually provided</h3><p className="mt-1 text-sm text-slate-500">Unchecked items will appear as not provided in the disclosure.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{[['chainOfTitleProvided','Chain of title'],['accountMediaProvided','Account-level media'],['priorSaleHistoryProvided','Prior-sale history'],['originalAgreementsProvided','Original agreements'],['paymentHistoryProvided','Payment history']].map(([key,label])=><Check key={key} label={label} checked={Boolean((form as any)[key])} onChange={v=>patch({[key]:v} as any)}/>)}</div></Card>
 <Card className="p-5"><h3 className="font-semibold">File accuracy review</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><Tri label="Account numbers present" value={form.accountNumbersPresent} onChange={v=>patch({accountNumbersPresent:v})}/><Tri label="Creditor names consistent" value={form.creditorNamesConsistent} onChange={v=>patch({creditorNamesConsistent:v})}/><Tri label="Dates consistent with description" value={form.datesConsistent} onChange={v=>patch({datesConsistent:v})}/><Num label="Advertised account count" value={form.advertisedAccountCount} onChange={v=>patch({advertisedAccountCount:v})}/><Num label="Verified account count" value={form.verifiedAccountCount} onChange={v=>patch({verifiedAccountCount:v})}/><Num label="Duplicate records" value={form.duplicateCount} onChange={v=>patch({duplicateCount:v||0})}/><Num label="Advertised face value" value={form.advertisedFaceValue} onChange={v=>patch({advertisedFaceValue:v})}/><Num label="Verified face value" value={form.verifiedFaceValue} onChange={v=>patch({verifiedFaceValue:v})}/><Num label="Blank critical fields %" value={form.blankCriticalFieldPercent} onChange={v=>patch({blankCriticalFieldPercent:v})}/><label className="text-xs font-semibold text-slate-600">Oldest account date<input type="date" className={inputClass+' mt-1'} value={form.oldestAccountDate||''} onChange={e=>patch({oldestAccountDate:e.target.value})}/></label><label className="text-xs font-semibold text-slate-600">Newest account date<input type="date" className={inputClass+' mt-1'} value={form.newestAccountDate||''} onChange={e=>patch({newestAccountDate:e.target.value})}/></label></div></Card>
 <Card className="p-5"><h3 className="font-semibold">Fields and discrepancies</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><Text label="Available fields, comma separated" value={form.availableFields.join(', ')} onChange={v=>patch({availableFields:split(v)})}/><Text label="Missing fields, comma separated" value={form.missingFields.join(', ')} onChange={v=>patch({missingFields:split(v)})}/></div><div className="mt-4 flex gap-2"><input className={inputClass} placeholder="Example: Account dates are older than seller description" value={issueText} onChange={e=>setIssueText(e.target.value)}/><SecondaryButton onClick={addIssue}>Add issue</SecondaryButton></div><div className="mt-3 space-y-2">{form.detectedIssues.map((i,n)=><div key={n} className="flex items-center justify-between rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-900"><span><AlertTriangle className="mr-2 inline" size={15}/>{i.message}</span><button onClick={()=>patch({detectedIssues:form.detectedIssues.filter((_,x)=>x!==n)})} className="font-semibold">Remove</button></div>)}</div><textarea className={inputClass+' mt-4 min-h-24'} placeholder="Seller description" value={form.sellerDescription} onChange={e=>patch({sellerDescription:e.target.value})}/><textarea className={inputClass+' mt-3 min-h-24'} placeholder="Internal reviewer notes" value={form.reviewerNotes} onChange={e=>patch({reviewerNotes:e.target.value})}/></Card></div>
 <div className="space-y-6"><Card className="p-5"><h3 className="font-semibold">Review decision</h3><select value={form.status} onChange={e=>patch({status:e.target.value as ReviewStatus})} className="mt-3 w-full rounded-2xl border border-slate-200 px-4 py-3">{Object.entries(statusLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{form.status==='owner_approved_with_disclosure'&&<textarea className={inputClass+' mt-3 min-h-28'} placeholder="Required: explain why the portfolio may be marketed with disclosure" value={form.ownerOverrideReason} onChange={e=>patch({ownerOverrideReason:e.target.value})}/>}<PrimaryButton disabled={busy||loading||!portfolioId} className="mt-4 w-full" onClick={()=>act(()=>save({...form,portfolioId}), 'AS-IS review saved.')}><Save className="mr-2" size={17}/>Save review</PrimaryButton></Card>
 <Card className="p-5"><div className="flex items-center gap-3"><ShieldAlert className="text-blue-600"/><div><h3 className="font-semibold">Marketing gate</h3><p className="text-sm text-slate-500">Activation is allowed only after review completion or owner approval with disclosure.</p></div></div><div className="mt-4 rounded-2xl bg-slate-50 p-4 text-sm">{['review_complete','owner_approved_with_disclosure'].includes(form.status)?<span className="font-semibold text-emerald-700"><CheckCircle2 className="mr-2 inline" size={17}/>Eligible for marketing after save</span>:<span className="font-semibold text-red-700"><ShieldAlert className="mr-2 inline" size={17}/>Blocked from new activation</span>}</div></Card>
 <Card className="p-5"><div className="flex items-center gap-3"><FileCheck2 className="text-blue-600"/><h3 className="font-semibold">Buyer disclosure</h3></div><p className="mt-2 text-sm text-slate-500">Generate a plain-language summary of what is available, what is missing, and what the buyer must independently verify.</p><SecondaryButton disabled={busy||!existing} className="mt-4 w-full" onClick={()=>act(async()=>{const text=await generateDisclosure(portfolioId);patch({disclosureText:text})},'Disclosure generated.')}><Sparkles className="mr-2" size={17}/>Generate disclosure</SecondaryButton><textarea readOnly className={inputClass+' mt-4 min-h-72 bg-slate-50'} value={form.disclosureText} placeholder="Save the review, then generate the disclosure."/></Card></div></div></div>}
function Metric({label,value}:{label:string;value:number}){return <Card className="p-5"><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></Card>}
function Check({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="flex items-center gap-3 rounded-2xl border border-slate-200 p-4 text-sm font-medium"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="h-4 w-4"/>{label}</label>}
function Tri({label,value,onChange}:{label:string;value?:boolean;onChange:(v:boolean|undefined)=>void}){return <label className="text-xs font-semibold text-slate-600">{label}<select className="mt-1 w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm font-normal" value={value===undefined?'unknown':value?'yes':'no'} onChange={e=>onChange(e.target.value==='unknown'?undefined:e.target.value==='yes')}><option value="unknown">Unknown</option><option value="yes">Yes</option><option value="no">No</option></select></label>}
function Num({label,value,onChange}:{label:string;value?:number;onChange:(v:number|undefined)=>void}){return <label className="text-xs font-semibold text-slate-600">{label}<input type="number" className={inputClass+' mt-1'} value={value??''} onChange={e=>onChange(e.target.value===''?undefined:Number(e.target.value))}/></label>}
function Text({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="text-xs font-semibold text-slate-600">{label}<textarea className={inputClass+' mt-1 min-h-24'} value={value} onChange={e=>onChange(e.target.value)}/></label>}
