import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowRightLeft, Building2, CheckSquare, Filter, RefreshCw, Users } from 'lucide-react';
import { Card, Field, PrimaryButton, SecondaryButton, inputClass, Pill } from '../../components/Primitives';
import { supabase } from '../../lib/supabase';
import { useAgencyStore } from '../../store/AgencyStore';

type Workload={employee_id:string;full_name:string;email:string|null;is_active:boolean;permission_level:string;max_agencies:number;assigned_agencies:number;follow_ups_due_today:number;open_opportunities:number;pipeline_value:number;calls_today:number;emails_today:number};
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0);

export default function AssignmentCenter(){
 const {agencies,refresh}=useAgencyStore();
 const [workloads,setWorkloads]=useState<Workload[]>([]);const [selected,setSelected]=useState<string[]>([]);const [employeeId,setEmployeeId]=useState('');
 const [state,setState]=useState('');const [city,setCity]=useState('');const [category,setCategory]=useState('');const [onlyUnassigned,setOnlyUnassigned]=useState(true);
 const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const load=useCallback(async()=>{const {data,error}=await supabase.rpc('dmh_employee_workloads');if(error)setMessage(error.message);else setWorkloads((data||[]) as Workload[])},[]);
 useEffect(()=>{load()},[load]);
 const filtered=useMemo(()=>agencies.filter(a=>(!onlyUnassigned||!a.ownerEmployeeId)&&(!state||a.state.toLowerCase()===state.toLowerCase())&&(!city||a.city.toLowerCase()===city.toLowerCase())&&(!category||a.category.toLowerCase()===category.toLowerCase())),[agencies,onlyUnassigned,state,city,category]);
 const allSelected=filtered.length>0&&filtered.every(a=>selected.includes(a.id));
 async function assign(){if(!employeeId||!selected.length)return;setBusy(true);setMessage('');const {data,error}=await supabase.rpc('dmh_assign_agencies',{p_agency_ids:selected,p_employee_id:employeeId,p_reason:'Owner assignment center'});if(error)setMessage(error.message);else{setMessage(`${data||selected.length} agencies assigned.`);setSelected([]);await Promise.all([load(),refresh()]);}setBusy(false)}
 async function roundRobin(){setBusy(true);setMessage('');const {data,error}=await supabase.rpc('dmh_round_robin_assign',{p_only_unassigned:onlyUnassigned,p_state:state||null,p_city:city||null,p_category:category||null});if(error)setMessage(error.message);else{setMessage(`${data||0} agencies distributed by workload.`);setSelected([]);await Promise.all([load(),refresh()]);}setBusy(false)}
 return <div className="mx-auto max-w-[1500px] p-5 md:p-8 lg:p-10"><header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold text-blue-600">Employee Access & Assignment Engine · v1.4.2</p><h2 className="mt-1 text-3xl font-semibold">Assignment center</h2><p className="mt-2 text-slate-500">Control ownership, balance workloads, and keep every buyer relationship accountable.</p></div><SecondaryButton onClick={()=>Promise.all([load(),refresh()])}><RefreshCw className="mr-2" size={17}/>Refresh</SecondaryButton></header>
 {message&&<div className="mt-5 rounded-2xl bg-blue-50 p-4 text-sm text-blue-700">{message}</div>}
 <div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{workloads.map(w=><Card key={w.employee_id} className="p-5"><div className="flex items-start justify-between"><div><p className="font-semibold">{w.full_name}</p><p className="mt-1 text-xs text-slate-500">{w.email||'No email'}</p></div><Pill tone={w.is_active?'success':'danger'}>{w.is_active?'Active':'Inactive'}</Pill></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><Metric label="Agencies" value={`${w.assigned_agencies}/${w.max_agencies}`}/><Metric label="Due today" value={String(w.follow_ups_due_today)}/><Metric label="Open deals" value={String(w.open_opportunities)}/><Metric label="Pipeline" value={money(w.pipeline_value)}/><Metric label="Calls" value={String(w.calls_today)}/><Metric label="Emails" value={String(w.emails_today)}/></div><button onClick={async()=>{const permission=prompt('Permission level: sales_rep, senior_rep, or manager',w.permission_level);if(!permission)return;const limit=Number(prompt('Maximum assigned agencies',String(w.max_agencies)));if(!Number.isFinite(limit))return;setBusy(true);const {error}=await supabase.rpc('dmh_set_employee_assignment_settings',{p_employee_id:w.employee_id,p_permission_level:permission,p_max_agencies:limit});setMessage(error?error.message:'Employee assignment settings updated.');await load();setBusy(false)}} className="mt-4 w-full rounded-xl border border-slate-200 py-2 text-xs font-semibold hover:bg-slate-50">{w.permission_level.replace('_',' ')} · Edit access</button></Card>)}</div>
 <div className="mt-7 grid gap-6 xl:grid-cols-[1fr_2fr]"><Card className="p-6"><div className="flex items-center gap-3"><Filter className="text-blue-600"/><div><h3 className="font-semibold">Assignment rules</h3><p className="text-sm text-slate-500">Filter inventory before manual or round-robin assignment.</p></div></div><div className="mt-6 grid gap-4"><Field label="State"><input className={inputClass} value={state} onChange={e=>setState(e.target.value)} placeholder="Example: FL"/></Field><Field label="City"><input className={inputClass} value={city} onChange={e=>setCity(e.target.value)} placeholder="Example: Tampa"/></Field><Field label="Category"><input className={inputClass} value={category} onChange={e=>setCategory(e.target.value)} placeholder="Example: Collection agency"/></Field><label className="flex items-center gap-3 rounded-2xl bg-slate-50 p-4 text-sm"><input type="checkbox" checked={onlyUnassigned} onChange={e=>setOnlyUnassigned(e.target.checked)}/>Only unassigned agencies</label><PrimaryButton onClick={roundRobin} disabled={busy||!workloads.some(w=>w.is_active)}><ArrowRightLeft className="mr-2" size={17}/>{busy?'Working…':'Run round robin'}</PrimaryButton></div></Card>
 <Card className="overflow-hidden"><div className="flex flex-col gap-4 border-b border-slate-100 p-6 md:flex-row md:items-end"><div className="flex-1"><h3 className="font-semibold">Agency inventory</h3><p className="mt-1 text-sm text-slate-500">{filtered.length} agencies match the current rules. Select records for a direct assignment.</p></div><div className="flex flex-col gap-2 sm:flex-row"><select className={inputClass} value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">Select employee</option>{workloads.filter(w=>w.is_active).map(w=><option key={w.employee_id} value={w.employee_id}>{w.full_name} · {w.assigned_agencies}/{w.max_agencies}</option>)}</select><PrimaryButton onClick={assign} disabled={busy||!employeeId||!selected.length}><Users className="mr-2" size={17}/>Assign {selected.length||''}</PrimaryButton></div></div><div className="max-h-[620px] overflow-auto"><button onClick={()=>setSelected(allSelected?selected.filter(id=>!filtered.some(a=>a.id===id)):Array.from(new Set([...selected,...filtered.map(a=>a.id)])))} className="flex w-full items-center gap-3 border-b border-slate-100 px-6 py-4 text-left text-sm font-semibold"><CheckSquare size={17}/>{allSelected?'Clear visible':'Select visible'}</button>{filtered.map(a=><label key={a.id} className="flex cursor-pointer items-center gap-4 border-b border-slate-100 px-6 py-4 hover:bg-slate-50"><input type="checkbox" checked={selected.includes(a.id)} onChange={()=>setSelected(x=>x.includes(a.id)?x.filter(id=>id!==a.id):[...x,a.id])}/><div className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-600"><Building2 size={18}/></div><div className="min-w-0 flex-1"><p className="truncate font-semibold">{a.name}</p><p className="mt-1 text-xs text-slate-500">{[a.city,a.state,a.category].filter(Boolean).join(' · ')||'Location unavailable'}</p></div><div className="text-right"><p className="text-xs text-slate-400">Current owner</p><p className="mt-1 text-sm font-semibold">{a.ownerEmployeeId?a.ownerEmployeeName:'Unassigned'}</p></div></label>)}{!filtered.length&&<div className="p-10 text-center text-sm text-slate-500">No agencies match these assignment rules.</div>}</div></Card></div></div>
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 font-semibold">{value}</p></div>}
