import { ArrowLeft, FileKey2, FileSpreadsheet, ShieldCheck, Sparkles } from 'lucide-react';
import { useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Card, Field, PrimaryButton, SecondaryButton, inputClass } from '../../components/Primitives';
import { usePortfolioStore } from '../../store/PortfolioStore';

const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'});
export default function CreatePortfolio(){
 const nav=useNavigate();const {createPortfolio}=usePortfolioStore();const [file,setFile]=useState<File|null>(null);const [unmaskedFile,setUnmaskedFile]=useState<File|null>(null);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 const [asking,setAsking]=useState(0);const [commissionType,setCommissionType]=useState<'percentage'|'flat'>('percentage');const [commissionValue,setCommissionValue]=useState(10);const [commissionVisible,setCommissionVisible]=useState(true);
 const potential=useMemo(()=>commissionType==='percentage'?asking*(commissionValue/100):commissionValue,[asking,commissionType,commissionValue]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError('');const f=new FormData(e.currentTarget);try{const p=await createPortfolio({name:String(f.get('name')),originalCreditor:String(f.get('creditor')),category:String(f.get('category')),accountCount:Number(f.get('accounts')),faceValue:Number(f.get('faceValue')),askingPrice:Number(f.get('asking')),privateMinimum:Number(f.get('minimum')),acquisitionCost:Number(f.get('cost')),employeeCommissionType:commissionType,employeeCommissionValue:commissionValue,employeeCommissionVisible:commissionVisible,description:String(f.get('description')),sellingPoints:String(f.get('sellingPoints')).split('\n').map(x=>x.trim()).filter(Boolean),file:file||undefined,unmaskedFile:unmaskedFile||undefined});nav(`/portfolios/${p.id}`)}catch(err){setError(err instanceof Error?err.message:'Unable to create portfolio.')}finally{setSaving(false)}}
 return <div className="mx-auto max-w-5xl p-5 md:p-8 lg:p-10"><Link to="/portfolios" className="mb-6 inline-flex items-center text-sm font-semibold text-slate-500 hover:text-slate-900"><ArrowLeft className="mr-2" size={17}/>Portfolio queue</Link><header className="mb-8"><p className="text-sm font-semibold text-blue-600">New inventory</p><h2 className="mt-1 text-3xl font-semibold">Create portfolio</h2><p className="mt-2 text-slate-500">Create the listing now. The private unmasked file can be added now or later.</p></header><form onSubmit={submit} className="space-y-6">
 <Card className="p-6 md:p-8"><h3 className="text-xl font-semibold">Portfolio identity</h3><div className="mt-6 grid gap-5 md:grid-cols-2"><Field label="Portfolio name"><input className={inputClass} name="name" required/></Field><Field label="Original creditor"><input className={inputClass} name="creditor" required/></Field><Field label="Category"><input className={inputClass} name="category" required/></Field><Field label="Account count"><input className={inputClass} name="accounts" min="1" type="number" required/></Field><Field label="Total face value"><input className={inputClass} name="faceValue" min="0" step=".01" type="number" required/></Field></div></Card>
 <Card className="p-6 md:p-8"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 text-blue-600"/><div><h3 className="text-xl font-semibold">Owner economics</h3><p className="mt-1 text-sm text-slate-500">Minimum and acquisition cost remain owner-only.</p></div></div><div className="mt-6 grid gap-5 md:grid-cols-3"><Field label="Asking price"><input className={inputClass} name="asking" min="0" step=".01" type="number" required value={asking||''} onChange={e=>setAsking(Number(e.target.value))}/></Field><Field label="Private minimum"><input className={inputClass} name="minimum" min="0" step=".01" type="number" required/></Field><Field label="Acquisition cost"><input className={inputClass} name="cost" min="0" step=".01" type="number" required/></Field></div></Card>
 <Card className="overflow-hidden"><div className="border-b border-emerald-100 bg-emerald-50 p-6 md:p-8"><div className="flex items-start gap-3"><Sparkles className="mt-0.5 text-emerald-700"/><div><h3 className="text-xl font-semibold text-emerald-950">Employee earning opportunity</h3></div></div><div className="mt-6 grid gap-5 md:grid-cols-2"><Field label="Commission type"><select className={inputClass} value={commissionType} onChange={e=>setCommissionType(e.target.value as 'percentage'|'flat')}><option value="percentage">Percentage of sale price</option><option value="flat">Flat commission</option></select></Field><Field label={commissionType==='percentage'?'Commission percentage':'Flat commission amount'}><input className={inputClass} min="0" step=".01" type="number" value={commissionValue} onChange={e=>setCommissionValue(Number(e.target.value))}/></Field></div><div className="mt-6 rounded-2xl bg-white p-6 shadow-sm"><p className="text-sm font-semibold text-slate-500">Employee payout at asking price</p><p className="mt-2 text-4xl font-bold text-emerald-700">{money.format(potential)}</p></div><label className="mt-5 flex items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={commissionVisible} onChange={e=>setCommissionVisible(e.target.checked)}/>Show to employees</label></div></Card>
 <Card className="p-6 md:p-8"><h3 className="text-xl font-semibold">Sales package and files</h3><div className="mt-6 space-y-5"><Field label="Approved portfolio description"><textarea className={`${inputClass} min-h-28`} name="description" required/></Field><Field label="Selling points" hint="One per line"><textarea className={`${inputClass} min-h-28`} name="sellingPoints" required/></Field><FilePicker icon={<FileSpreadsheet/>} label="Masked file" note="Required before Ready. Employees may view, but not download." file={file} accept=".csv,.xlsx,.xls" onChange={setFile}/><FilePicker icon={<FileKey2/>} label="Unmasked file (optional)" note="Owner-only private vault. You may upload this later from Edit Portfolio." file={unmaskedFile} accept=".csv,.xlsx,.xls,.zip" onChange={setUnmaskedFile}/></div></Card>
 {error&&<p className="rounded-2xl bg-red-50 p-4 text-sm font-medium text-red-700">{error}</p>}<div className="flex justify-end gap-3"><Link to="/portfolios"><SecondaryButton type="button">Cancel</SecondaryButton></Link><PrimaryButton disabled={saving}>{saving?'Creating…':'Create draft'}</PrimaryButton></div></form></div>}
function FilePicker({icon,label,note,file,accept,onChange}:{icon:ReactNode;label:string;note:string;file:File|null;accept:string;onChange:(file:File|null)=>void}){return <Field label={label}><label className="flex cursor-pointer items-center gap-4 rounded-2xl border border-dashed border-slate-300 p-5 hover:border-blue-400"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-blue-700">{icon}</div><div className="flex-1"><p className="text-sm font-semibold">{file?file.name:`Choose ${label.toLowerCase()}`}</p><p className="mt-1 text-xs text-slate-500">{note}</p></div><input className="hidden" type="file" accept={accept} onChange={e=>onChange(e.target.files?.[0]||null)}/></label></Field>}
