import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { CalendarClock, CheckCircle2, CircleDollarSign, Clock3, FileCheck2, Handshake, Plus, RefreshCw, TrendingUp, MessageSquareText, ExternalLink, AlertTriangle } from 'lucide-react';
import { Card, Field, Pill, PrimaryButton, SecondaryButton, inputClass } from '../../components/Primitives';
import { supabase } from '../../lib/supabase';
import { usePipelineStore, type Opportunity } from '../../store/PipelineStore';
import { useAgencyStore } from '../../store/AgencyStore';
import { usePortfolioStore } from '../../store/PortfolioStore';
import { useConversationStore } from '../../store/ConversationStore';
import { useNavigate,useSearchParams } from 'react-router-dom';

type Deal = Opportunity & { current_offer?: number; current_counter?: number; decision_maker?: string; terms?: string; next_action?: string; next_action_at?: string; accepted_at?: string; funded_at?: string };
type Timeline = { id:string; opportunity_id:string; event_type:string; title:string; detail?:string; amount?:number; created_at:string };
type Checklist = { id:string; opportunity_id:string; item_key:string; label:string; completed:boolean; completed_at?:string };
type Dashboard = { activePipeline:number; negotiations:number; closing:number; fundedThisMonth:number; averageDaysToClose:number };
const money=(n=0)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const when=(v?:string)=>v?new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—';
const stageLabel=(v:string)=>v.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());

export default function DealCommand(){
 const {profile}=usePortfolioStore(); const {agencies}=useAgencyStore(); const {opportunities,refresh:refreshPipeline}=usePipelineStore();const {conversations,messages}=useConversationStore();const navigate=useNavigate();const [params]=useSearchParams();
 const [deals,setDeals]=useState<Deal[]>([]); const [timeline,setTimeline]=useState<Timeline[]>([]); const [checklist,setChecklist]=useState<Checklist[]>([]); const [dashboard,setDashboard]=useState<Dashboard>({activePipeline:0,negotiations:0,closing:0,fundedThisMonth:0,averageDaysToClose:0});
 const [selectedId,setSelectedId]=useState(''); const [notice,setNotice]=useState(''); const [loading,setLoading]=useState(true);
 const selected=deals.find(d=>d.id===selectedId)||deals[0];
 const agencyById=useMemo(()=>new Map(agencies.map(a=>[a.id,a])),[agencies]);
 async function load(){if(!profile)return;setLoading(true);setNotice('');const [d,t,c,k]=await Promise.all([
  supabase.from('sales_opportunities').select('*').eq('company_id',profile.company_id).order('updated_at',{ascending:false}),
  supabase.from('deal_timeline_events').select('*').eq('company_id',profile.company_id).order('created_at',{ascending:false}),
  supabase.from('deal_checklist_items').select('*').eq('company_id',profile.company_id).order('created_at'),
  supabase.rpc('dmh_deal_dashboard')
 ]); if(d.error){setNotice(d.error.message)} else setDeals((d.data||[]).map((x:any)=>({id:x.id,agencyId:x.agency_id,portfolioId:x.portfolio_id||undefined,ownerId:x.owner_id||undefined,title:x.title,stage:x.stage,askingPrice:Number(x.asking_price||0),probability:Number(x.probability||0),expectedCloseDate:x.expected_close_date||undefined,closedAmount:x.closed_amount==null?undefined:Number(x.closed_amount),lostReason:x.lost_reason||undefined,createdAt:x.created_at,updatedAt:x.updated_at,current_offer:x.current_offer==null?undefined:Number(x.current_offer),current_counter:x.current_counter==null?undefined:Number(x.current_counter),decision_maker:x.decision_maker||undefined,terms:x.terms||undefined,next_action:x.next_action||undefined,next_action_at:x.next_action_at||undefined,accepted_at:x.accepted_at||undefined,funded_at:x.funded_at||undefined})));
 if(!t.error)setTimeline((t.data||[]) as Timeline[]); if(!c.error)setChecklist((c.data||[]) as Checklist[]); if(!k.error&&k.data)setDashboard({activePipeline:Number(k.data.activePipeline||0),negotiations:Number(k.data.negotiations||0),closing:Number(k.data.closing||0),fundedThisMonth:Number(k.data.fundedThisMonth||0),averageDaysToClose:Number(k.data.averageDaysToClose||0)});setLoading(false)}
 useEffect(()=>{load()},[profile]);
 useEffect(()=>{const requested=params.get('deal');if(requested&&deals.some(d=>d.id===requested))setSelectedId(requested);else if(!selectedId&&deals[0])setSelectedId(deals[0].id)},[deals,selectedId,params]);
 async function saveDeal(){if(!selected)return;const value=(id:string)=>(document.getElementById(id) as HTMLInputElement|HTMLSelectElement|null)?.value||'';const patch:any={current_offer:value('dealOffer')?Number(value('dealOffer')):null,current_counter:value('dealCounter')?Number(value('dealCounter')):null,decision_maker:value('dealDecisionMaker')||null,terms:value('dealTerms')||null,probability:Number(value('dealProbability')||selected.probability),expected_close_date:value('dealCloseDate')||null,next_action:value('dealNextAction')||null,next_action_at:value('dealNextActionAt')||null,updated_at:new Date().toISOString()};const {error}=await supabase.from('sales_opportunities').update(patch).eq('id',selected.id);if(error){setNotice(error.message);return}await supabase.rpc('dmh_record_deal_event',{p_opportunity_id:selected.id,p_event_type:'deal_updated',p_title:'Deal terms updated',p_detail:patch.next_action||patch.terms||null,p_amount:patch.current_counter??patch.current_offer??null});setNotice('Deal updated.');await Promise.all([load(),refreshPipeline()])}
 async function record(action:'offer'|'counter'|'accepted'|'funded'){if(!selected)return;const amount=Number((document.getElementById('dealEventAmount') as HTMLInputElement|null)?.value||0)||null;const detail=(document.getElementById('dealEventDetail') as HTMLInputElement|null)?.value||'';const titles={offer:'Buyer offer received',counter:'Counter sent',accepted:'Terms accepted',funded:'Funds received'};const patch:any={updated_at:new Date().toISOString()};if(action==='offer')patch.current_offer=amount;if(action==='counter')patch.current_counter=amount;if(action==='accepted'){patch.stage='contracts';patch.accepted_at=new Date().toISOString()}if(action==='funded'){patch.stage='closed_won';patch.closed_amount=amount||selected.current_counter||selected.current_offer||selected.askingPrice;patch.funded_at=new Date().toISOString();patch.closed_at=new Date().toISOString()};const {error}=await supabase.from('sales_opportunities').update(patch).eq('id',selected.id);if(error){setNotice(error.message);return}await supabase.rpc('dmh_record_deal_event',{p_opportunity_id:selected.id,p_event_type:action,p_title:titles[action],p_detail:detail||null,p_amount:amount});if(action==='accepted'||action==='funded')await supabase.rpc('dmh_initialize_deal_checklist',{p_opportunity_id:selected.id});setNotice(`${titles[action]} recorded.`);await Promise.all([load(),refreshPipeline()])}
 async function toggle(item:Checklist){const {error}=await supabase.rpc('dmh_toggle_deal_checklist',{p_item_id:item.id,p_completed:!item.completed});if(error){setNotice(error.message);return}await load()}
 const linkedConversation=selected?conversations.find(c=>c.opportunityId===selected.id)||conversations.find(c=>c.agencyId===selected.agencyId):undefined;const linkedMessages=linkedConversation?messages.filter(m=>m.conversationId===linkedConversation.id):[];const latestMessage=linkedMessages[linkedMessages.length-1];const unreadReplies=linkedMessages.filter(m=>m.direction==='inbound'&&!m.isRead).length;
 const activeDeals=deals.filter(d=>!['closed_won','closed_lost'].includes(d.stage)); const selectedTimeline=selected?timeline.filter(t=>t.opportunity_id===selected.id):[]; const selectedChecklist=selected?checklist.filter(c=>c.opportunity_id===selected.id):[];
 return <div className="mx-auto max-w-[1500px] p-5 md:p-10"><header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold text-blue-600">Deal-to-Conversation Integration · v1.7.1</p><h2 className="mt-1 text-3xl font-semibold">Turn active conversations into funded deals.</h2><p className="mt-2 text-slate-500">Offers, counters, terms, closing tasks and funding history in one owner-controlled workspace.</p></div><SecondaryButton onClick={load}><RefreshCw size={17} className="mr-2"/>Refresh</SecondaryButton></header>{notice&&<div className="mt-5 rounded-2xl bg-blue-50 p-4 text-sm font-semibold text-blue-800">{notice}</div>}
 <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat icon={<TrendingUp/>} label="Active pipeline" value={money(dashboard.activePipeline)}/><Stat icon={<Handshake/>} label="Negotiations" value={String(dashboard.negotiations)}/><Stat icon={<FileCheck2/>} label="Closing" value={String(dashboard.closing)}/><Stat icon={<CircleDollarSign/>} label="Funded this month" value={money(dashboard.fundedThisMonth)}/><Stat icon={<Clock3/>} label="Avg. days to close" value={String(dashboard.averageDaysToClose)}/></div>
 <div className="mt-7 grid gap-6 xl:grid-cols-[.72fr_1.28fr]"><Card className="overflow-hidden"><div className="border-b border-slate-100 p-5"><h3 className="font-semibold">Active deals</h3><p className="mt-1 text-sm text-slate-500">{activeDeals.length} open opportunities</p></div>{loading?<p className="p-5 text-slate-500">Loading deals…</p>:activeDeals.length===0?<p className="p-5 text-slate-500">No active opportunities yet. Create one from Pipeline.</p>:<div className="divide-y divide-slate-100">{activeDeals.map(d=><button key={d.id} onClick={()=>setSelectedId(d.id)} className={`w-full p-5 text-left ${selected?.id===d.id?'bg-blue-50':'hover:bg-slate-50'}`}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{agencyById.get(d.agencyId)?.name||d.title}</p><p className="mt-1 text-sm text-slate-500">{d.title}</p></div><Pill tone={d.stage==='contracts'?'success':'blue'}>{stageLabel(d.stage)}</Pill></div><div className="mt-4 flex items-center justify-between text-sm"><span>{money(d.current_counter||d.current_offer||d.askingPrice)}</span><span className="text-slate-500">{d.probability}%</span></div></button>)}</div>}</Card>
 <Card className="p-6">{!selected?<div className="grid min-h-[500px] place-items-center text-slate-400">Select a deal.</div>:<div><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><p className="text-sm text-slate-500">{selected.title}</p><h3 className="mt-1 text-2xl font-semibold">{agencyById.get(selected.agencyId)?.name||'Agency'}</h3><p className="mt-2 text-sm text-slate-500">Created {when(selected.createdAt)}</p></div><div className="text-left md:text-right"><p className="text-sm text-slate-500">Current deal value</p><p className="mt-1 text-3xl font-semibold">{money(selected.current_counter||selected.current_offer||selected.askingPrice)}</p></div></div>
 <div className="mt-6 rounded-2xl border border-blue-100 bg-blue-50/70 p-4"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2 text-blue-700"><MessageSquareText size={18}/><h4 className="font-semibold">Buyer conversation</h4>{unreadReplies>0&&<Pill tone="warning">{unreadReplies} unread</Pill>}</div>{linkedConversation?<><p className="mt-2 text-sm text-slate-600">{latestMessage?`${latestMessage.direction==='inbound'?'Buyer':'DMH'}: ${latestMessage.body.slice(0,120)}`:'Conversation has no messages yet.'}</p><p className="mt-2 text-xs text-slate-500">Next follow-up: {linkedConversation.nextFollowUpAt?when(linkedConversation.nextFollowUpAt):'Not scheduled'}</p></>:<p className="mt-2 text-sm text-slate-600">No conversation is linked to this deal yet.</p>}</div>{linkedConversation&&<PrimaryButton onClick={()=>navigate(`/conversations?conversation=${linkedConversation.id}`)}><ExternalLink className="mr-2" size={16}/>Open conversation</PrimaryButton>}</div>{linkedConversation&&linkedConversation.lastInboundAt&&(!linkedConversation.lastOutboundAt||new Date(linkedConversation.lastInboundAt)>new Date(linkedConversation.lastOutboundAt))&&<p className="mt-3 flex items-center gap-2 text-sm font-semibold text-amber-700"><AlertTriangle size={15}/>Buyer replied and the deal has not received a company response yet.</p>}</div>
 <div className="mt-7 grid gap-4 md:grid-cols-2"><Field label="Buyer offer"><input id="dealOffer" type="number" className={inputClass} defaultValue={selected.current_offer||''}/></Field><Field label="Current counter"><input id="dealCounter" type="number" className={inputClass} defaultValue={selected.current_counter||''}/></Field><Field label="Decision maker"><input id="dealDecisionMaker" className={inputClass} defaultValue={selected.decision_maker||''}/></Field><Field label="Probability"><input id="dealProbability" type="number" min="0" max="100" className={inputClass} defaultValue={selected.probability}/></Field><Field label="Expected close"><input id="dealCloseDate" type="date" className={inputClass} defaultValue={selected.expectedCloseDate||''}/></Field><Field label="Next action date"><input id="dealNextActionAt" type="datetime-local" className={inputClass} defaultValue={selected.next_action_at?.slice(0,16)||''}/></Field></div><div className="mt-4"><Field label="Terms"><textarea id="dealTerms" className={`${inputClass} min-h-24`} defaultValue={selected.terms||''}/></Field></div><div className="mt-4"><Field label="Next action"><input id="dealNextAction" className={inputClass} defaultValue={selected.next_action||''}/></Field></div><PrimaryButton className="mt-4" onClick={saveDeal}>Save deal</PrimaryButton>
 <div className="mt-8 border-t border-slate-100 pt-6"><h4 className="font-semibold">Record negotiation event</h4><div className="mt-4 grid gap-3 md:grid-cols-[.6fr_1fr]"><input id="dealEventAmount" type="number" className={inputClass} placeholder="Amount"/><input id="dealEventDetail" className={inputClass} placeholder="Terms or note"/></div><div className="mt-3 grid grid-cols-2 gap-2 lg:grid-cols-4"><SecondaryButton onClick={()=>record('offer')}>Offer received</SecondaryButton><SecondaryButton onClick={()=>record('counter')}>Counter sent</SecondaryButton><PrimaryButton onClick={()=>record('accepted')}>Accepted</PrimaryButton><PrimaryButton onClick={()=>record('funded')}>Funded</PrimaryButton></div></div>
 <div className="mt-8 grid gap-6 lg:grid-cols-2"><section><h4 className="font-semibold">Deal timeline</h4><div className="mt-3 space-y-3">{selectedTimeline.length===0?<p className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-500">No negotiation events recorded yet.</p>:selectedTimeline.map(e=><div key={e.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{e.title}</p><p className="mt-1 text-sm text-slate-500">{e.detail||stageLabel(e.event_type)}</p></div>{e.amount!=null&&<span className="font-semibold">{money(Number(e.amount))}</span>}</div><p className="mt-3 text-xs text-slate-400">{when(e.created_at)}</p></div>)}</div></section><section><div className="flex items-center justify-between"><h4 className="font-semibold">Closing checklist</h4>{selectedChecklist.length===0&&<button className="text-sm font-semibold text-blue-600" onClick={async()=>{await supabase.rpc('dmh_initialize_deal_checklist',{p_opportunity_id:selected.id});await load()}}><Plus size={15} className="mr-1 inline"/>Initialize</button>}</div><div className="mt-3 space-y-2">{selectedChecklist.length===0?<p className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-500">Checklist starts when terms are accepted, or initialize it now.</p>:selectedChecklist.map(item=><button key={item.id} onClick={()=>toggle(item)} className="flex w-full items-center gap-3 rounded-2xl border border-slate-200 p-4 text-left hover:bg-slate-50">{item.completed?<CheckCircle2 className="text-emerald-600"/>:<span className="h-6 w-6 rounded-full border-2 border-slate-300"/>}<span className={item.completed?'text-slate-400 line-through':'font-medium'}>{item.label}</span></button>)}</div></section></div>
 </div>}</Card></div></div>}
function Stat({icon,label,value}:{icon:ReactNode;label:string;value:string}){return <Card className="p-5"><div className="text-blue-600">{icon}</div><p className="mt-4 text-2xl font-semibold">{value}</p><p className="mt-1 text-sm text-slate-500">{label}</p></Card>}
