import { useCallback, useEffect, useState } from 'react';
import { Check, Copy, RefreshCw, ShieldCheck, UserRound, Users } from 'lucide-react';
import { Card, Pill, PrimaryButton, SecondaryButton } from '../../components/Primitives';
import { supabase } from '../../lib/supabase';
import { usePortfolioStore } from '../../store/PortfolioStore';

type Member={id:string;full_name:string;email:string|null;role:'owner'|'employee';is_active:boolean;created_at:string};

export default function EmployeeManagement(){
 const {profile}=usePortfolioStore();
 const [members,setMembers]=useState<Member[]>([]);const [joinCode,setJoinCode]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [message,setMessage]=useState('');
 const load=useCallback(async()=>{if(!profile)return;setLoading(true);setMessage('');const [companyResult,membersResult]=await Promise.all([
  supabase.from('companies').select('join_code').eq('id',profile.company_id).single(),
  supabase.rpc('dmh_company_members')
 ]);if(companyResult.error)setMessage(companyResult.error.message);else setJoinCode(companyResult.data?.join_code||'');if(membersResult.error)setMessage(membersResult.error.message);else setMembers((membersResult.data||[]) as Member[]);setLoading(false)},[profile]);
 useEffect(()=>{load()},[load]);
 async function toggle(member:Member){setBusy(member.id);setMessage('');const {error}=await supabase.rpc('dmh_set_employee_active',{p_employee_id:member.id,p_is_active:!member.is_active});if(error)setMessage(error.message);else await load();setBusy('')}
 async function rotate(){setBusy('rotate');setMessage('');const {data,error}=await supabase.rpc('dmh_rotate_join_code');if(error)setMessage(error.message);else{setJoinCode(String(data));setMessage('A new employee join code is active.');}setBusy('')}
 async function copy(){await navigator.clipboard.writeText(joinCode);setMessage('Join code copied.');}
 const employees=members.filter(m=>m.role==='employee');
 return <div className="mx-auto max-w-6xl p-5 md:p-8 lg:p-10"><header><p className="text-sm font-semibold text-blue-600">Company membership engine</p><h2 className="mt-1 text-3xl font-semibold">Employees</h2><p className="mt-2 text-slate-500">Every employee below belongs to the same Data Market House workspace and receives the same active portfolio.</p></header>
 <div className="mt-8 grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><div className="space-y-6"><Card className="p-6"><div className="flex items-center gap-3"><div className="rounded-2xl bg-blue-50 p-3 text-blue-600"><Users/></div><div><p className="text-sm text-slate-500">Active employees</p><p className="text-2xl font-semibold">{employees.filter(x=>x.is_active).length}</p></div></div></Card>
 <Card className="p-6"><p className="text-sm font-semibold">Employee join code</p><p className="mt-2 text-sm leading-6 text-slate-500">Give this code only to approved employees. They select <b>Join as employee</b> when creating their account.</p><div className="mt-5 flex items-center gap-2 rounded-2xl bg-slate-950 px-4 py-4 text-white"><span className="flex-1 font-mono text-xl tracking-[.18em]">{joinCode||'—'}</span><button onClick={copy} className="rounded-xl p-2 hover:bg-white/10" title="Copy join code"><Copy size={18}/></button></div><SecondaryButton className="mt-4 w-full" onClick={rotate} disabled={busy==='rotate'}><RefreshCw className="mr-2" size={17}/>{busy==='rotate'?'Rotating…':'Rotate code'}</SecondaryButton></Card>
 <Card className="flex gap-3 p-5"><ShieldCheck className="shrink-0 text-emerald-600"/><div><p className="text-sm font-semibold">Owner economics remain private</p><p className="mt-1 text-xs leading-5 text-slate-500">Employee portfolio queries exclude acquisition cost and private minimum at the data-request level.</p></div></Card></div>
 <Card className="overflow-hidden"><div className="border-b border-slate-100 px-6 py-5"><h3 className="font-semibold">Company members</h3><p className="mt-1 text-sm text-slate-500">Deactivate an employee immediately without deleting their history.</p></div>{message&&<div className="mx-6 mt-5 rounded-2xl bg-blue-50 p-3 text-sm text-blue-700">{message}</div>}{loading?<div className="p-8 text-sm text-slate-500">Loading company members…</div>:<div className="divide-y divide-slate-100">{members.map(member=><div key={member.id} className="flex flex-col gap-4 p-6 sm:flex-row sm:items-center"><div className="flex flex-1 items-center gap-4"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-slate-100 text-slate-600"><UserRound size={20}/></div><div><div className="flex items-center gap-2"><p className="font-semibold">{member.full_name}</p>{member.role==='owner'&&<Pill tone="blue">Owner</Pill>}</div><p className="mt-1 text-sm text-slate-500">{member.email||'No email available'}</p></div></div><div className="flex items-center gap-3"><Pill tone={member.is_active?'success':'danger'}>{member.is_active?'Active':'Inactive'}</Pill>{member.role==='employee'&&<PrimaryButton onClick={()=>toggle(member)} disabled={busy===member.id} className={member.is_active?'!bg-slate-900 hover:!bg-slate-800':''}>{member.is_active?'Deactivate':<><Check className="mr-2" size={16}/>Activate</>}</PrimaryButton>}</div></div>)}</div>}</Card></div></div>;
}
