import {FormEvent,useEffect,useState} from 'react';
import {ArrowLeft,CheckCircle2,Clock3,Download,FileUp,History,LockKeyhole,MessageSquare,PackageCheck,ShieldCheck,WalletCards} from 'lucide-react';
import {Link,useParams} from 'react-router-dom';
import {Card,Field,Pill,PrimaryButton,SecondaryButton,inputClass} from '../../components/Primitives';
import {useBuyerPortalStore,type DealRoomSnapshot} from '../../store/BuyerPortalStore';
import {usePortfolioStore} from '../../store/PortfolioStore';
import {supabase} from '../../lib/supabase';

const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v||0);
const when=(v:string)=>v?new Date(v).toLocaleString():'Pending';
const safeName=(name:string)=>name.replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/-+/g,'-');

export default function OwnerBuyerDealRoom(){
 const {id}=useParams();
 const {portfolios,profile}=usePortfolioStore();
 const {buyers,loadRoom,offerAction,dealGate,closeDeal,uploadDocument,sendMessage}=useBuyerPortalStore();
 const [data,setData]=useState<DealRoomSnapshot|null>(null);
 const [message,setMessage]=useState('');
 const [busy,setBusy]=useState(false);
 const [uploading,setUploading]=useState(false);
 const p=portfolios.find(x=>x.id===id);
 const reload=async()=>{if(id)setData(await loadRoom(id))};
 useEffect(()=>{reload().catch(e=>setMessage(e.message))},[id]);
 const run=async(fn:()=>Promise<unknown>,ok:string)=>{setBusy(true);try{await fn();await reload();setMessage(ok)}catch(e){setMessage(e instanceof Error?e.message:'Action failed')}finally{setBusy(false)}};
 if(!p)return <div className="p-8">Portfolio unavailable.</div>;
 const r=data?.room,o=data?.offer,b=buyers.find(x=>x.id===r?.buyer_id);
 const finalFile=(data?.documents||[]).find((d:any)=>d.document_type==='final_portfolio'&&d.status!=='superseded');

 async function configureDelivery(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const method=String(f.get('method'));const eta=method==='delayed'?Number(f.get('eta')):null;await run(async()=>{const {error}=await supabase.rpc('dmh_configure_delivery',{p_room_id:r.id,p_delivery_method:method,p_eta_hours:eta});if(error)throw error},method==='immediate'?'Immediate download configured.':'Delayed delivery countdown configured.');}
 async function uploadVault(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile||!r)return;const f=new FormData(e.currentTarget);const file=f.get('file');if(!(file instanceof File)||!file.size){setMessage('Choose the unmasked portfolio file.');return}setUploading(true);try{const path=`${profile.company_id}/${r.id}/${crypto.randomUUID()}-${safeName(file.name)}`;const up=await supabase.storage.from('buyer-delivery-vault').upload(path,file,{upsert:false,contentType:file.type||'application/octet-stream'});if(up.error)throw up.error;const reg=await supabase.rpc('dmh_register_vault_file',{p_room_id:r.id,p_title:file.name,p_storage_path:path});if(reg.error){await supabase.storage.from('buyer-delivery-vault').remove([path]);throw reg.error}await reload();setMessage('Unmasked file secured in the private Owner-to-Buyer vault.');e.currentTarget.reset()}catch(err){setMessage(err instanceof Error?err.message:'Upload failed')}finally{setUploading(false)}}
 async function doc(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(()=>uploadDocument(r!.id,String(f.get('type')),String(f.get('title')),String(f.get('url')),f.get('visible')==='on'),'Document added.');e.currentTarget.reset()}
 async function msg(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(()=>sendMessage(r!.buyer_id,p!.id,String(f.get('body')),o?.id),'Message sent.');e.currentTarget.reset()}
 async function verifyPayment(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(async()=>{const {error}=await supabase.rpc('dmh_verify_buyer_payment',{p_room_id:r.id,p_method:String(f.get('method')),p_reference:String(f.get('reference')||'')||null,p_amount:Number(f.get('amount'))||null,p_notes:String(f.get('notes')||'')||null});if(error)throw error},r.delivery_method==='immediate'?'Payment verified and buyer file unlocked.':'Payment verified and buyer delivery countdown started.')}
 async function release(){await run(async()=>{const {error}=await supabase.rpc('dmh_release_buyer_files',{p_room_id:r.id});if(error)throw error},'Unmasked portfolio released directly to buyer.')}

 return <div className="p-5 lg:p-8"><div className="mx-auto max-w-7xl">
  <Link to="/deal-rooms" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft size={16}/>Deal Rooms</Link>
  <div className="mt-5 flex flex-wrap justify-between gap-4"><div><p className="text-xs font-bold tracking-[.2em] text-blue-600">OWNER DELIVERY CONTROL</p><h1 className="mt-2 text-3xl font-semibold">{p.name}</h1><p className="mt-2 text-sm text-slate-500">{b?.company_name||'Buyer'} · Current offer {money(o?.current_amount)}</p></div><Pill tone={r?.status==='closed'?'success':'blue'}>{r?.status?.replaceAll('_',' ')||'No active room'}</Pill></div>
  {message&&<p className="mt-5 rounded-2xl bg-blue-50 p-4 text-sm text-blue-700">{message}</p>}
  {!r?<Card className="mt-7 p-8 text-center text-slate-500">No active buyer deal room for this portfolio.</Card>:<div className="mt-7 grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><div className="space-y-6">
   <Card className="p-6"><div className="flex items-center gap-3"><ShieldCheck className="text-blue-600"/><div><h2 className="font-semibold">Delivery promise shown to buyer</h2><p className="text-sm text-slate-500">Choose this before payment is verified.</p></div></div><form className="mt-5 grid gap-4" onSubmit={configureDelivery}><div className="grid gap-3 sm:grid-cols-2"><label className="rounded-2xl border border-slate-200 p-4"><input type="radio" name="method" value="immediate" defaultChecked={r.delivery_method==='immediate'}/><span className="ml-2 font-semibold">Immediate Download</span><p className="mt-2 text-xs text-slate-500">File must already be secured. Owner payment verification unlocks it immediately.</p></label><label className="rounded-2xl border border-slate-200 p-4"><input type="radio" name="method" value="delayed" defaultChecked={r.delivery_method!=='immediate'}/><span className="ml-2 font-semibold">Wait Period</span><p className="mt-2 text-xs text-slate-500">Countdown begins only after Owner verifies payment.</p></label></div><Field label="Delayed delivery time"><select className={inputClass} name="eta" defaultValue={r.delivery_eta_hours||24}><option value="12">12 hours</option><option value="24">24 hours</option><option value="48">48 hours</option><option value="72">3 days</option><option value="120">5 days</option></select></Field><PrimaryButton disabled={busy}>Save Delivery Method</PrimaryButton></form>{r.delivery_configured_at&&<div className="mt-4 rounded-2xl bg-slate-50 p-4 text-sm"><p className="font-semibold capitalize">{r.delivery_method==='immediate'?'Immediate download':'Wait period delivery'}</p><p className="mt-1 text-slate-500">{r.delivery_method==='delayed'?`${r.delivery_eta_hours} hours after Owner payment confirmation`:'Unlocks immediately after Owner payment confirmation'}</p></div>}</Card>
   <Card className="p-6"><div className="flex items-center gap-3"><FileUp className="text-blue-600"/><div><h2 className="font-semibold">Private unmasked-file vault</h2><p className="text-sm text-slate-500">Owner uploads. Buyer downloads. Employees have no database or storage access.</p></div></div>{finalFile?<div className="mt-5 rounded-2xl bg-emerald-50 p-5 text-emerald-800"><PackageCheck/><p className="mt-3 font-semibold">Unmasked file secured</p><p className="mt-1 text-sm">{finalFile.title}</p><p className="mt-1 text-xs">{r.final_file_released_at?'Released directly to buyer':'Locked in private storage'}</p></div>:null}<form className="mt-5 space-y-4" onSubmit={uploadVault}><Field label={finalFile?'Replace unmasked file':'Upload unmasked file'}><input className={inputClass} name="file" type="file" required/></Field><PrimaryButton className="w-full" disabled={uploading}>{uploading?'Securing file…':'Upload to Private Vault'}</PrimaryButton></form></Card>
   <Card className="p-6"><h2 className="font-semibold">Closing gates</h2><div className="mt-5 grid gap-3 sm:grid-cols-4">{[['Agreement approved',r.agreement_approved_at],['Payment verified',r.payment_confirmed_at],['Files released',r.final_file_released_at],['Transaction closed',r.closed_at]].map(([x,v]:any)=><div key={x} className={`rounded-2xl p-4 ${v?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{v?<CheckCircle2/>:<LockKeyhole/>}<p className="mt-3 text-sm font-semibold">{x}</p><p className="mt-1 text-[11px]">{v?when(v):'Pending'}</p></div>)}</div><div className="mt-5 flex flex-wrap gap-2"><PrimaryButton onClick={()=>run(()=>dealGate(r.id,'agreement'),'Purchase agreement approved.')} disabled={busy||!!r.agreement_approved_at}>Approve Agreement</PrimaryButton>{r.delivery_method==='delayed'&&<PrimaryButton onClick={release} disabled={busy||!r.payment_confirmed_at||!finalFile||!!r.final_file_released_at}>Release to Buyer</PrimaryButton>}<PrimaryButton onClick={()=>run(()=>closeDeal(r.id),'Deal closed and financial records created.')} disabled={busy||!r.final_file_released_at||r.status==='closed'}>Close Deal</PrimaryButton></div></Card>
   <Card className="p-6"><div className="flex items-center gap-3"><WalletCards className="text-blue-600"/><div><h2 className="font-semibold">Owner-only payment verification</h2><p className="text-sm text-slate-500">No employee or buyer action can start delivery.</p></div></div>{r.payment_confirmed_at?<div className="mt-5 rounded-2xl bg-emerald-50 p-5 text-emerald-800"><p className="font-semibold">Payment verified</p><p className="mt-2 text-sm">{r.payment_method||'Payment'}{r.payment_reference?` · Reference ${r.payment_reference}`:''}</p><p className="mt-1 text-sm">{r.payment_amount?money(r.payment_amount):'Amount not recorded'} · {when(r.payment_confirmed_at)}</p>{r.delivery_due_at&&!r.final_file_released_at&&<p className="mt-2 flex items-center gap-2 font-semibold"><Clock3 size={16}/>Delivery due {when(r.delivery_due_at)}</p>}</div>:<form className="mt-5 grid gap-4" onSubmit={verifyPayment}><div className="grid gap-4 sm:grid-cols-2"><Field label="Payment method"><select className={inputClass} name="method" required><option value="">Select method</option><option>Wire</option><option>ACH</option><option>Check</option><option>Crypto</option><option>Other</option></select></Field><Field label="Amount received"><input className={inputClass} name="amount" type="number" min="0" step="0.01" defaultValue={o?.current_amount||''}/></Field></div><Field label="Reference number"><input className={inputClass} name="reference"/></Field><Field label="Internal notes"><textarea className={`${inputClass} min-h-24`} name="notes"/></Field><PrimaryButton disabled={busy||!r.agreement_approved_at||!r.delivery_configured_at||(r.delivery_method==='immediate'&&!finalFile)}>Verify Payment & Start Delivery</PrimaryButton></form>}</Card>
   <Card className="p-6"><div className="flex items-center gap-3"><History className="text-blue-600"/><h2 className="font-semibold">Audit trail</h2></div><div className="mt-4 space-y-3">{(data?.events||[]).length===0?<p className="text-sm text-slate-500">Events will appear here.</p>:(data?.events||[]).map((e:any)=><div key={e.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex justify-between gap-2"><p className="font-semibold capitalize">{String(e.event_type).replaceAll('_',' ')}</p><p className="text-xs text-slate-500">{when(e.created_at)}</p></div></div>)}</div></Card>
   <Card className="p-6"><div className="flex items-center gap-3"><Download className="text-blue-600"/><h2 className="font-semibold">Buyer download history</h2></div><div className="mt-4 space-y-3">{(data?.downloads||[]).length===0?<p className="text-sm text-slate-500">No downloads yet.</p>:(data?.downloads||[]).map((d:any)=><div key={d.id} className="rounded-2xl bg-slate-50 p-4"><p className="font-semibold">File downloaded</p><p className="mt-1 text-xs text-slate-500">{when(d.downloaded_at)}</p></div>)}</div></Card>
  </div><div className="space-y-6">
   <Card className="p-6"><h2 className="font-semibold">Non-vault deal document</h2><p className="mt-1 text-xs text-slate-500">Never use this form for an unmasked portfolio.</p><form className="mt-4 space-y-4" onSubmit={doc}><Field label="Document type"><select className={inputClass} name="type"><option value="purchase_agreement">Purchase agreement</option><option value="payment_instructions">Payment instructions</option><option value="payment_proof">Payment proof</option><option value="other">Other</option></select></Field><Field label="Title"><input className={inputClass} name="title" required/></Field><Field label="Secure URL"><input className={inputClass} name="url"/></Field><label className="flex gap-3 text-sm"><input type="checkbox" name="visible"/>Visible to buyer immediately</label><PrimaryButton className="w-full">Add document</PrimaryButton></form></Card>
   <Card className="p-6"><h2 className="font-semibold">Document checklist</h2><div className="mt-4 space-y-3">{(data?.documents||[]).map((d:any)=><div key={d.id} className="rounded-2xl bg-slate-50 p-4"><p className="font-semibold">{d.title}</p><p className="mt-1 text-xs capitalize text-slate-500">{d.document_type.replaceAll('_',' ')} · {d.status} · {d.visible_to_buyer?'Buyer visible':'Locked'}</p></div>)}</div></Card>
   <Card className="p-6"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">Owner negotiation control</h2><p className="mt-1 text-xs text-slate-500">Only Owner can approve, reject, or counter a buyer offer. Employees remain view-only.</p></div><Pill tone={o?.status==='accepted'?'success':'blue'}>{o?.status||'pending'}</Pill></div>{o&&<div className="mt-5 rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold tracking-[.18em] text-slate-400">CURRENT PRICE</p><p className="mt-2 text-3xl font-semibold">{money(o.current_amount)}</p><p className="mt-1 text-xs text-slate-500">{o.pricing_path==='asking_price'?'Buyer accepted asking price':'Negotiated offer'}</p></div>}<div className="mt-4 space-y-3">{(data?.rounds||[]).map((x:any)=><div key={x.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><p className="font-semibold capitalize">{x.actor_role} · {x.action}</p><p className="font-semibold">{money(x.amount)}</p></div>{x.message&&<p className="mt-2 text-sm text-slate-500">{x.message}</p>}</div>)}</div>{o&&o.status!=='accepted'&&o.status!=='rejected'&&<><form className="mt-5 grid gap-3" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await run(()=>offerAction(o.id,'counter',Number(f.get('amount')),String(f.get('message')||'')),'Counteroffer sent to buyer.')}}><Field label="Owner counteroffer"><input className={inputClass} name="amount" type="number" min="1" step="0.01" required/></Field><Field label="Message"><input className={inputClass} name="message" placeholder="Optional terms or explanation"/></Field><PrimaryButton>Send Counteroffer</PrimaryButton></form><div className="mt-3 flex flex-wrap gap-2"><PrimaryButton onClick={()=>run(()=>offerAction(o.id,'accept',undefined,'Owner approved final price',new Date(Date.now()+72*3600000).toISOString()),'Final price approved. Purchase Agreement is ready.')}>Approve Final Price</PrimaryButton><SecondaryButton onClick={()=>run(()=>offerAction(o.id,'reject',undefined,'Owner declined offer'),'Offer declined.')}>Decline Offer</SecondaryButton></div></>}{o?.status==='accepted'&&<div className="mt-5 rounded-2xl bg-emerald-50 p-4 text-sm text-emerald-800"><p className="font-semibold">Final price approved · {money(o.current_amount)}</p><p className="mt-1">Purchase Agreement stage is unlocked.</p></div>}</Card>
   <Card className="p-6"><div className="flex items-center gap-3"><MessageSquare className="text-blue-600"/><h2 className="font-semibold">Messages</h2></div><div className="mt-4 max-h-72 space-y-3 overflow-y-auto">{(data?.messages||[]).map((m:any)=><div key={m.id} className={`rounded-2xl p-3 text-sm ${m.sender_role==='buyer'?'mr-10 bg-slate-100':'ml-10 bg-blue-600 text-white'}`}>{m.body}</div>)}</div><form className="mt-4 flex gap-2" onSubmit={msg}><input className={inputClass} name="body" placeholder="Message buyer" required/><PrimaryButton>Send</PrimaryButton></form></Card>
  </div></div>}
 </div></div>
}
