import {FormEvent,useEffect,useState} from 'react';
import {ArrowLeft,CheckCircle2,FileUp,LockKeyhole,MessageSquare,WalletCards} from 'lucide-react';
import {Link,useParams} from 'react-router-dom';
import {Card,Field,Pill,PrimaryButton,SecondaryButton,inputClass} from '../../components/Primitives';
import {useBuyerPortalStore,type DealRoomSnapshot} from '../../store/BuyerPortalStore';
import {usePortfolioStore} from '../../store/PortfolioStore';
const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v||0);
export default function OwnerBuyerDealRoom(){const {id}=useParams();const {portfolios}=usePortfolioStore();const {buyers,loadRoom,offerAction,dealGate,closeDeal,uploadDocument,sendMessage}=useBuyerPortalStore();const [data,setData]=useState<DealRoomSnapshot|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const p=portfolios.find(x=>x.id===id);const reload=async()=>{if(id)setData(await loadRoom(id))};useEffect(()=>{reload().catch(e=>setMessage(e.message))},[id]);const run=async(fn:()=>Promise<unknown>,ok:string)=>{setBusy(true);try{await fn();await reload();setMessage(ok)}catch(e){setMessage(e instanceof Error?e.message:'Action failed')}finally{setBusy(false)}};if(!p)return <div className="p-8">Portfolio unavailable.</div>;const r=data?.room,o=data?.offer,b=buyers.find(x=>x.id===r?.buyer_id);
async function doc(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(()=>uploadDocument(r.id,String(f.get('type')),String(f.get('title')),String(f.get('url')),f.get('visible')==='on'),'Document added.');e.currentTarget.reset()}
async function msg(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(()=>sendMessage(r.buyer_id,p!.id,String(f.get('body')),o.id),'Message sent.');e.currentTarget.reset()}
return <div className="p-5 lg:p-8"><div className="mx-auto max-w-7xl"><Link to="/buyers" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft size={16}/>Buyer Portal</Link><div className="mt-5 flex justify-between gap-4"><div><p className="text-xs font-bold tracking-[.2em] text-blue-600">OWNER CLOSING CONTROL</p><h1 className="mt-2 text-3xl font-semibold">{p.name}</h1><p className="mt-2 text-sm text-slate-500">{b?.company_name||'Buyer'} · Current offer {money(o?.current_amount)}</p></div><Pill tone={r?.status==='closed'?'success':'blue'}>{r?.status?.replace(/_/g,' ')||'No active room'}</Pill></div>{message&&<p className="mt-5 rounded-2xl bg-blue-50 p-4 text-sm text-blue-700">{message}</p>}{!r?<Card className="mt-7 p-8 text-center text-slate-500">No active buyer deal room for this portfolio.</Card>:<div className="mt-7 grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><div className="space-y-6"><Card className="p-6"><h2 className="font-semibold">Closing gates</h2><div className="mt-5 grid gap-3 sm:grid-cols-3">{[['Agreement approved',r.agreement_approved_at],['Payment confirmed',r.payment_confirmed_at],['Final file released',r.final_file_released_at]].map(([x,v]:any)=><div key={x} className={`rounded-2xl p-4 ${v?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{v?<CheckCircle2/>:<LockKeyhole/>}<p className="mt-3 text-sm font-semibold">{x}</p></div>)}</div><div className="mt-5 flex flex-wrap gap-2"><PrimaryButton onClick={()=>run(()=>dealGate(r.id,'agreement'),'Agreement approved.')} disabled={busy||!!r.agreement_approved_at}>Approve Agreement</PrimaryButton><PrimaryButton onClick={()=>run(()=>dealGate(r.id,'payment'),'Payment confirmed.')} disabled={busy||!r.agreement_approved_at||!!r.payment_confirmed_at}>Confirm Payment</PrimaryButton><PrimaryButton onClick={()=>run(()=>dealGate(r.id,'release'),'Final file released.')} disabled={busy||!r.payment_confirmed_at||!!r.final_file_released_at}>Release Final File</PrimaryButton><PrimaryButton onClick={()=>run(()=>closeDeal(r.id),'Deal closed and financial records created.')} disabled={busy||!r.final_file_released_at||r.status==='closed'}>Close Deal</PrimaryButton></div></Card>
<Card className="p-6"><h2 className="font-semibold">Negotiation history</h2><div className="mt-4 space-y-3">{(data?.rounds||[]).map((x:any)=><div key={x.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex justify-between"><p className="font-semibold capitalize">{x.actor_role} · {x.action}</p><p className="font-semibold">{money(x.amount)}</p></div>{x.message&&<p className="mt-2 text-sm text-slate-600">{x.message}</p>}</div>)}</div>{o?.status!=='accepted'&&<div className="mt-4 flex gap-2"><PrimaryButton onClick={()=>run(()=>offerAction(o.id,'accept',undefined,'Seller accepted offer',new Date(Date.now()+72*3600000).toISOString()),'Offer accepted and reserved for 72 hours.')}>Accept & Reserve</PrimaryButton><SecondaryButton onClick={()=>run(()=>offerAction(o.id,'reject',undefined,'Seller rejected offer'),'Offer rejected.')}>Reject</SecondaryButton></div>}</Card>
<Card className="p-6"><div className="flex items-center gap-3"><MessageSquare className="text-blue-600"/><h2 className="font-semibold">Messages</h2></div><div className="mt-4 max-h-72 space-y-3 overflow-y-auto">{(data?.messages||[]).map((m:any)=><div key={m.id} className={`rounded-2xl p-3 text-sm ${m.sender_role==='buyer'?'mr-10 bg-slate-100':'ml-10 bg-blue-600 text-white'}`}>{m.body}</div>)}</div><form className="mt-4 flex gap-2" onSubmit={msg}><input className={inputClass} name="body" placeholder="Message buyer" required/><PrimaryButton>Send</PrimaryButton></form></Card></div>
<div className="space-y-6"><Card className="p-6"><FileUp className="text-blue-600"/><h2 className="mt-3 font-semibold">Add deal document</h2><form className="mt-4 space-y-4" onSubmit={doc}><Field label="Document type"><select className={inputClass} name="type"><option value="purchase_agreement">Purchase agreement</option><option value="payment_instructions">Payment instructions</option><option value="payment_proof">Payment proof</option><option value="final_portfolio">Final portfolio file</option><option value="other">Other</option></select></Field><Field label="Title"><input className={inputClass} name="title" required/></Field><Field label="Secure URL"><input className={inputClass} name="url" placeholder="Storage or signed URL"/></Field><label className="flex gap-3 text-sm"><input type="checkbox" name="visible"/>Visible to buyer immediately</label><PrimaryButton className="w-full">Add document</PrimaryButton></form></Card><Card className="p-6"><h2 className="font-semibold">Document checklist</h2><div className="mt-4 space-y-3">{(data?.documents||[]).map((d:any)=><div key={d.id} className="rounded-2xl bg-slate-50 p-4"><p className="font-semibold">{d.title}</p><p className="mt-1 text-xs capitalize text-slate-500">{d.document_type.replace(/_/g,' ')} · {d.status} · {d.visible_to_buyer?'Buyer visible':'Locked'}</p></div>)}</div></Card><Card className="p-6"><WalletCards className="text-blue-600"/><h2 className="mt-3 font-semibold">Automatic close result</h2><p className="mt-2 text-sm leading-6 text-slate-500">Closing marks the portfolio sold, creates the sale, records revenue, creates eligible employee commission, and preserves the audit trail.</p></Card></div></div>}</div></div>}
