import {useEffect,useMemo,useState} from 'react';
import {Activity,BarChart3,BadgeDollarSign,Clock3,RefreshCw,Target,TrendingUp,Trophy,Users,WalletCards} from 'lucide-react';
import {Card,SecondaryButton,Pill} from '../../components/Primitives';
import {supabase} from '../../lib/supabase';

type Summary={monthRevenue:number;monthProfit:number;monthSales:number;previousMonthRevenue:number;lifetimeRevenue:number;lifetimeProfit:number;pipelineValue:number;weightedPipeline:number;openDeals:number;winRate:number;averageSale:number;averageDaysToClose:number;profitMargin:number};
type Trend={month:string;monthStart:string;revenue:number;profit:number;sales:number};
type Stage={stage:string;count:number;value:number};
type Employee={employeeId:string;employeeName:string;sales:number;revenue:number;profit:number;commission:number;commissionPaid:number;averageDaysToClose:number};
type Portfolio={portfolioId:string;portfolioName:string;accountCount:number;salePrice:number;acquisitionCost:number;transactionCosts:number;profit:number;roi:number|null;closedAt:string};
type Analytics={summary:Summary;monthlyTrend:Trend[];stageFunnel:Stage[];employees:Employee[];portfolios:Portfolio[]};
const empty:Analytics={summary:{monthRevenue:0,monthProfit:0,monthSales:0,previousMonthRevenue:0,lifetimeRevenue:0,lifetimeProfit:0,pipelineValue:0,weightedPipeline:0,openDeals:0,winRate:0,averageSale:0,averageDaysToClose:0,profitMargin:0},monthlyTrend:[],stageFunnel:[],employees:[],portfolios:[]};
const money=(n=0)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)||0);
const stageName=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export default function PerformanceCommand(){
 const [data,setData]=useState<Analytics>(empty),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');const {data,error}=await supabase.rpc('dmh_owner_sales_analytics');if(error)setError(error.message);else setData((data||empty) as Analytics);setLoading(false)};
 useEffect(()=>{load()},[]);
 const change=useMemo(()=>{const a=Number(data.summary.monthRevenue||0),b=Number(data.summary.previousMonthRevenue||0);return b===0?(a>0?100:0):Math.round(((a-b)/b)*1000)/10},[data]);
 const maxTrend=Math.max(1,...data.monthlyTrend.map(x=>Number(x.revenue||0)));
 const maxStage=Math.max(1,...data.stageFunnel.map(x=>Number(x.count||0)));
 return <div className="mx-auto max-w-[1600px] p-5 md:p-8 lg:p-10">
  <header className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold text-blue-600">Owner Sales Analytics · v3.1.5</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Sales Intelligence</h1><p className="mt-2 text-slate-500">Revenue, profit, conversion, closing speed, employee production, and portfolio performance calculated from recorded activity.</p></div><SecondaryButton onClick={load} disabled={loading}><RefreshCw className={`mr-2 ${loading?'animate-spin':''}`} size={17}/>Refresh</SecondaryButton></header>
  {error&&<Card className="mt-6 border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}. Run migration 061.</Card>}
  <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={BadgeDollarSign} label="Revenue this month" value={money(data.summary.monthRevenue)} note={`${change>=0?'+':''}${change}% vs last month`}/><Metric icon={WalletCards} label="Profit this month" value={money(data.summary.monthProfit)} note={`${data.summary.profitMargin||0}% lifetime margin`}/><Metric icon={Target} label="Open pipeline" value={money(data.summary.pipelineValue)} note={`${money(data.summary.weightedPipeline)} weighted`}/><Metric icon={Trophy} label="Win rate" value={`${data.summary.winRate||0}%`} note={`${data.summary.openDeals||0} open deals`}/></section>
  <section className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Activity} label="Sales this month" value={String(data.summary.monthSales||0)} note={`${money(data.summary.averageSale)} average sale`}/><Metric icon={Clock3} label="Average close time" value={`${data.summary.averageDaysToClose||0} days`} note="Closed-won opportunities"/><Metric icon={TrendingUp} label="Lifetime revenue" value={money(data.summary.lifetimeRevenue)} note={`${money(data.summary.lifetimeProfit)} profit`}/><Metric icon={Users} label="Producing employees" value={String(data.employees.filter(x=>x.sales>0).length)} note={`${data.employees.length} employees tracked`}/></section>
  <div className="mt-7 grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><Card className="p-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">12-month revenue trend</h2><p className="mt-1 text-sm text-slate-500">Closed sales and realized profit.</p></div><BarChart3 className="text-blue-600"/></div><div className="mt-8 flex h-64 items-end gap-2 border-b border-slate-200">{data.monthlyTrend.map(x=><div key={x.monthStart} className="flex h-full min-w-0 flex-1 flex-col justify-end"><div className="group relative flex flex-1 items-end justify-center"><div className="w-full max-w-12 rounded-t-lg bg-blue-600 transition-opacity hover:opacity-80" style={{height:`${Math.max(3,Number(x.revenue||0)/maxTrend*100)}%`}}/><div className="pointer-events-none absolute bottom-full z-10 mb-2 hidden whitespace-nowrap rounded-xl bg-slate-900 px-3 py-2 text-xs text-white group-hover:block">{money(x.revenue)} revenue · {money(x.profit)} profit · {x.sales} sales</div></div><p className="mt-3 truncate text-center text-[10px] text-slate-500">{x.month.split(' ')[0]}</p></div>)}</div></Card>
  <Card className="p-6"><h2 className="text-xl font-semibold">Pipeline funnel</h2><p className="mt-1 text-sm text-slate-500">Live opportunities by recorded stage.</p><div className="mt-6 space-y-4">{data.stageFunnel.length===0?<p className="text-sm text-slate-500">No pipeline activity yet.</p>:data.stageFunnel.map(s=><div key={s.stage}><div className="flex items-center justify-between gap-3 text-sm"><span className="font-medium">{stageName(s.stage)}</span><span className="text-slate-500">{s.count} · {money(s.value)}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${Math.max(4,Number(s.count||0)/maxStage*100)}%`}}/></div></div>)}</div></Card></div>
  <Card className="mt-6 overflow-hidden"><div className="border-b border-slate-100 p-6"><h2 className="text-xl font-semibold">Employee production</h2><p className="mt-1 text-sm text-slate-500">Ranked by verified closed revenue—not manually entered status.</p></div><div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-left"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-4">Rank</th><th className="px-4 py-4">Employee</th><th className="px-4 py-4">Sales</th><th className="px-4 py-4">Revenue</th><th className="px-4 py-4">Profit</th><th className="px-4 py-4">Commission earned</th><th className="px-4 py-4">Commission paid</th><th className="px-4 py-4">Avg. close</th></tr></thead><tbody className="divide-y divide-slate-100">{data.employees.map((e,i)=><tr key={e.employeeId}><td className="px-6 py-5 font-semibold">#{i+1}</td><td className="px-4 py-5 font-semibold">{e.employeeName}</td><td className="px-4 py-5">{e.sales}</td><td className="px-4 py-5 font-semibold">{money(e.revenue)}</td><td className="px-4 py-5">{money(e.profit)}</td><td className="px-4 py-5">{money(e.commission)}</td><td className="px-4 py-5">{money(e.commissionPaid)}</td><td className="px-4 py-5">{Number(e.averageDaysToClose||0).toFixed(1)} days</td></tr>)}{!loading&&data.employees.length===0&&<tr><td colSpan={8} className="px-6 py-8 text-sm text-slate-500">No employee performance records yet.</td></tr>}</tbody></table></div></Card>
  <Card className="mt-6 overflow-hidden"><div className="border-b border-slate-100 p-6"><h2 className="text-xl font-semibold">Portfolio profitability</h2><p className="mt-1 text-sm text-slate-500">Sale economics after acquisition and transaction costs.</p></div><div className="overflow-x-auto"><table className="min-w-[1000px] w-full text-left"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-4">Portfolio</th><th className="px-4 py-4">Accounts</th><th className="px-4 py-4">Sale price</th><th className="px-4 py-4">Acquisition</th><th className="px-4 py-4">Fees</th><th className="px-4 py-4">Net profit</th><th className="px-4 py-4">ROI</th><th className="px-4 py-4">Closed</th></tr></thead><tbody className="divide-y divide-slate-100">{data.portfolios.map(p=><tr key={p.portfolioId}><td className="px-6 py-5 font-semibold">{p.portfolioName}</td><td className="px-4 py-5">{Number(p.accountCount||0).toLocaleString()}</td><td className="px-4 py-5">{money(p.salePrice)}</td><td className="px-4 py-5">{money(p.acquisitionCost)}</td><td className="px-4 py-5">{money(p.transactionCosts)}</td><td className="px-4 py-5 font-semibold">{money(p.profit)}</td><td className="px-4 py-5"><Pill tone={Number(p.roi||0)>=0?'success':'danger'}>{p.roi===null?'Not reconciled':`${p.roi}%`}</Pill></td><td className="px-4 py-5 text-sm text-slate-500">{p.closedAt?new Date(p.closedAt).toLocaleDateString():'—'}</td></tr>)}{!loading&&data.portfolios.length===0&&<tr><td colSpan={8} className="px-6 py-8 text-sm text-slate-500">No completed portfolio sales yet.</td></tr>}</tbody></table></div></Card>
 </div>
}
function Metric({icon:Icon,label,value,note}:{icon:any;label:string;value:string;note:string}){return <Card className="p-5"><Icon className="text-blue-600" size={19}/><p className="mt-4 text-3xl font-semibold">{value}</p><p className="mt-1 text-sm font-medium">{label}</p><p className="mt-1 text-xs text-slate-500">{note}</p></Card>}
