import type { FormEvent } from 'react';
import { useMemo, useState } from 'react';
import { CheckCircle2, Mail, Pause, Play, Plus, Send, Trash2, Users } from 'lucide-react';
import { Card, Pill, PrimaryButton, SecondaryButton, inputClass } from '../../components/Primitives';
import { usePortfolioStore } from '../../store/PortfolioStore';
import { useAgencyStore } from '../../store/AgencyStore';
import { useOutreachStore } from '../../store/OutreachStore';
import { useMatchingStore } from '../../store/MatchingStore';
import { type RecipientStatus, useCampaignStore } from '../../store/CampaignStore';

const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const vars=(text:string,data:Record<string,string|number>)=>Object.entries(data).reduce((out,[key,value])=>out.replaceAll(`{{${key}}}`,String(value)),text);
export default function PortfolioCampaigns(){
 const {portfolios}=usePortfolioStore();const {agencies}=useAgencyStore();const {templates}=useOutreachStore();const {matches,employees}=useMatchingStore();const {campaigns,recipients,events,loading,error,createCampaign,setCampaignStatus,addRecipient,removeRecipient,assignRecipient,updateRecipientStatus,sendRecipient}=useCampaignStore();
 const [selectedId,setSelectedId]=useState(campaigns[0]?.id||'');const selected=campaigns.find(c=>c.id===selectedId)||campaigns[0];const [creating,setCreating]=useState(false);const [message,setMessage]=useState('');
 const rows=selected?recipients.filter(r=>r.campaignId===selected.id):[];const portfolio=selected?portfolios.find(p=>p.id===selected.portfolioId):undefined;
 const counts=useMemo(()=>({selected:rows.filter(r=>['selected','assigned','queued'].includes(r.status)).length,sent:rows.filter(r=>['sent','delivered','opened','replied','interested','negotiating','purchased'].includes(r.status)).length,delivered:rows.filter(r=>['delivered','opened','replied','interested','negotiating','purchased'].includes(r.status)).length,replies:rows.filter(r=>['replied','interested','negotiating','purchased'].includes(r.status)).length,interested:rows.filter(r=>['interested','negotiating','purchased'].includes(r.status)).length,negotiating:rows.filter(r=>['negotiating','purchased'].includes(r.status)).length,purchased:rows.filter(r=>r.status==='purchased').length}),[rows]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const template=templates.find(t=>t.id===String(f.get('templateId')));try{const id=await createCampaign({portfolioId:String(f.get('portfolioId')),name:String(f.get('name')),templateId:template?.id,subject:String(f.get('subject')||template?.subject||''),body:String(f.get('body')||template?.body||''),maxRecipients:Number(f.get('maxRecipients')||50)});setSelectedId(id);setCreating(false);setMessage('Campaign created. Add matched buyers, then approve it.');}catch(err){setMessage(err instanceof Error?err.message:'Unable to create campaign.')}}
 async function addMatched(agencyId:string){if(!selected||!portfolio)return;const agency=agencies.find(a=>a.id===agencyId);const match=matches.find(m=>m.portfolioId===portfolio.id&&m.agencyId===agencyId);if(!agency||!match)return;const contact=agency.contacts.find(c=>c.decisionMaker&&c.email)||agency.contacts.find(c=>c.email);const email=contact?.email||agency.generalEmail;const name=contact?[contact.firstName,contact.lastName].filter(Boolean).join(' '):agency.name;const data={agency_name:agency.name,contact_name:name,portfolio_name:portfolio.name,account_count:portfolio.accountCount,asking_price:money.format(portfolio.askingPrice),employee_name:'Data Market House'};try{await addRecipient({campaignId:selected.id,portfolioId:portfolio.id,agencyId,contactId:contact?.id,assignedEmployeeId:match.assignedEmployeeId,matchScore:match.score,recipientEmail:email,recipientName:name,personalizedSubject:vars(selected.subject,data),personalizedBody:vars(selected.body,data)});setMessage(`${agency.name} added.`)}catch(err){setMessage(err instanceof Error?err.message:'Unable to add buyer.')}}
 const candidateMatches=selected?matches.filter(m=>m.portfolioId===selected.portfolioId&&!rows.some(r=>r.agencyId===m.agencyId)).sort((a,b)=>b.score-a.score):[];
 return <div className="mx-auto max-w-[1500px] p-5 md:p-8 lg:p-10"><header className="mb-7 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold text-blue-600">Controlled portfolio distribution</p><h2 className="mt-1 text-3xl font-semibold">Portfolio campaigns</h2><p className="mt-2 text-slate-500">Turn buyer matches into approved, assigned, duplicate-safe outreach.</p></div><PrimaryButton onClick={()=>setCreating(true)}><Plus className="mr-2" size={17}/>New campaign</PrimaryButton></header>{error&&<Card className="mb-5 border-red-200 p-4 text-red-700">{error}</Card>}{message&&<Card className="mb-5 p-4 text-sm text-slate-600">{message}</Card>}{creating&&<Card className="mb-6 p-6"><form onSubmit={create} className="grid gap-4 md:grid-cols-2"><input className={inputClass} name="name" placeholder="Campaign name" required/><select className={inputClass} name="portfolioId" required><option value="">Select portfolio</option>{portfolios.filter(p=>p.status!=='sold').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select className={inputClass} name="templateId"><option value="">Select approved template</option>{templates.filter(t=>t.active).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><input className={inputClass} type="number" min="1" max="500" name="maxRecipients" defaultValue="50"/><input className={`${inputClass} md:col-span-2`} name="subject" placeholder="Optional subject override"/><textarea className={`${inputClass} min-h-36 md:col-span-2`} name="body" placeholder="Optional message override"/><div className="flex gap-3 md:col-span-2"><PrimaryButton>Create campaign</PrimaryButton><SecondaryButton type="button" onClick={()=>setCreating(false)}>Cancel</SecondaryButton></div></form></Card>}
 <div className="grid gap-6 xl:grid-cols-[330px_1fr]"><Card className="h-fit p-4"><p className="px-2 pb-3 text-xs font-semibold uppercase tracking-[.18em] text-slate-400">Campaigns</p><div className="space-y-2">{campaigns.map(c=>{const p=portfolios.find(x=>x.id===c.portfolioId);return <button key={c.id} onClick={()=>setSelectedId(c.id)} className={`w-full rounded-2xl p-4 text-left ${selected?.id===c.id?'bg-slate-900 text-white':'bg-slate-50 hover:bg-slate-100'}`}><div className="flex items-center justify-between gap-2"><p className="font-semibold">{c.name}</p><Pill tone={c.status==='active'?'success':c.status==='paused'?'warning':'neutral'}>{c.status}</Pill></div><p className={`mt-1 text-xs ${selected?.id===c.id?'text-slate-400':'text-slate-500'}`}>{p?.name||'Portfolio'} · {recipients.filter(r=>r.campaignId===c.id).length}/{c.maxRecipients}</p></button>})}{!campaigns.length&&!loading&&<p className="p-5 text-center text-sm text-slate-400">No campaigns yet.</p>}</div></Card>
 {selected&&portfolio?<div className="space-y-6"><Card className="p-6 md:p-8"><div className="flex flex-col gap-5 md:flex-row md:items-start md:justify-between"><div><div className="flex flex-wrap items-center gap-3"><h3 className="text-2xl font-semibold">{selected.name}</h3><Pill tone={selected.status==='active'?'success':selected.status==='paused'?'warning':'blue'}>{selected.status}</Pill></div><p className="mt-2 text-slate-500">{portfolio.name} · {portfolio.accountCount.toLocaleString()} accounts · {money.format(portfolio.askingPrice)}</p></div><div className="flex flex-wrap gap-2">{selected.status==='draft'&&<PrimaryButton onClick={()=>void setCampaignStatus(selected.id,'ready')}>Approve campaign</PrimaryButton>}{selected.status==='ready'&&<PrimaryButton onClick={()=>void setCampaignStatus(selected.id,'active')}><Play className="mr-2" size={16}/>Launch</PrimaryButton>}{selected.status==='active'&&<SecondaryButton onClick={()=>void setCampaignStatus(selected.id,'paused')}><Pause className="mr-2" size={16}/>Pause</SecondaryButton>}{selected.status==='paused'&&<PrimaryButton onClick={()=>void setCampaignStatus(selected.id,'active')}><Play className="mr-2" size={16}/>Resume</PrimaryButton>}{!['completed','cancelled'].includes(selected.status)&&<SecondaryButton onClick={()=>void setCampaignStatus(selected.id,'completed')}><CheckCircle2 className="mr-2" size={16}/>Complete</SecondaryButton>}</div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-7">{Object.entries(counts).map(([k,v])=><div key={k} className="rounded-2xl bg-slate-50 p-4"><p className="text-xs capitalize text-slate-500">{k}</p><p className="mt-1 text-2xl font-semibold">{v}</p></div>)}</div></Card>
 <div className="grid gap-6 2xl:grid-cols-[1fr_390px]"><Card className="overflow-hidden"><div className="border-b border-slate-100 p-5"><h3 className="text-lg font-semibold">Campaign recipients</h3><p className="mt-1 text-sm text-slate-500">Employees can only work recipients assigned to them.</p></div><div className="divide-y divide-slate-100">{rows.map(r=>{const agency=agencies.find(a=>a.id===r.agencyId);return <div key={r.id} className="grid gap-3 p-5 xl:grid-cols-[1fr_170px_170px_auto]"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{agency?.name||r.recipientName}</p><Pill tone={r.status==='purchased'?'success':r.status==='failed'||r.status==='declined'?'danger':r.status==='interested'||r.status==='negotiating'?'warning':'blue'}>{r.status}</Pill><span className="text-xs font-semibold text-slate-400">{r.matchScore}% match</span></div><p className="mt-1 text-sm text-slate-500">{r.recipientEmail||'Missing email'}</p></div><select className={inputClass} value={r.assignedEmployeeId||''} onChange={e=>void assignRecipient(r.id,e.target.value)}><option value="">Unassigned</option>{employees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className={inputClass} value={r.status} onChange={e=>void updateRecipientStatus(r.id,e.target.value as RecipientStatus)}>{['selected','assigned','sent','delivered','opened','replied','interested','declined','negotiating','purchased','failed','suppressed'].map(s=><option key={s}>{s}</option>)}</select><div className="flex gap-2"><PrimaryButton disabled={selected.status!=='active'||!r.recipientEmail||['sent','delivered','opened','replied','interested','negotiating','purchased'].includes(r.status)} onClick={()=>void sendRecipient(r.id)}><Send size={16}/></PrimaryButton><SecondaryButton disabled={!['selected','assigned'].includes(r.status)} onClick={()=>void removeRecipient(r.id)}><Trash2 size={16}/></SecondaryButton></div></div>})}{!rows.length&&<p className="p-10 text-center text-slate-400">Add matched buyers to begin.</p>}</div></Card>
 <div className="space-y-6"><Card className="p-5"><div className="flex items-center gap-3"><Users className="text-blue-600"/><div><h3 className="font-semibold">Best matched buyers</h3><p className="text-xs text-slate-500">Highest fit first</p></div></div><div className="mt-4 space-y-3">{candidateMatches.slice(0,12).map(m=>{const a=agencies.find(x=>x.id===m.agencyId);return <div key={m.agencyId} className="rounded-2xl bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{a?.name||'Agency'}</p><p className="mt-1 text-xs text-slate-500">{m.score}% · {m.reasons.slice(0,2).join(' · ')}</p></div><button onClick={()=>void addMatched(m.agencyId)} className="rounded-xl bg-slate-900 px-3 py-2 text-xs font-semibold text-white">Add</button></div></div>})}{!candidateMatches.length&&<p className="py-8 text-center text-sm text-slate-400">No additional matches.</p>}</div></Card><Card className="p-5"><div className="flex items-center gap-3"><Mail className="text-blue-600"/><h3 className="font-semibold">Recent campaign events</h3></div><div className="mt-4 space-y-3">{events.filter(e=>e.campaignId===selected.id).slice(0,8).map(e=><div key={e.id} className="border-l-2 border-slate-200 pl-3"><p className="text-sm font-medium">{e.detail||e.eventType}</p><p className="mt-1 text-xs text-slate-400">{new Date(e.createdAt).toLocaleString()}</p></div>)}</div></Card></div></div></div>:<Card className="grid min-h-80 place-items-center p-8 text-slate-400">Select or create a campaign.</Card>}</div></div>;
}
