import { ArrowLeft, Check, Download, FileKey2, FileSpreadsheet, Pencil, Play, RotateCcw, Save, ShieldCheck, Trash2, Upload } from 'lucide-react';
import { useState, type FormEvent, type ReactNode } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Card, Field, Pill, PrimaryButton, SecondaryButton, inputClass } from '../../components/Primitives';
import { usePortfolioStore } from '../../store/PortfolioStore';
import type { PortfolioStatus } from '../../types/domain';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
export default function PortfolioDetail(){
 const {id}=useParams();const nav=useNavigate();const {portfolios,transition,removePortfolio,getDownloadUrl,updatePortfolio,uploadMaskedFile,uploadUnmaskedFile}=usePortfolioStore();const p=portfolios.find(x=>x.id===id);const [notice,setNotice]=useState('');const [error,setError]=useState('');const [editing,setEditing]=useState(false);const [saving,setSaving]=useState(false);const [uploading,setUploading]=useState<'masked'|'unmasked'|''>('');
 if(!p)return <div className="p-10">Portfolio not found.</div>;const portfolio=p;
 async function move(status:PortfolioStatus){const r=await transition(portfolio.id,status);setNotice(r.message)}
 async function download(){const url=await getDownloadUrl(portfolio.id);if(url)window.open(url,'_blank','noopener,noreferrer')}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError('');const f=new FormData(e.currentTarget);try{await updatePortfolio(p.id,{name:String(f.get('name')),originalCreditor:String(f.get('creditor')),category:String(f.get('category')),accountCount:Number(f.get('accounts')),faceValue:Number(f.get('faceValue')),askingPrice:Number(f.get('asking')),privateMinimum:Number(f.get('minimum')),acquisitionCost:Number(f.get('cost')),description:String(f.get('description')),sellingPoints:String(f.get('sellingPoints')).split('\n').map(x=>x.trim()).filter(Boolean)});setNotice('Portfolio changes saved.');setEditing(false)}catch(e){setError(e instanceof Error?e.message:'Unable to save portfolio.')}finally{setSaving(false)}}
 async function upload(kind:'masked'|'unmasked',file:File|null){if(!file)return;setUploading(kind);setError('');try{if(kind==='masked')await uploadMaskedFile(p.id,file);else await uploadUnmaskedFile(p.id,file);setNotice(`${kind==='masked'?'Masked':'Unmasked'} file uploaded successfully.`)}catch(e){setError(e instanceof Error?e.message:'File upload failed.')}finally{setUploading('')}}
 async function remove(){if(!window.confirm(`Delete ${p.name}? This cannot be undone.`))return;setError('');try{await removePortfolio(p.id);nav('/portfolios')}catch(e){setError(e instanceof Error?e.message:'Unable to delete portfolio.')}}
 return <div className="mx-auto max-w-[1350px] p-5 md:p-8 lg:p-10"><Link to="/portfolios" className="mb-6 inline-flex items-center text-sm font-semibold text-slate-500"><ArrowLeft className="mr-2" size={17}/>Portfolio queue</Link>
 <header className="mb-8 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><div className="flex items-center gap-3"><Pill tone={p.status==='active'?'success':p.status==='ready'?'blue':'neutral'}>{p.status}</Pill><span className="text-sm text-slate-400">{p.category}</span></div><h2 className="mt-3 text-3xl font-semibold">{p.name}</h2><p className="mt-2 text-slate-500">{p.originalCreditor} · {p.accountCount.toLocaleString()} accounts</p></div><div className="flex flex-wrap gap-3"><SecondaryButton onClick={()=>setEditing(x=>!x)}><Pencil className="mr-2" size={17}/>{editing?'Close editor':'Edit portfolio'}</SecondaryButton>{p.status==='draft'&&<PrimaryButton onClick={()=>move('ready')}><Check className="mr-2" size={18}/>Mark Ready</PrimaryButton>}{p.status==='ready'&&<PrimaryButton onClick={()=>move('active')}><Play className="mr-2" size={18}/>Activate campaign</PrimaryButton>}{p.status==='active'&&<SecondaryButton onClick={()=>move('archived')}>Withdraw campaign</SecondaryButton>}{p.status==='archived'&&<SecondaryButton disabled><RotateCcw className="mr-2" size={17}/>Archived</SecondaryButton>}</div></header>
 {notice&&<div className="mb-6 rounded-2xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{notice}</div>}{error&&<div className="mb-6 rounded-2xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}
 {editing&&<Card className="mb-6 p-6 md:p-8"><h3 className="text-xl font-semibold">Edit portfolio</h3><form onSubmit={save} className="mt-6 space-y-5"><div className="grid gap-5 md:grid-cols-2"><Field label="Portfolio name"><input className={inputClass} name="name" defaultValue={p.name} required/></Field><Field label="Original creditor"><input className={inputClass} name="creditor" defaultValue={p.originalCreditor} required/></Field><Field label="Category"><input className={inputClass} name="category" defaultValue={p.category} required/></Field><Field label="Account count"><input className={inputClass} name="accounts" type="number" min="1" defaultValue={p.accountCount} required/></Field><Field label="Face value"><input className={inputClass} name="faceValue" type="number" min="0" step=".01" defaultValue={p.faceValue} required/></Field><Field label="Asking price"><input className={inputClass} name="asking" type="number" min="0" step=".01" defaultValue={p.askingPrice} required/></Field><Field label="Private minimum"><input className={inputClass} name="minimum" type="number" min="0" step=".01" defaultValue={p.privateMinimum} required/></Field><Field label="Acquisition cost"><input className={inputClass} name="cost" type="number" min="0" step=".01" defaultValue={p.acquisitionCost} required/></Field></div><Field label="Description"><textarea className={`${inputClass} min-h-28`} name="description" defaultValue={p.description} required/></Field><Field label="Selling points"><textarea className={`${inputClass} min-h-28`} name="sellingPoints" defaultValue={p.sellingPoints.join('\n')} required/></Field><div className="flex justify-end"><PrimaryButton disabled={saving}><Save className="mr-2" size={17}/>{saving?'Saving…':'Save changes'}</PrimaryButton></div></form></Card>}
 <div className="grid gap-6 xl:grid-cols-[1.45fr_.75fr]"><div className="space-y-6"><Card className="p-6 md:p-8"><h3 className="text-xl font-semibold">Approved sales package</h3><p className="mt-4 leading-7 text-slate-600">{p.description}</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{p.sellingPoints.map(x=><div key={x} className="flex gap-3 rounded-2xl bg-slate-50 p-4"><Check className="mt-0.5 text-emerald-600" size={18}/><span className="text-sm font-medium">{x}</span></div>)}</div></Card>
 <FileCard title="Masked portfolio file" icon={<FileSpreadsheet/>} fileName={p.file?.name} meta={p.file?`${Math.ceil(p.file.size/1024)} KB · ${new Date(p.file.uploadedAt).toLocaleDateString()}`:'No masked file uploaded'} accept=".csv,.xlsx,.xls" onUpload={f=>upload('masked',f)} loading={uploading==='masked'} action={p.file?<SecondaryButton onClick={download}><Download className="mr-2" size={17}/>Test download</SecondaryButton>:undefined}/>
 <FileCard title="Private unmasked portfolio file" icon={<FileKey2/>} fileName={p.unmaskedFile?.name} meta={p.unmaskedFile?`${Math.ceil(p.unmaskedFile.size/1024)} KB · owner-only vault`:'Not uploaded yet. Add it now or later.'} accept=".csv,.xlsx,.xls,.zip" onUpload={f=>upload('unmasked',f)} loading={uploading==='unmasked'}/></div>
 <div className="space-y-6"><Card className="overflow-hidden"><div className="border-b border-slate-100 p-6"><div className="flex items-center gap-3"><ShieldCheck className="text-blue-600"/><div><p className="font-semibold">Owner-only economics</p><p className="text-xs text-slate-400">Hidden from employees</p></div></div></div><OwnerMetric label="Asking price" value={money(p.askingPrice)}/><OwnerMetric label="Private minimum" value={money(p.privateMinimum)}/><OwnerMetric label="Acquisition cost" value={money(p.acquisitionCost)}/><OwnerMetric label="Potential gross profit" value={money(p.askingPrice-p.acquisitionCost)}/></Card><Card className="p-6"><p className="text-sm font-semibold text-red-700">Danger zone</p><p className="mt-2 text-sm text-slate-500">Deletion is blocked automatically when an active buyer deal exists.</p><SecondaryButton className="mt-5 w-full text-red-700" onClick={remove}><Trash2 className="mr-2" size={17}/>Delete portfolio</SecondaryButton></Card></div></div></div>}
function FileCard({title,icon,fileName,meta,accept,onUpload,loading,action}:{title:string;icon:ReactNode;fileName?:string;meta:string;accept:string;onUpload:(file:File|null)=>void;loading:boolean;action?:ReactNode}){return <Card className="p-6 md:p-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-blue-50 text-blue-700">{icon}</div><div className="flex-1"><p className="font-semibold">{title}</p><p className="mt-1 text-sm text-slate-500">{fileName||meta}</p>{fileName&&<p className="mt-1 text-xs text-slate-400">{meta}</p>}</div>{action}<label className="inline-flex min-h-11 cursor-pointer items-center justify-center rounded-2xl border border-slate-200 px-5 py-3 text-sm font-semibold hover:bg-slate-50"><Upload className="mr-2" size={17}/>{loading?'Uploading…':fileName?'Replace':'Upload'}<input className="hidden" type="file" accept={accept} disabled={loading} onChange={e=>onUpload(e.target.files?.[0]||null)}/></label></div></Card>}
function OwnerMetric({label,value}:{label:string;value:string}){return <div className="border-b border-slate-100 p-6 last:border-0"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>}
