import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,BadgeDollarSign,CheckCircle2,RefreshCw,Save,Users,WalletCards} from 'lucide-react';
import {Card,PrimaryButton,SecondaryButton,inputClass,Pill} from '../../components/Primitives';
import {supabase} from '../../lib/supabase';

type Rule={employee_id:string;employee_name:string;rule_type:string|null;rule_value:number|null;is_active:boolean;updated_at?:string};
type Commission={commission_id:string;employee_id:string;employee_name:string;portfolio_name:string;sale_price:number;account_count:number;amount:number;status:string;rule_type?:string;rule_value?:number;locked_at?:string;paid_at?:string;payment_method?:string;payment_reference?:string;dispute_reason?:string;created_at:string};
const money=(n=0)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0);
const ruleLabel=(r?:string,v?:number)=>r==='percent_sale'?`${v||0}% of sale`:r==='per_account'?`${money(v||0)} per account`:r==='flat'?`${money(v||0)} flat`:'Not configured';
export default function RevenueCommand(){
 const [rules,setRules]=useState<Rule[]>([]),[ledger,setLedger]=useState<Commission[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 const load=async()=>{setLoading(true);setError('');const [a,b]=await Promise.all([supabase.rpc('dmh_owner_commission_rules'),supabase.rpc('dmh_owner_commission_ledger')]);if(a.error||b.error)setError(a.error?.message||b.error?.message||'Unable to load commissions');else{setRules((a.data||[]) as Rule[]);setLedger((b.data||[]) as Commission[])}setLoading(false)};
 useEffect(()=>{load()},[]);
 const totals=useMemo(()=>({pending:ledger.filter(x=>['pending','earned','approved'].includes(x.status)).reduce((s,x)=>s+Number(x.amount||0),0),paid:ledger.filter(x=>x.status==='paid').reduce((s,x)=>s+Number(x.amount||0),0),disputed:ledger.filter(x=>x.status==='disputed').length}),[ledger]);
 const saveRule=async(employeeId:string,type:string,value:number)=>{setMessage('');const {error}=await supabase.rpc('dmh_owner_set_employee_commission_rule',{p_employee_id:employeeId,p_rule_type:type,p_rule_value:value});if(error)setError(error.message);else{setMessage('Commission rule saved. Future commissions will use this rule.');await load()}};
 const pay=async(id:string)=>{const method=window.prompt('Payment method (ACH, Wire, Check, Cash, Other):','ACH');if(!method)return;const ref=window.prompt('Payment reference number (optional):','')||'';const {error}=await supabase.rpc('dmh_owner_mark_commission_paid_v2',{p_commission_id:id,p_payment_method:method,p_payment_reference:ref,p_notes:null});if(error)setError(error.message);else{setMessage('Commission marked paid with a permanent payout record.');await load()}};
 const resolve=async(id:string)=>{const text=window.prompt('Enter the resolution visible to the employee:');if(!text)return;const {error}=await supabase.rpc('dmh_owner_resolve_commission_dispute',{p_commission_id:id,p_resolution:text,p_restore_status:'earned'});if(error)setError(error.message);else{setMessage('Dispute resolved and recorded.');await load()}};
 return <div className="mx-auto max-w-[1500px] p-5 md:p-8 lg:p-10"><header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold text-blue-600">Commission Rules & Payout Ledger · v3.1.4</p><h1 className="mt-1 text-3xl font-semibold">Commission Command</h1><p className="mt-2 text-slate-500">Set transparent rules, protect earned amounts, and record every employee payout.</p></div><SecondaryButton onClick={load}><RefreshCw className="mr-2" size={17}/>Refresh</SecondaryButton></header>
 {error&&<Card className="mt-5 border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</Card>}{message&&<Card className="mt-5 border-blue-200 bg-blue-50 p-4 text-sm text-blue-800">{message}</Card>}
 <section className="mt-7 grid gap-4 sm:grid-cols-3"><Metric icon={WalletCards} label="Awaiting payout" value={money(totals.pending)}/><Metric icon={CheckCircle2} label="Paid commissions" value={money(totals.paid)}/><Metric icon={AlertTriangle} label="Open disputes" value={String(totals.disputed)}/></section>
 <div className="mt-7 grid gap-6 xl:grid-cols-[.85fr_1.4fr]"><Card className="p-6"><h2 className="text-xl font-semibold">Employee commission rules</h2><p className="mt-1 text-sm text-slate-500">The active rule is visible to each employee.</p><div className="mt-5 space-y-4">{rules.map(r=><RuleEditor key={r.employee_id} rule={r} onSave={saveRule}/>)}</div></Card>
 <Card className="overflow-hidden"><div className="border-b border-slate-100 p-6"><h2 className="text-xl font-semibold">Payout ledger</h2><p className="mt-1 text-sm text-slate-500">Earned amounts lock when buyer payment is verified.</p></div><div className="divide-y divide-slate-100">{loading?<p className="p-6 text-slate-500">Loading ledger…</p>:ledger.length===0?<p className="p-6 text-slate-500">No commissions yet.</p>:ledger.map(c=><div key={c.commission_id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-semibold">{c.employee_name} · {c.portfolio_name}</p><p className="mt-1 text-sm text-slate-500">Sale {money(c.sale_price)} · {ruleLabel(c.rule_type,c.rule_value)}</p><p className="mt-1 text-xs text-slate-400">{c.locked_at?'Amount locked after verified buyer payment':'Not earned yet'}</p></div><div className="text-right"><p className="text-xl font-semibold">{money(c.amount)}</p><Pill tone={c.status==='paid'?'success':c.status==='disputed'?'danger':c.status==='earned'||c.status==='approved'?'warning':'blue'}>{c.status}</Pill></div></div>{c.dispute_reason&&<div className="mt-4 rounded-2xl bg-red-50 p-4 text-sm text-red-800"><strong>Employee dispute:</strong> {c.dispute_reason}</div>}<div className="mt-4 flex flex-wrap gap-2">{['earned','approved'].includes(c.status)&&<PrimaryButton onClick={()=>pay(c.commission_id)}>Mark paid</PrimaryButton>}{c.status==='disputed'&&<SecondaryButton onClick={()=>resolve(c.commission_id)}>Resolve dispute</SecondaryButton>}{c.status==='paid'&&<span className="text-sm text-slate-500">Paid {c.paid_at?new Date(c.paid_at).toLocaleString():''} · {c.payment_method||'method not recorded'} {c.payment_reference?`· ${c.payment_reference}`:''}</span>}</div></div>)}</div></Card></div></div>}
function Metric({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <Card className="p-5"><Icon className="text-blue-600" size={19}/><p className="mt-4 text-3xl font-semibold">{value}</p><p className="text-sm text-slate-500">{label}</p></Card>}
function RuleEditor({rule,onSave}:{rule:Rule;onSave:(id:string,type:string,value:number)=>Promise<void>}){const [type,setType]=useState(rule.rule_type||'percent_sale'),[value,setValue]=useState(String(rule.rule_value??10)),[busy,setBusy]=useState(false);return <div className="rounded-2xl border border-slate-200 p-4"><p className="font-semibold">{rule.employee_name}</p><p className="mt-1 text-xs text-slate-500">Current: {ruleLabel(rule.rule_type||undefined,Number(rule.rule_value||0))}</p><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_110px_auto]"><select className={inputClass} value={type} onChange={e=>setType(e.target.value)}><option value="percent_sale">Percent of sale</option><option value="flat">Flat amount</option><option value="per_account">Amount per account</option></select><input className={inputClass} type="number" min="0" step="0.01" value={value} onChange={e=>setValue(e.target.value)}/><SecondaryButton disabled={busy} onClick={async()=>{setBusy(true);await onSave(rule.employee_id,type,Number(value||0));setBusy(false)}}><Save size={16}/></SecondaryButton></div></div>}
