import {useEffect,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {AlertTriangle,BellRing,Clock3,CreditCard,FileSignature,Play,RefreshCw,ShieldCheck} from 'lucide-react';
import {Card,Field,Pill,PrimaryButton,SecondaryButton,inputClass} from '../../components/Primitives';
import {useTransactionAutomation,type AutomationSettings} from '../../store/TransactionAutomationStore';
const defaults:AutomationSettings={nda_reminder_hours:24,agreement_reminder_hours:24,reservation_warning_hours:48,payment_warning_days:3,owner_escalation_enabled:true,buyer_alerts_enabled:true,employee_alerts_enabled:true};
export default function TransactionAutomationCommand(){const {alerts,metrics,loading,error,run,markRead,markAllRead,saveSettings}=useTransactionAutomation();const nav=useNavigate();const [settings,setSettings]=useState(defaults);const [message,setMessage]=useState('');const [running,setRunning]=useState(false);useEffect(()=>{if(metrics?.settings)setSettings(metrics.settings)},[metrics]);
 async function execute(){setRunning(true);setMessage('');try{const n=await run();setMessage(`Automation completed. ${n} alert actions processed.`)}catch(e){setMessage(e instanceof Error?e.message:'Automation failed')}finally{setRunning(false)}}
 async function save(){try{await saveSettings(settings);setMessage('Automation settings saved.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to save settings')}}
 const cards=[['NDAs waiting',metrics?.nda_waiting||0,FileSignature],['Agreements waiting',metrics?.agreements_waiting||0,Clock3],['Payments due',metrics?.payments_due||0,CreditCard],['Overdue',metrics?.payments_overdue||0,AlertTriangle],['Reservations expiring',metrics?.reservations_expiring||0,Clock3],['Release ready',metrics?.final_release_ready||0,ShieldCheck]] as const;
 return <div className="p-5 lg:p-8"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold tracking-[.2em] text-blue-600">TRANSACTION CONTROL</p><h1 className="mt-2 text-3xl font-semibold">Automation Command Center</h1><p className="mt-2 text-sm text-slate-500">One queue for signatures, reservations, payments and final release.</p></div><div className="flex gap-2"><SecondaryButton onClick={()=>void markAllRead()}>Mark all read</SecondaryButton><PrimaryButton onClick={execute} disabled={running}><Play size={16} className="mr-2"/>{running?'Running…':'Run engine now'}</PrimaryButton></div></div>
 {(error||message)&&<div className={`mt-5 rounded-2xl p-4 text-sm ${error?'bg-red-50 text-red-700':'bg-blue-50 text-blue-700'}`}>{error||message}</div>}
 <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{cards.map(([label,value,Icon])=><Card key={label} className="p-5"><Icon size={20} className={label==='Overdue'&&value?'text-red-600':'text-blue-600'}/><p className="mt-4 text-3xl font-semibold">{value}</p><p className="mt-1 text-sm text-slate-500">{label}</p></Card>)}</div>
 <div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-semibold">Live transaction queue</h2><p className="mt-1 text-sm text-slate-500">Unread owner alerts and escalations.</p></div><Pill tone={metrics?.unread_alerts?'warning':'success'}>{metrics?.unread_alerts||0} unread</Pill></div><div className="divide-y divide-slate-100">{loading?<p className="p-6 text-sm text-slate-500">Refreshing transaction intelligence…</p>:alerts.length===0?<div className="p-8 text-center"><BellRing className="mx-auto text-slate-300"/><p className="mt-3 font-semibold">Queue is clear</p><p className="mt-1 text-sm text-slate-500">Run the engine to evaluate active transactions.</p></div>:alerts.map(a=><button key={a.id} onClick={()=>{void markRead(a.id);if(a.action_path)nav(a.action_path)}} className={`block w-full p-5 text-left transition hover:bg-slate-50 ${a.read_at?'opacity-60':''}`}><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><p className="font-semibold">{a.title}</p><Pill tone={a.severity==='critical'?'danger':a.severity==='warning'?'warning':a.severity==='success'?'success':'blue'}>{a.severity}</Pill></div><p className="mt-1 text-sm text-slate-500">{a.body}</p><p className="mt-2 text-xs text-slate-400">{new Date(a.created_at).toLocaleString()}{a.due_at?` · Due ${new Date(a.due_at).toLocaleString()}`:''}</p></div>{!a.read_at&&<span className="mt-1 h-2.5 w-2.5 rounded-full bg-blue-600"/>}</div></button>)}</div></Card>
 <Card className="p-6"><div className="flex items-center gap-2"><RefreshCw size={19} className="text-blue-600"/><h2 className="font-semibold">Alert timing</h2></div><p className="mt-1 text-sm text-slate-500">Control when the engine begins escalation.</p><div className="mt-5 space-y-4"><Field label="NDA unsigned reminder (hours)"><input className={inputClass} type="number" min="1" value={settings.nda_reminder_hours} onChange={e=>setSettings({...settings,nda_reminder_hours:Number(e.target.value)})}/></Field><Field label="Agreement unsigned reminder (hours)"><input className={inputClass} type="number" min="1" value={settings.agreement_reminder_hours} onChange={e=>setSettings({...settings,agreement_reminder_hours:Number(e.target.value)})}/></Field><Field label="Reservation warning (hours)"><input className={inputClass} type="number" min="1" value={settings.reservation_warning_hours} onChange={e=>setSettings({...settings,reservation_warning_hours:Number(e.target.value)})}/></Field><Field label="Payment warning (days)"><input className={inputClass} type="number" min="1" value={settings.payment_warning_days} onChange={e=>setSettings({...settings,payment_warning_days:Number(e.target.value)})}/></Field>{[['Owner escalation', 'owner_escalation_enabled'],['Buyer alerts','buyer_alerts_enabled'],['Employee alerts','employee_alerts_enabled']].map(([label,key])=><label key={key} className="flex items-center justify-between rounded-2xl border border-slate-200 p-4 text-sm font-medium"><span>{label}</span><input type="checkbox" checked={Boolean(settings[key as keyof AutomationSettings])} onChange={e=>setSettings({...settings,[key]:e.target.checked})}/></label>)}<PrimaryButton className="w-full" onClick={save}>Save automation settings</PrimaryButton></div></Card></div></div></div>
}
