import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import { supabase } from '../lib/supabase';
import { usePortfolioStore } from './PortfolioStore';

export type AgencyStatus='new'|'researching'|'contacted'|'qualified'|'portfolio_sent'|'negotiating'|'offer_submitted'|'closed'|'not_interested'|'do_not_contact';
export type ActivityType='call'|'email'|'note'|'follow_up';
export type ActivityDisposition='No answer'|'Left voicemail'|'Reached receptionist'|'Reached decision-maker'|'Requested information'|'Call back later'|'Wrong number'|'Email drafted'|'Email sent'|'Email replied'|'Email bounced'|'Follow-up required'|'Portfolio sent'|'Qualified'|'Negotiating'|'Offer submitted'|'Closed'|'Not interested'|'Do not contact'|'Follow-up completed';
export type ChannelStatus='active'|'bounced'|'invalid'|'disconnected'|'do_not_contact'|'archived';
export interface AgencyContact{ id:string; firstName:string; lastName:string; title:string; email:string; phone:string; decisionMaker:boolean; emailStatus:ChannelStatus; phoneStatus:ChannelStatus; emailBounceCount:number; emailLastBouncedAt?:string; archivedAt?:string; }
export interface AgencyActivity{ id:string; type:ActivityType; disposition:ActivityDisposition|string; notes:string; occurredAt:string; contactId?:string; followUpAt?:string; completedAt?:string; employeeId?:string; employeeName?:string; subject?:string; }
export interface Agency{ id:string; name:string; website:string; phone:string; generalEmail:string; zip:string; sourceLabel:string; internalNotes:string; isTest:boolean; phoneStatus:ChannelStatus; generalEmailStatus:ChannelStatus; emailBounceCount:number; emailLastBouncedAt?:string; address:string; city:string; state:string; sourceUrl:string; category:string; rating:number|null; reviewCount:number|null; latitude:number|null; longitude:number|null; ownerEmployeeId:string; ownerEmployeeName:string; ownershipStartedAt:string; ownershipExpiresAt:string; status:AgencyStatus; pipelineStage:string; contacts:AgencyContact[]; activities:AgencyActivity[]; createdAt:string; }
type DuplicateMatch={agency:Agency;score:number;reasons:string[]};
type AgencyInput=Omit<Agency,'id'|'createdAt'|'contacts'|'activities'|'ownerEmployeeId'|'ownerEmployeeName'|'ownershipStartedAt'|'ownershipExpiresAt'|'status'|'phoneStatus'|'generalEmailStatus'|'emailBounceCount'|'emailLastBouncedAt'>;
export type ContactEligibility={allowed:boolean;reason:string;lastContactedAt?:string;suppressedUntil?:string;contactedByName?:string;outcome?:string};
type Store={agencies:Agency[];currentEmployee:{id:string;name:string};loading:boolean;error:string;refresh:()=>Promise<void>;duplicateCheck:(input:{name:string;website:string;phone:string;generalEmail:string})=>DuplicateMatch[];createAgency:(input:AgencyInput)=>Promise<Agency>;addContact:(agencyId:string,input:Omit<AgencyContact,'id'|'emailStatus'|'phoneStatus'|'emailBounceCount'|'emailLastBouncedAt'|'archivedAt'>)=>Promise<void>;checkEligibility:(agencyId:string,channel:'phone'|'email',value:string)=>Promise<ContactEligibility>;updateChannel:(agencyId:string,contactId:string|undefined,channel:'phone'|'email',value:string,status:ChannelStatus,reason?:string)=>Promise<void>;addActivity:(agencyId:string,input:Omit<AgencyActivity,'id'|'occurredAt'> & {stage?:AgencyStatus})=>Promise<void>;completeFollowUp:(agencyId:string,activityId:string)=>Promise<void>;snoozeFollowUp:(agencyId:string,activityId:string,nextDate:string)=>Promise<void>;reassign:(agencyId:string,name:string)=>Promise<void>;release:(agencyId:string)=>Promise<void>;clearInventory:()=>Promise<number>;get:(id:string)=>Agency|undefined;};
const Context=createContext<Store|null>(null);
const normalize=(v:string)=>v.toLowerCase().replace(/^https?:\/\/(www\.)?/,'').replace(/\/$/,'').replace(/[^a-z0-9]/g,'');
function statusFromDisposition(disposition:string,current:AgencyStatus):AgencyStatus{if(disposition==='Do not contact')return'do_not_contact';if(disposition==='Not interested')return'not_interested';if(disposition==='Closed')return'closed';if(disposition==='Offer submitted')return'offer_submitted';if(disposition==='Negotiating')return'negotiating';if(disposition==='Portfolio sent')return'portfolio_sent';if(disposition==='Qualified'||disposition==='Reached decision-maker'||disposition==='Requested information')return'qualified';if(['No answer','Left voicemail','Reached receptionist','Call back later','Wrong number','Email drafted','Email sent','Email replied','Email bounced','Follow-up required'].includes(disposition))return'contacted';return current==='new'?'researching':current}
function mapAgency(row:any,contacts:any[],activities:any[],names:Map<string,string>):Agency{return {id:row.id,name:row.name,website:row.website||'',phone:row.phone||'',generalEmail:row.general_email||'',zip:row.zip||'',sourceLabel:row.source_label||'',internalNotes:row.internal_notes||'',isTest:Boolean(row.is_test),phoneStatus:(row.phone_status||'active') as ChannelStatus,generalEmailStatus:(row.general_email_status||'active') as ChannelStatus,emailBounceCount:Number(row.email_bounce_count||0),emailLastBouncedAt:row.email_last_bounced_at||undefined,address:row.address||'',city:row.city||'',state:row.state||'',sourceUrl:row.source_url||'',category:row.category||'',rating:row.rating==null?null:Number(row.rating),reviewCount:row.review_count==null?null:Number(row.review_count),latitude:row.latitude==null?null:Number(row.latitude),longitude:row.longitude==null?null:Number(row.longitude),ownerEmployeeId:row.assigned_to||'',ownerEmployeeName:row.assigned_to?names.get(row.assigned_to)||'Assigned employee':'Unassigned',ownershipStartedAt:row.ownership_started_at||row.created_at,ownershipExpiresAt:row.ownership_expires_at||row.created_at,status:(row.status||'new') as AgencyStatus,pipelineStage:row.pipeline_stage||'new',createdAt:row.created_at,contacts:contacts.filter(c=>c.agency_id===row.id).map(c=>({id:c.id,firstName:c.first_name,lastName:c.last_name||'',title:c.title||'',email:c.email||'',phone:c.phone||'',decisionMaker:Boolean(c.is_decision_maker),emailStatus:(c.email_status||'active') as ChannelStatus,phoneStatus:(c.phone_status||'active') as ChannelStatus,emailBounceCount:Number(c.email_bounce_count||0),emailLastBouncedAt:c.email_last_bounced_at||undefined,archivedAt:c.archived_at||undefined})).filter(c=>!c.archivedAt),activities:activities.filter(a=>a.agency_id===row.id).map(a=>({id:a.id,type:(a.activity_type==='voicemail'?'call':a.activity_type) as ActivityType,disposition:a.disposition||'',notes:a.notes||'',occurredAt:a.occurred_at,contactId:a.contact_id||undefined,followUpAt:a.follow_up_at||undefined,completedAt:a.completed_at||undefined,employeeId:a.employee_id||undefined,employeeName:a.employee_id?names.get(a.employee_id)||'Employee':undefined,subject:a.subject||undefined}))};}
export function AgencyProvider({children}:{children:ReactNode}){
 const {profile}=usePortfolioStore();const [agencies,setAgencies]=useState<Agency[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const currentEmployee={id:profile?.id||'',name:profile?.full_name||'Current user'};
 const refresh=useCallback(async()=>{if(!profile){setAgencies([]);setLoading(false);return;}setLoading(true);setError('');try{const agencyResult=await supabase.from('agencies').select('*').eq('company_id',profile.company_id).order('created_at',{ascending:false});if(agencyResult.error)throw agencyResult.error;const rows=agencyResult.data||[];const ids=rows.map((a:any)=>a.id);const profileResult=await supabase.from('profiles').select('id,full_name').eq('company_id',profile.company_id);if(profileResult.error)throw profileResult.error;let contacts:any[]=[];let activities:any[]=[];if(ids.length){const [contactResult,activityResult]=await Promise.all([supabase.from('agency_contacts').select('*').in('agency_id',ids).order('created_at',{ascending:false}),supabase.from('outreach_activities').select('*').in('agency_id',ids).order('occurred_at',{ascending:false})]);if(contactResult.error)throw contactResult.error;if(activityResult.error)throw activityResult.error;contacts=contactResult.data||[];activities=activityResult.data||[];}const names=new Map<string,string>((profileResult.data||[]).map((p:any)=>[String(p.id),String(p.full_name)]));setAgencies(rows.map((a:any)=>mapAgency(a,contacts,activities,names)));}catch(e){setError(e instanceof Error?e.message:'Unable to load agencies.');}finally{setLoading(false)}},[profile]);
 useEffect(()=>{refresh()},[refresh]);
 const duplicateCheck:Store['duplicateCheck']=input=>agencies.map(agency=>{let score=0;const reasons:string[]=[];if(normalize(input.name)&&normalize(agency.name)===normalize(input.name)){score+=60;reasons.push('Exact company name')}else if(normalize(input.name)&&normalize(agency.name).includes(normalize(input.name))){score+=30;reasons.push('Similar company name')}if(input.website&&normalize(agency.website)===normalize(input.website)){score+=80;reasons.push('Matching website')}if(input.phone&&normalize(agency.phone)===normalize(input.phone)){score+=80;reasons.push('Matching phone')}const email=input.generalEmail.trim().toLowerCase();if(email&&agency.generalEmail.trim().toLowerCase()===email){score+=100;reasons.push('Matching agency email')}if(email&&agency.contacts.some(c=>c.email.trim().toLowerCase()===email)){score+=100;reasons.push('Email already belongs to a contact')}return{agency,score,reasons}}).filter(x=>x.score>=30).sort((a,b)=>b.score-a.score);
 const createAgency=async(input:AgencyInput)=>{if(!profile)throw new Error('Profile is not ready.');const now=new Date().toISOString();const expires=new Date(Date.now()+30*86400000).toISOString();const domain=input.website.toLowerCase().replace(/^https?:\/\/(www\.)?/,'').split('/')[0]||null;const {data,error:e}=await supabase.from('agencies').insert({company_id:profile.company_id,discovered_by:profile.id,assigned_to:profile.id,name:input.name,website:input.website||null,domain,phone:input.phone||null,general_email:input.generalEmail||null,city:input.city||null,state:input.state||null,source_url:input.sourceUrl||null,address:input.address||null,zip:input.zip||null,source_label:input.sourceLabel||null,internal_notes:input.internalNotes||null,is_test:Boolean(input.isTest),ownership_started_at:now,ownership_expires_at:expires,status:'new'}).select('*').single();if(e)throw e;await refresh();return mapAgency(data,[],[],new Map([[profile.id,profile.full_name]]));};
 const addContact=async(agencyId:string,input:Omit<AgencyContact,'id'|'emailStatus'|'phoneStatus'|'emailBounceCount'|'emailLastBouncedAt'|'archivedAt'>)=>{if(!profile)throw new Error('Profile is not ready.');const {error:e}=await supabase.from('agency_contacts').insert({company_id:profile.company_id,agency_id:agencyId,first_name:input.firstName,last_name:input.lastName||null,title:input.title||null,email:input.email||null,phone:input.phone||null,is_decision_maker:input.decisionMaker});if(e)throw e;await supabase.from('agencies').update({status:'researching'}).eq('id',agencyId).eq('status','new');await refresh();};

 const checkEligibility:Store['checkEligibility']=async(agencyId,channel,value)=>{const {data,error:e}=await supabase.rpc('dmh_contact_eligibility',{p_channel:channel,p_value:value,p_agency_id:agencyId});if(e)throw e;const row=Array.isArray(data)?data[0]:data;return {allowed:Boolean(row?.allowed),reason:row?.reason||'',lastContactedAt:row?.last_contacted_at||undefined,suppressedUntil:row?.suppressed_until||undefined,contactedByName:row?.contacted_by_name||undefined,outcome:row?.outcome||undefined};};
 const updateChannel:Store['updateChannel']=async(agencyId,contactId,channel,value,status,reason)=>{const {error:e}=await supabase.rpc('dmh_owner_update_contact_channel',{p_agency_id:agencyId,p_contact_id:contactId||null,p_channel:channel,p_value:value,p_status:status,p_reason:reason||null});if(e)throw e;await refresh();};
 const addActivity=async(agencyId:string,input:Omit<AgencyActivity,'id'|'occurredAt'> & {stage?:AgencyStatus})=>{if(!profile)throw new Error('Profile is not ready.');const existing=agencies.find(a=>a.id===agencyId);const status=input.stage||statusFromDisposition(input.disposition,existing?.status||'new');const type=input.type==='follow_up'?'follow_up':input.type;const selected=existing?.contacts.find(c=>c.id===input.contactId);if(type==='call'||type==='email'){const channel=type==='call'?'phone':'email';const value=channel==='phone'?(selected?.phone||existing?.phone||''):(selected?.email||existing?.generalEmail||'');if(!value)throw new Error(`No ${channel} is available for this contact.`);const {error:protectError}=await supabase.rpc('dmh_register_contact_attempt',{p_agency_id:agencyId,p_contact_id:input.contactId||null,p_channel:channel,p_value:value,p_outcome:input.disposition,p_source:'portal',p_override_reason:null,p_provider_event_id:null});if(protectError)throw protectError;}const {data:activity,error:e}=await supabase.from('outreach_activities').insert({company_id:profile.company_id,agency_id:agencyId,contact_id:input.contactId||null,employee_id:profile.id,activity_type:type,disposition:input.disposition,notes:input.notes,subject:input.subject||null,follow_up_at:input.followUpAt||null}).select('id').single();if(e)throw e;if(input.followUpAt){const {error:followError}=await supabase.from('follow_ups').insert({company_id:profile.company_id,agency_id:agencyId,employee_id:profile.id,due_at:input.followUpAt,reason:input.notes||input.disposition,source_activity_id:activity.id});if(followError)throw followError;}await supabase.from('agencies').update({status,assigned_to:profile.id,ownership_started_at:new Date().toISOString(),ownership_expires_at:new Date(Date.now()+30*86400000).toISOString()}).eq('id',agencyId);await refresh();};
 const completeFollowUp=async(_agencyId:string,activityId:string)=>{const completedAt=new Date().toISOString();const {error:e}=await supabase.from('outreach_activities').update({completed_at:completedAt,disposition:'Follow-up completed'}).eq('id',activityId);if(e)throw e;const {error:followError}=await supabase.from('follow_ups').update({completed_at:completedAt}).eq('source_activity_id',activityId);if(followError)throw followError;await refresh();};
 const snoozeFollowUp=async(_agencyId:string,activityId:string,nextDate:string)=>{const {error:e}=await supabase.from('outreach_activities').update({follow_up_at:nextDate,completed_at:null}).eq('id',activityId);if(e)throw e;const {error:followError}=await supabase.from('follow_ups').update({due_at:nextDate,completed_at:null}).eq('source_activity_id',activityId);if(followError)throw followError;await refresh();};
 const reassign=async(agencyId:string,name:string)=>{if(!profile)throw new Error('Profile is not ready.');const {data:employee,error:findError}=await supabase.from('profiles').select('id,full_name').eq('company_id',profile.company_id).ilike('full_name',name).limit(1).maybeSingle();if(findError)throw findError;if(!employee)throw new Error('No employee profile matched that name.');const {error:e}=await supabase.from('agencies').update({assigned_to:employee.id,ownership_started_at:new Date().toISOString(),ownership_expires_at:new Date(Date.now()+30*86400000).toISOString()}).eq('id',agencyId);if(e)throw e;await refresh();};
 const release=async(agencyId:string)=>{const {error:e}=await supabase.rpc('dmh_release_agency_from_inventory',{p_agency_id:agencyId});if(e)throw e;await refresh();};
 const clearInventory=async()=>{const {data,error:e}=await supabase.rpc('dmh_clear_my_agency_inventory');if(e)throw e;await refresh();return Number(data||0);};
 const value=useMemo<Store>(()=>({agencies,currentEmployee,loading,error,refresh,duplicateCheck,createAgency,addContact,checkEligibility,updateChannel,addActivity,completeFollowUp,snoozeFollowUp,reassign,release,clearInventory,get:id=>agencies.find(a=>a.id===id)}),[agencies,currentEmployee.id,currentEmployee.name,loading,error,refresh]);return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useAgencyStore(){const x=useContext(Context);if(!x)throw new Error('AgencyProvider missing');return x;}
