import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import { supabase } from '../lib/supabase';
import { usePortfolioStore } from './PortfolioStore';

export type ApprovalStatus='pending'|'approved'|'rejected'|'returned'|'expired'|'cancelled'|'executed';
export type ApprovalType='below_floor_offer'|'discount_exception'|'marketing_override'|'as_is_override'|'deal_reassignment'|'commission_exception'|'buyer_suppression_removal'|'funding_extension'|'closing_document_exception'|'high_value_campaign'|'reservation_extension'|'other';
export type ApprovalRequest={id:string;companyId:string;requestType:ApprovalType;status:ApprovalStatus;title:string;reason:string;recommendation:string;entityType:string;entityId?:string;portfolioId?:string;agencyId?:string;dealId?:string;requestedBy:string;reviewedBy?:string;assignedEmployeeId?:string;originalValue?:number;requestedValue?:number;approvedValue?:number;financialImpact?:number;supportingNotes:string;ownerNotes:string;expiresAt?:string;decidedAt?:string;executedAt?:string;createdAt:string;updatedAt:string};
type NewRequest={requestType:ApprovalType;title:string;reason:string;recommendation?:string;entityType?:string;entityId?:string;portfolioId?:string;agencyId?:string;dealId?:string;assignedEmployeeId?:string;originalValue?:number;requestedValue?:number;financialImpact?:number;supportingNotes?:string;expiresAt?:string};
type Store={requests:ApprovalRequest[];loading:boolean;error:string;refresh:()=>Promise<void>;create:(input:NewRequest)=>Promise<void>;decide:(id:string,status:Extract<ApprovalStatus,'approved'|'rejected'|'returned'|'cancelled'|'executed'>,notes:string,approvedValue?:number)=>Promise<void>};
const Context=createContext<Store|null>(null);
const num=(v:any)=>v==null?undefined:Number(v);
const map=(r:any):ApprovalRequest=>({id:r.id,companyId:r.company_id,requestType:r.request_type,status:r.status,title:r.title,reason:r.reason,recommendation:r.recommendation||'',entityType:r.entity_type||'general',entityId:r.entity_id||undefined,portfolioId:r.portfolio_id||undefined,agencyId:r.agency_id||undefined,dealId:r.deal_id||undefined,requestedBy:r.requested_by,reviewedBy:r.reviewed_by||undefined,assignedEmployeeId:r.assigned_employee_id||undefined,originalValue:num(r.original_value),requestedValue:num(r.requested_value),approvedValue:num(r.approved_value),financialImpact:num(r.financial_impact),supportingNotes:r.supporting_notes||'',ownerNotes:r.owner_notes||'',expiresAt:r.expires_at||undefined,decidedAt:r.decided_at||undefined,executedAt:r.executed_at||undefined,createdAt:r.created_at,updatedAt:r.updated_at});
export function ApprovalProvider({children}:{children:ReactNode}){const {profile}=usePortfolioStore();const [requests,setRequests]=useState<ApprovalRequest[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 const refresh=useCallback(async()=>{if(!profile){setRequests([]);return}setLoading(true);setError('');const {data,error:e}=await supabase.from('owner_approval_requests').select('*').eq('company_id',profile.company_id).order('created_at',{ascending:false});if(e)setError(e.message);else setRequests((data||[]).map(map));setLoading(false)},[profile]);
 useEffect(()=>{refresh()},[refresh]);
 const create=async(input:NewRequest)=>{if(!profile)throw new Error('Profile not ready.');const {error:e}=await supabase.from('owner_approval_requests').insert({company_id:profile.company_id,requested_by:profile.id,request_type:input.requestType,status:'pending',title:input.title,reason:input.reason,recommendation:input.recommendation||'',entity_type:input.entityType||'general',entity_id:input.entityId||null,portfolio_id:input.portfolioId||null,agency_id:input.agencyId||null,deal_id:input.dealId||null,assigned_employee_id:input.assignedEmployeeId||null,original_value:input.originalValue??null,requested_value:input.requestedValue??null,financial_impact:input.financialImpact??null,supporting_notes:input.supportingNotes||'',expires_at:input.expiresAt||null});if(e)throw e;await refresh()};
 const decide=async(id:string,status:Extract<ApprovalStatus,'approved'|'rejected'|'returned'|'cancelled'|'executed'>,notes:string,approvedValue?:number)=>{const {error:e}=await supabase.rpc('dmh_decide_owner_approval',{p_request_id:id,p_decision:status,p_owner_notes:notes,p_approved_value:approvedValue??null});if(e)throw e;await refresh()};
 const value=useMemo(()=>({requests,loading,error,refresh,create,decide}),[requests,loading,error,refresh]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useApprovalStore(){const x=useContext(Context);if(!x)throw new Error('ApprovalProvider missing');return x}
