import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import { supabase } from '../lib/supabase';
import { usePortfolioStore } from './PortfolioStore';

export type ReviewStatus='not_reviewed'|'review_complete'|'disclosure_required'|'material_discrepancy'|'hold_from_marketing'|'owner_approved_with_disclosure';
export type DetectedIssue={severity:'info'|'warning'|'critical';message:string};
export type AsIsReview={
 id:string;portfolioId:string;status:ReviewStatus;saleCondition:string;chainOfTitleProvided:boolean;accountMediaProvided:boolean;priorSaleHistoryProvided:boolean;originalAgreementsProvided:boolean;paymentHistoryProvided:boolean;
 accountNumbersPresent?:boolean;creditorNamesConsistent?:boolean;datesConsistent?:boolean;advertisedAccountCount?:number;verifiedAccountCount?:number;advertisedFaceValue?:number;verifiedFaceValue?:number;oldestAccountDate?:string;newestAccountDate?:string;duplicateCount:number;blankCriticalFieldPercent?:number;
 availableFields:string[];missingFields:string[];detectedIssues:DetectedIssue[];sellerDescription:string;reviewerNotes:string;disclosureText:string;ownerOverrideReason:string;reviewedAt?:string;ownerApprovedAt?:string;
};
type SaveInput=Omit<AsIsReview,'id'|'reviewedAt'|'ownerApprovedAt'>;
type Store={reviews:AsIsReview[];loading:boolean;error:string;refresh:()=>Promise<void>;save:(input:SaveInput)=>Promise<void>;generateDisclosure:(portfolioId:string)=>Promise<string>;isMarketable:(portfolioId:string)=>boolean};
const Context=createContext<Store|null>(null);
const map=(r:any):AsIsReview=>({id:r.id,portfolioId:r.portfolio_id,status:r.review_status,saleCondition:r.sale_condition,chainOfTitleProvided:r.chain_of_title_provided,accountMediaProvided:r.account_media_provided,priorSaleHistoryProvided:r.prior_sale_history_provided,originalAgreementsProvided:r.original_agreements_provided,paymentHistoryProvided:r.payment_history_provided,accountNumbersPresent:r.account_numbers_present??undefined,creditorNamesConsistent:r.creditor_names_consistent??undefined,datesConsistent:r.dates_consistent??undefined,advertisedAccountCount:r.advertised_account_count==null?undefined:Number(r.advertised_account_count),verifiedAccountCount:r.verified_account_count==null?undefined:Number(r.verified_account_count),advertisedFaceValue:r.advertised_face_value==null?undefined:Number(r.advertised_face_value),verifiedFaceValue:r.verified_face_value==null?undefined:Number(r.verified_face_value),oldestAccountDate:r.oldest_account_date||undefined,newestAccountDate:r.newest_account_date||undefined,duplicateCount:Number(r.duplicate_count||0),blankCriticalFieldPercent:r.blank_critical_field_percent==null?undefined:Number(r.blank_critical_field_percent),availableFields:r.available_fields||[],missingFields:r.missing_fields||[],detectedIssues:Array.isArray(r.detected_issues)?r.detected_issues:[],sellerDescription:r.seller_description||'',reviewerNotes:r.reviewer_notes||'',disclosureText:r.disclosure_text||'',ownerOverrideReason:r.owner_override_reason||'',reviewedAt:r.reviewed_at||undefined,ownerApprovedAt:r.owner_approved_at||undefined});
export function AsIsReviewProvider({children}:{children:ReactNode}){const {profile}=usePortfolioStore();const [reviews,setReviews]=useState<AsIsReview[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 const refresh=useCallback(async()=>{if(!profile){setReviews([]);return}setLoading(true);setError('');const {data,error:e}=await supabase.from('portfolio_as_is_reviews').select('*').eq('company_id',profile.company_id).order('updated_at',{ascending:false});if(e)setError(e.message);else setReviews((data||[]).map(map));setLoading(false)},[profile]);
 useEffect(()=>{refresh()},[refresh]);
 const save=async(input:SaveInput)=>{if(!profile)throw new Error('Profile not ready.');const payload:any={company_id:profile.company_id,portfolio_id:input.portfolioId,review_status:input.status,sale_condition:'as_is',chain_of_title_provided:input.chainOfTitleProvided,account_media_provided:input.accountMediaProvided,prior_sale_history_provided:input.priorSaleHistoryProvided,original_agreements_provided:input.originalAgreementsProvided,payment_history_provided:input.paymentHistoryProvided,account_numbers_present:input.accountNumbersPresent??null,creditor_names_consistent:input.creditorNamesConsistent??null,dates_consistent:input.datesConsistent??null,advertised_account_count:input.advertisedAccountCount??null,verified_account_count:input.verifiedAccountCount??null,advertised_face_value:input.advertisedFaceValue??null,verified_face_value:input.verifiedFaceValue??null,oldest_account_date:input.oldestAccountDate||null,newest_account_date:input.newestAccountDate||null,duplicate_count:input.duplicateCount||0,blank_critical_field_percent:input.blankCriticalFieldPercent??null,available_fields:input.availableFields,missing_fields:input.missingFields,detected_issues:input.detectedIssues,seller_description:input.sellerDescription,reviewer_notes:input.reviewerNotes,disclosure_text:input.disclosureText,owner_override_reason:input.ownerOverrideReason};const {error:e}=await supabase.from('portfolio_as_is_reviews').upsert(payload,{onConflict:'portfolio_id'});if(e)throw e;await refresh()};
 const generateDisclosure=async(portfolioId:string)=>{const {data,error:e}=await supabase.rpc('dmh_generate_as_is_disclosure',{p_portfolio_id:portfolioId});if(e)throw e;await refresh();return String(data||'')};
 const value=useMemo(()=>({reviews,loading,error,refresh,save,generateDisclosure,isMarketable:(id:string)=>['review_complete','owner_approved_with_disclosure'].includes(reviews.find(r=>r.portfolioId===id)?.status||'')}),[reviews,loading,error,refresh]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useAsIsReviewStore(){const x=useContext(Context);if(!x)throw new Error('AsIsReviewProvider missing');return x}
