import {createContext,useCallback,useContext,useEffect,useMemo,useState,type ReactNode} from 'react';
import {supabase} from '../lib/supabase';
import {usePortfolioStore} from './PortfolioStore';

export type BuyerProfile={id:string;company_name:string;contact_name:string;email:string;phone?:string;status:'pending'|'approved'|'denied'|'suspended';created_at:string};
export type BuyerPortfolio={id:string;name:string;category:string;accountCount:number;faceValue:number|null;askingPrice:number|null;description:string;sellingPoints:string[];status:string;canDownloadSample:boolean;expiresAt:string|null;disclosureSigned:boolean};
export type DealRoomSnapshot={room:any|null;offer:any|null;messages:any[];documents:any[];rounds:any[]};
export type BuyerAccess={id:string;buyer_id:string;portfolio_id:string;can_download_sample:boolean;expires_at:string|null;revoked_at:string|null;portfolio?:{name:string}};
type Store={buyer:BuyerProfile|null;buyers:BuyerProfile[];portfolios:BuyerPortfolio[];access:BuyerAccess[];loading:boolean;error:string;refresh:()=>Promise<void>;setBuyerStatus:(id:string,status:BuyerProfile['status'])=>Promise<void>;grantAccess:(buyerId:string,portfolioId:string,download:boolean,expiresAt?:string)=>Promise<void>;acknowledge:(portfolioId:string)=>Promise<void>;submitOffer:(portfolioId:string,amount:number,terms:string,conditions:string)=>Promise<string>;sendMessage:(buyerId:string,portfolioId:string,body:string,offerId?:string)=>Promise<void>;loadRoom:(portfolioId:string)=>Promise<DealRoomSnapshot>;offerAction:(offerId:string,action:string,amount?:number,message?:string,expiresAt?:string)=>Promise<void>;dealGate:(roomId:string,gate:string)=>Promise<void>;closeDeal:(roomId:string)=>Promise<string>;uploadDocument:(roomId:string,type:string,title:string,url:string,visible:boolean)=>Promise<void>;getDocumentGate:(portfolioId:string)=>Promise<{nda_executed:boolean;purchase_agreement_executed:boolean}>;downloadPortfolioFile:(portfolioId:string,type:'masked'|'unmasked')=>Promise<void>};
const C=createContext<Store|null>(null);
export function BuyerPortalProvider({children}:{children:ReactNode}){const {profile}=usePortfolioStore();const [buyer,setBuyer]=useState<BuyerProfile|null>(null);const [buyers,setBuyers]=useState<BuyerProfile[]>([]);const [portfolios,setPortfolios]=useState<BuyerPortfolio[]>([]);const [access,setAccess]=useState<BuyerAccess[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
const refresh=useCallback(async()=>{if(!profile)return;setLoading(true);setError('');try{if(profile.role==='buyer'){const {data,error}=await supabase.rpc('dmh_buyer_marketplace');if(error)throw error;const raw:any=data||{};setBuyer(raw.buyer||null);setPortfolios(raw.portfolios||[]);setBuyers([]);setAccess([]);}else if(profile.role==='owner'){const [b,a]=await Promise.all([supabase.from('buyer_profiles').select('*').eq('company_id',profile.company_id).order('created_at',{ascending:false}),supabase.from('buyer_portfolio_access').select('*,portfolio:portfolios(name)').eq('company_id',profile.company_id).order('granted_at',{ascending:false})]);if(b.error)throw b.error;if(a.error)throw a.error;setBuyers((b.data||[]) as BuyerProfile[]);setAccess((a.data||[]) as BuyerAccess[]);setBuyer(null);setPortfolios([]);}}catch(e){setError(e instanceof Error?e.message:'Unable to load buyer portal.')}finally{setLoading(false)}},[profile]);
useEffect(()=>{refresh()},[refresh]);
const setBuyerStatus=async(id:string,status:BuyerProfile['status'])=>{const {error}=await supabase.rpc('dmh_set_buyer_status',{p_buyer_id:id,p_status:status});if(error)throw error;await refresh()};
const grantAccess=async(buyerId:string,portfolioId:string,download:boolean,expiresAt?:string)=>{const {error}=await supabase.rpc('dmh_grant_buyer_portfolio_access',{p_buyer_id:buyerId,p_portfolio_id:portfolioId,p_can_download_sample:download,p_expires_at:expiresAt||null});if(error)throw error;await refresh()};
const acknowledge=async(portfolioId:string)=>{const {error}=await supabase.rpc('dmh_buyer_acknowledge_disclosure',{p_portfolio_id:portfolioId});if(error)throw error;await refresh()};
const submitOffer=async(portfolioId:string,amount:number,terms:string,conditions:string)=>{const {data,error}=await supabase.rpc('dmh_buyer_submit_offer',{p_portfolio_id:portfolioId,p_amount:amount,p_payment_terms:terms||null,p_conditions:conditions||null});if(error)throw error;await refresh();return String(data)};
const loadRoom=async(portfolioId:string)=>{const {data,error}=await supabase.rpc('dmh_deal_room_snapshot',{p_portfolio_id:portfolioId});if(error)throw error;return (data||{room:null,offer:null,messages:[],documents:[],rounds:[]}) as DealRoomSnapshot};
const offerAction=async(offerId:string,action:string,amount?:number,message?:string,expiresAt?:string)=>{const {error}=await supabase.rpc('dmh_deal_offer_action',{p_offer_id:offerId,p_action:action,p_amount:amount||null,p_message:message||null,p_reservation_expires_at:expiresAt||null});if(error)throw error};
const dealGate=async(roomId:string,gate:string)=>{const {error}=await supabase.rpc('dmh_deal_gate',{p_room_id:roomId,p_gate:gate});if(error)throw error};
const closeDeal=async(roomId:string)=>{const {data,error}=await supabase.rpc('dmh_close_buyer_deal',{p_room_id:roomId});if(error)throw error;return String(data)};
const uploadDocument=async(roomId:string,type:string,title:string,url:string,visible:boolean)=>{if(!profile)throw new Error('Profile unavailable');const {error}=await supabase.from('buyer_deal_documents').insert({company_id:profile.company_id,room_id:roomId,document_type:type,title,external_url:url||null,status:'uploaded',visible_to_buyer:visible,uploaded_by:profile.id});if(error)throw error};

const getDocumentGate=async(portfolioId:string)=>{const {data,error}=await supabase.rpc('dmh_document_access_gate',{p_portfolio_id:portfolioId});if(error)throw error;return (data||{nda_executed:false,purchase_agreement_executed:false}) as {nda_executed:boolean;purchase_agreement_executed:boolean}};
const downloadPortfolioFile=async(portfolioId:string,type:'masked'|'unmasked')=>{const {data,error}=await supabase.rpc('dmh_portfolio_file_access',{p_portfolio_id:portfolioId,p_file_type:type});if(error)throw error;const row:any=data;const signed=await supabase.storage.from('portfolio-files').createSignedUrl(row.storagePath,300,{download:row.fileName});if(signed.error)throw signed.error;window.open(signed.data.signedUrl,'_blank','noopener,noreferrer')};
const sendMessage=async(buyerId:string,portfolioId:string,body:string,offerId?:string)=>{if(!profile)throw new Error('Profile unavailable');const {error}=await supabase.from('buyer_deal_messages').insert({company_id:profile.company_id,buyer_id:buyerId,portfolio_id:portfolioId,offer_id:offerId||null,sender_role:profile.role,sender_id:profile.id,body});if(error)throw error;};
const value=useMemo(()=>({buyer,buyers,portfolios,access,loading,error,refresh,setBuyerStatus,grantAccess,acknowledge,submitOffer,sendMessage,loadRoom,offerAction,dealGate,closeDeal,uploadDocument,getDocumentGate,downloadPortfolioFile}),[buyer,buyers,portfolios,access,loading,error,refresh]);return <C.Provider value={value}>{children}</C.Provider>}
export function useBuyerPortalStore(){const x=useContext(C);if(!x)throw new Error('BuyerPortalProvider missing');return x}
