import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import { supabase } from '../lib/supabase';
import { usePortfolioStore } from './PortfolioStore';

export type CampaignStatus='draft'|'ready'|'active'|'paused'|'completed'|'cancelled';
export type RecipientStatus='selected'|'assigned'|'queued'|'sent'|'delivered'|'opened'|'replied'|'interested'|'declined'|'negotiating'|'purchased'|'failed'|'suppressed';
export type Campaign={id:string;portfolioId:string;name:string;templateId?:string;subject:string;body:string;status:CampaignStatus;maxRecipients:number;approvedAt?:string;launchedAt?:string;createdAt:string;createdBy:string};
export type CampaignRecipient={id:string;campaignId:string;portfolioId:string;agencyId:string;contactId?:string;assignedEmployeeId?:string;matchScore:number;recipientEmail:string;recipientName:string;personalizedSubject:string;personalizedBody:string;status:RecipientStatus;outreachMessageId?:string;sentAt?:string;repliedAt?:string;notes:string;createdAt:string};
export type CampaignEvent={id:string;campaignId:string;recipientId?:string;eventType:string;detail:string;createdAt:string};

type CreateCampaignInput={portfolioId:string;name:string;templateId?:string;subject:string;body:string;maxRecipients:number};
type AddRecipientInput={campaignId:string;portfolioId:string;agencyId:string;contactId?:string;assignedEmployeeId?:string;matchScore:number;recipientEmail:string;recipientName:string;personalizedSubject:string;personalizedBody:string};
type Store={campaigns:Campaign[];recipients:CampaignRecipient[];events:CampaignEvent[];loading:boolean;error:string;refresh:()=>Promise<void>;createCampaign:(input:CreateCampaignInput)=>Promise<string>;updateCampaign:(id:string,patch:Partial<Campaign>)=>Promise<void>;setCampaignStatus:(id:string,status:CampaignStatus)=>Promise<void>;addRecipient:(input:AddRecipientInput)=>Promise<void>;removeRecipient:(id:string)=>Promise<void>;assignRecipient:(id:string,employeeId:string)=>Promise<void>;updateRecipientStatus:(id:string,status:RecipientStatus,notes?:string)=>Promise<void>;sendRecipient:(id:string)=>Promise<void>;duplicateCheck:(portfolioId:string,agencyId:string,campaignId?:string)=>Promise<boolean>};
const Context=createContext<Store|null>(null);
const campaignMap=(r:any):Campaign=>({id:r.id,portfolioId:r.portfolio_id,name:r.name,templateId:r.template_id||undefined,subject:r.subject||'',body:r.body||'',status:r.status,maxRecipients:Number(r.max_recipients||50),approvedAt:r.approved_at||undefined,launchedAt:r.launched_at||undefined,createdAt:r.created_at,createdBy:r.created_by});
const recipientMap=(r:any):CampaignRecipient=>({id:r.id,campaignId:r.campaign_id,portfolioId:r.portfolio_id,agencyId:r.agency_id,contactId:r.contact_id||undefined,assignedEmployeeId:r.assigned_employee_id||undefined,matchScore:Number(r.match_score||0),recipientEmail:r.recipient_email||'',recipientName:r.recipient_name||'',personalizedSubject:r.personalized_subject||'',personalizedBody:r.personalized_body||'',status:r.status,outreachMessageId:r.outreach_message_id||undefined,sentAt:r.sent_at||undefined,repliedAt:r.replied_at||undefined,notes:r.notes||'',createdAt:r.created_at});

export function CampaignProvider({children}:{children:ReactNode}){
 const {profile}=usePortfolioStore();const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [recipients,setRecipients]=useState<CampaignRecipient[]>([]);const [events,setEvents]=useState<CampaignEvent[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const refresh=useCallback(async()=>{if(!profile){setLoading(false);return;}setLoading(true);setError('');try{const [c,r,e]=await Promise.all([supabase.from('portfolio_outreach_campaigns').select('*').eq('company_id',profile.company_id).order('created_at',{ascending:false}),supabase.from('portfolio_campaign_recipients').select('*').eq('company_id',profile.company_id).order('created_at',{ascending:false}),supabase.from('portfolio_campaign_events').select('*').eq('company_id',profile.company_id).order('created_at',{ascending:false}).limit(300)]);if(c.error)throw c.error;if(r.error)throw r.error;if(e.error)throw e.error;setCampaigns((c.data||[]).map(campaignMap));setRecipients((r.data||[]).map(recipientMap));setEvents((e.data||[]).map((x:any)=>({id:x.id,campaignId:x.campaign_id,recipientId:x.recipient_id||undefined,eventType:x.event_type,detail:x.detail||'',createdAt:x.created_at})));}catch(err){setError(err instanceof Error?err.message:'Unable to load campaigns.')}finally{setLoading(false)}},[profile]);
 useEffect(()=>{void refresh()},[refresh]);
 const log=async(campaignId:string,eventType:string,detail:string,recipientId?:string)=>{if(!profile)return;await supabase.from('portfolio_campaign_events').insert({company_id:profile.company_id,campaign_id:campaignId,recipient_id:recipientId||null,event_type:eventType,detail,actor_id:profile.id});};
 const createCampaign=async(input:CreateCampaignInput)=>{if(!profile)throw new Error('Profile unavailable.');const {data,error:e}=await supabase.from('portfolio_outreach_campaigns').insert({company_id:profile.company_id,portfolio_id:input.portfolioId,name:input.name.trim(),template_id:input.templateId||null,subject:input.subject,body:input.body,max_recipients:input.maxRecipients,created_by:profile.id}).select('id').single();if(e)throw e;await log(data.id,'campaign_created','Campaign created.');await refresh();return data.id;};
 const updateCampaign=async(id:string,patch:Partial<Campaign>)=>{const db:any={updated_at:new Date().toISOString()};if(patch.name!==undefined)db.name=patch.name;if(patch.templateId!==undefined)db.template_id=patch.templateId||null;if(patch.subject!==undefined)db.subject=patch.subject;if(patch.body!==undefined)db.body=patch.body;if(patch.maxRecipients!==undefined)db.max_recipients=patch.maxRecipients;const {error:e}=await supabase.from('portfolio_outreach_campaigns').update(db).eq('id',id);if(e)throw e;await log(id,'campaign_updated','Campaign settings updated.');await refresh();};
 const setCampaignStatus=async(id:string,status:CampaignStatus)=>{if(!profile)throw new Error('Profile unavailable.');const patch:any={status,updated_at:new Date().toISOString()};if(status==='ready'){patch.approved_by=profile.id;patch.approved_at=new Date().toISOString()}if(status==='active'){patch.launched_by=profile.id;patch.launched_at=new Date().toISOString();patch.paused_at=null}if(status==='paused')patch.paused_at=new Date().toISOString();if(status==='completed')patch.completed_at=new Date().toISOString();const {error:e}=await supabase.from('portfolio_outreach_campaigns').update(patch).eq('id',id);if(e)throw e;await log(id,`campaign_${status}`,`Campaign moved to ${status}.`);await refresh();};
 const duplicateCheck=async(portfolioId:string,agencyId:string,campaignId?:string)=>{const {data,error:e}=await supabase.rpc('dmh_campaign_duplicate_check',{p_portfolio_id:portfolioId,p_agency_id:agencyId,p_exclude_campaign_id:campaignId||null});if(e)throw e;return Boolean(data);};
 const addRecipient=async(input:AddRecipientInput)=>{if(!profile)throw new Error('Profile unavailable.');const duplicate=await duplicateCheck(input.portfolioId,input.agencyId,input.campaignId);if(duplicate)throw new Error('Duplicate outreach blocked: this agency is already active in another campaign for this portfolio.');const campaign=campaigns.find(c=>c.id===input.campaignId);const count=recipients.filter(r=>r.campaignId===input.campaignId).length;if(campaign&&count>=campaign.maxRecipients)throw new Error(`Campaign limit reached (${campaign.maxRecipients}).`);const {data,error:e}=await supabase.from('portfolio_campaign_recipients').insert({company_id:profile.company_id,campaign_id:input.campaignId,portfolio_id:input.portfolioId,agency_id:input.agencyId,contact_id:input.contactId||null,assigned_employee_id:input.assignedEmployeeId||null,match_score:input.matchScore,recipient_email:input.recipientEmail||null,recipient_name:input.recipientName||null,personalized_subject:input.personalizedSubject,personalized_body:input.personalizedBody,status:input.assignedEmployeeId?'assigned':'selected'}).select('id').single();if(e)throw e;await log(input.campaignId,'recipient_added',`${input.recipientName||input.recipientEmail} added to campaign.`,data.id);await refresh();};
 const removeRecipient=async(id:string)=>{const recipient=recipients.find(r=>r.id===id);if(!recipient)return;const {error:e}=await supabase.from('portfolio_campaign_recipients').delete().eq('id',id).in('status',['selected','assigned']);if(e)throw e;await log(recipient.campaignId,'recipient_removed','Recipient removed before send.',id);await refresh();};
 const assignRecipient=async(id:string,employeeId:string)=>{const recipient=recipients.find(r=>r.id===id);if(!recipient)return;const {error:e}=await supabase.from('portfolio_campaign_recipients').update({assigned_employee_id:employeeId||null,status:employeeId?'assigned':'selected',updated_at:new Date().toISOString()}).eq('id',id);if(e)throw e;await log(recipient.campaignId,'recipient_assigned',employeeId?'Recipient assigned to employee.':'Recipient unassigned.',id);await refresh();};
 const updateRecipientStatus=async(id:string,status:RecipientStatus,notes='')=>{const recipient=recipients.find(r=>r.id===id);if(!recipient)return;const patch:any={status,last_status_at:new Date().toISOString(),updated_at:new Date().toISOString()};if(notes)patch.notes=notes;if(['replied','interested','negotiating','purchased'].includes(status))patch.replied_at=new Date().toISOString();const {error:e}=await supabase.from('portfolio_campaign_recipients').update(patch).eq('id',id);if(e)throw e;await log(recipient.campaignId,`recipient_${status}`,notes||`Recipient moved to ${status}.`,id);await refresh();};
 const sendRecipient=async(id:string)=>{const recipient=recipients.find(r=>r.id===id);const campaign=recipient&&campaigns.find(c=>c.id===recipient.campaignId);if(!profile||!recipient||!campaign)throw new Error('Campaign recipient unavailable.');if(campaign.status!=='active')throw new Error('The campaign must be active before sending.');if(!recipient.recipientEmail)throw new Error('Recipient email is missing.');await updateRecipientStatus(id,'queued');const {data:messageId,error:e}=await supabase.rpc('dmh_queue_outreach_email',{p_agency_id:recipient.agencyId,p_contact_id:recipient.contactId||null,p_portfolio_id:recipient.portfolioId,p_template_id:campaign.templateId||null,p_recipient:recipient.recipientEmail,p_subject:recipient.personalizedSubject||campaign.subject,p_body:recipient.personalizedBody||campaign.body,p_follow_up_at:null});if(e){await updateRecipientStatus(id,'failed',e.message);throw e;}const {data:fn,error:fnError}=await supabase.functions.invoke('send-outreach-email',{body:{messageId}});if(fnError||fn?.ok===false){const msg=fnError?.message||fn?.error||'Email failed.';await updateRecipientStatus(id,'failed',msg);throw new Error(msg);}await supabase.from('portfolio_campaign_recipients').update({status:'sent',outreach_message_id:messageId,sent_at:new Date().toISOString(),last_status_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id);await log(recipient.campaignId,'recipient_sent',`Campaign email sent to ${recipient.recipientEmail}.`,id);await refresh();};
 const value=useMemo<Store>(()=>({campaigns,recipients,events,loading,error,refresh,createCampaign,updateCampaign,setCampaignStatus,addRecipient,removeRecipient,assignRecipient,updateRecipientStatus,sendRecipient,duplicateCheck}),[campaigns,recipients,events,loading,error,refresh]);return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useCampaignStore(){const x=useContext(Context);if(!x)throw new Error('CampaignProvider missing');return x;}
