import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import { supabase } from '../lib/supabase';
import { usePortfolioStore } from './PortfolioStore';
import { useAgencyStore } from './AgencyStore';

export interface Reservation {id:string;offerId:string;portfolioId:string;portfolioName:string;agencyId:string;agencyName:string;amount:number;paymentDeadline:string;reservationExpiresAt?:string;status:'active'|'paid'|'expired'|'cancelled';depositRequired:number;depositReceived:number;depositReceivedAt?:string;balanceReceived:number;balanceReceivedAt?:string;paymentMethod?:string;proofStoragePath?:string;notes?:string;failureReason?:string;createdAt:string;}
export interface Sale {id:string;portfolioId:string;portfolioName:string;agencyId:string;agencyName:string;winningEmployeeId?:string;winningEmployeeName?:string;salePrice:number;acquisitionCost:number;commissionTotal:number;netRevenue:number;paidAt?:string;closedAt:string;paymentMethod?:string;}
export interface Commission {id:string;saleId:string;employeeId:string;employeeName:string;amount:number;status:'estimated'|'pending'|'approved'|'paid'|'cancelled'|'disputed';calculationType:'flat'|'percentage';rate?:number;approvedAt?:string;paidAt?:string;createdAt:string;}
interface Store {reservations:Reservation[];sales:Sale[];commissions:Commission[];employees:{id:string;name:string}[];loading:boolean;error:string;refresh:()=>Promise<void>;recordDeposit:(id:string,input:{amount:number;paymentMethod:string;receivedAt:string;proof?:File;notes?:string})=>Promise<void>;closeSale:(id:string,input:{balanceAmount:number;paymentMethod:string;paidAt:string;winningEmployeeId:string;commissionType:'flat'|'percentage';commissionValue:number;proof?:File;notes?:string})=>Promise<void>;releaseReservation:(id:string,reason:string)=>Promise<void>;setCommissionStatus:(id:string,status:'approved'|'paid'|'cancelled'|'disputed')=>Promise<void>;}
const Context=createContext<Store|null>(null);
export function ClosingProvider({children}:{children:ReactNode}){
 const {profile,portfolios,refresh:refreshPortfolios}=usePortfolioStore(); const {agencies}=useAgencyStore();
 const [reservations,setReservations]=useState<Reservation[]>([]);const [sales,setSales]=useState<Sale[]>([]);const [commissions,setCommissions]=useState<Commission[]>([]);const [employees,setEmployees]=useState<{id:string;name:string}[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const refresh=useCallback(async()=>{if(!profile){setLoading(false);return}setLoading(true);setError('');try{const [r,s,c,p]=await Promise.all([supabase.from('reservations').select('*').eq('company_id',profile.company_id).order('created_at',{ascending:false}),supabase.from('sales').select('*').eq('company_id',profile.company_id).order('closed_at',{ascending:false}),supabase.from('commissions').select('*').eq('company_id',profile.company_id).order('created_at',{ascending:false}),supabase.from('profiles').select('id,full_name,role').eq('company_id',profile.company_id).eq('role','employee')]);if(r.error)throw r.error;if(s.error)throw s.error;if(c.error)throw c.error;if(p.error)throw p.error;const names=new Map<string,string>((p.data||[]).map((x:any)=>[x.id,x.full_name||'Employee']));setEmployees((p.data||[]).map((x:any)=>({id:x.id,name:x.full_name||'Employee'})));setReservations((r.data||[]).map((x:any)=>({id:x.id,offerId:x.offer_id,portfolioId:x.portfolio_id,portfolioName:portfolios.find(v=>v.id===x.portfolio_id)?.name||'Portfolio',agencyId:x.buyer_agency_id,agencyName:agencies.find(v=>v.id===x.buyer_agency_id)?.name||'Agency',amount:Number(x.amount),paymentDeadline:x.payment_deadline,reservationExpiresAt:x.reservation_expires_at||undefined,status:x.status,depositRequired:Number(x.deposit_required||0),depositReceived:Number(x.deposit_received||0),depositReceivedAt:x.deposit_received_at||undefined,balanceReceived:Number(x.balance_received||0),balanceReceivedAt:x.balance_received_at||undefined,paymentMethod:x.payment_method||undefined,proofStoragePath:x.proof_storage_path||undefined,notes:x.notes||undefined,failureReason:x.failure_reason||undefined,createdAt:x.created_at})));setSales((s.data||[]).map((x:any)=>({id:x.id,portfolioId:x.portfolio_id,portfolioName:portfolios.find(v=>v.id===x.portfolio_id)?.name||'Portfolio',agencyId:x.buyer_agency_id,agencyName:agencies.find(v=>v.id===x.buyer_agency_id)?.name||'Agency',winningEmployeeId:x.winning_employee_id||undefined,winningEmployeeName:x.winning_employee_id?names.get(x.winning_employee_id)||'Employee':undefined,salePrice:Number(x.sale_price),acquisitionCost:Number(x.acquisition_cost||0),commissionTotal:Number(x.commission_total||0),netRevenue:Number(x.net_revenue||0),paidAt:x.paid_at||undefined,closedAt:x.closed_at,paymentMethod:x.payment_method||undefined})));setCommissions((c.data||[]).map((x:any)=>({id:x.id,saleId:x.sale_id,employeeId:x.employee_id,employeeName:names.get(x.employee_id)||'Employee',amount:Number(x.amount),status:x.status,calculationType:x.calculation_type||'flat',rate:x.rate==null?undefined:Number(x.rate),approvedAt:x.approved_at||undefined,paidAt:x.paid_at||undefined,createdAt:x.created_at})));}catch(e){setError(e instanceof Error?e.message:'Unable to load closing data.')}finally{setLoading(false)}},[profile,portfolios,agencies]);
 useEffect(()=>{refresh()},[refresh]);
 async function uploadProof(reservationId:string,file?:File){if(!file||!profile)return null;const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${profile.company_id}/${reservationId}/${Date.now()}-${safe}`;const {error}=await supabase.storage.from('closing-proofs').upload(path,file,{contentType:file.type||'application/octet-stream'});if(error)throw error;return path;}
 const recordDeposit:Store['recordDeposit']=async(id,input)=>{const proof=await uploadProof(id,input.proof);const employee=profile?.role==='employee';const {error:e}=employee?await supabase.rpc('dmh_employee_record_deposit',{p_reservation_id:id,p_amount:input.amount,p_payment_method:input.paymentMethod,p_received_at:input.receivedAt,p_proof_storage_path:proof,p_notes:input.notes||null}):await supabase.rpc('dmh_record_deposit',{p_reservation_id:id,p_amount:input.amount,p_payment_method:input.paymentMethod,p_received_at:input.receivedAt,p_proof_storage_path:proof,p_notes:input.notes||null});if(e)throw e;await Promise.all([refresh(),refreshPortfolios()]);};
 const closeSale:Store['closeSale']=async(id,input)=>{const proof=await uploadProof(id,input.proof);const employee=profile?.role==='employee';const {error:e}=employee?await supabase.rpc('dmh_employee_close_sale',{p_reservation_id:id,p_balance_amount:input.balanceAmount,p_payment_method:input.paymentMethod,p_paid_at:input.paidAt,p_proof_storage_path:proof,p_notes:input.notes||null}):await supabase.rpc('dmh_close_sale',{p_reservation_id:id,p_balance_amount:input.balanceAmount,p_payment_method:input.paymentMethod,p_paid_at:input.paidAt,p_winning_employee_id:input.winningEmployeeId||null,p_commission_type:input.commissionType,p_commission_value:input.commissionValue,p_proof_storage_path:proof,p_notes:input.notes||null});if(e)throw e;await Promise.all([refresh(),refreshPortfolios()]);};
 const releaseReservation:Store['releaseReservation']=async(id,reason)=>{const {error:e}=await supabase.rpc('dmh_release_reservation',{p_reservation_id:id,p_reason:reason});if(e)throw e;await Promise.all([refresh(),refreshPortfolios()]);};
 const setCommissionStatus:Store['setCommissionStatus']=async(id,status)=>{const {error:e}=await supabase.rpc('dmh_set_commission_status',{p_commission_id:id,p_status:status});if(e)throw e;await refresh();};
 const value=useMemo(()=>({reservations,sales,commissions,employees,loading,error,refresh,recordDeposit,closeSale,releaseReservation,setCommissionStatus}),[reservations,sales,commissions,employees,loading,error,refresh]);return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useClosingStore(){const x=useContext(Context);if(!x)throw new Error('ClosingProvider missing');return x}
