import {createContext,useCallback,useContext,useEffect,useMemo,useState,type ReactNode} from 'react';
import {supabase} from '../lib/supabase';import {usePortfolioStore} from './PortfolioStore';
export type InterventionPriority='low'|'normal'|'high'|'critical';export type InterventionStatus='open'|'in_progress'|'waiting_on_buyer'|'waiting_on_owner'|'completed'|'cancelled';
export type DealIntervention={id:string;companyId:string;opportunityId:string;createdBy?:string;createdByName?:string;assignedTo?:string;assignedToName?:string;action:string;notes?:string;riskScore:number;riskLevel:string;priority:InterventionPriority;status:InterventionStatus;dueAt?:string;completedAt?:string;outcome?:string;createdAt:string;updatedAt:string};
type CreateInput={opportunityId:string;action:string;notes?:string;riskScore:number;riskLevel:string;assignedTo?:string;dueAt?:string;priority?:InterventionPriority;status?:InterventionStatus};
type Store={items:DealIntervention[];loading:boolean;refresh:()=>Promise<void>;create:(input:CreateInput)=>Promise<void>;update:(id:string,patch:Partial<Pick<DealIntervention,'assignedTo'|'dueAt'|'priority'|'status'|'outcome'|'notes'>>)=>Promise<void>};
const C=createContext<Store|null>(null);const map=(r:any):DealIntervention=>({id:r.id,companyId:r.company_id,opportunityId:r.opportunity_id,createdBy:r.created_by||undefined,createdByName:r.created_by_name||undefined,assignedTo:r.assigned_to||undefined,assignedToName:r.assigned_to_name||undefined,action:r.action,notes:r.notes||undefined,riskScore:Number(r.risk_score||0),riskLevel:r.risk_level,priority:r.priority,status:r.status,dueAt:r.due_at||undefined,completedAt:r.completed_at||undefined,outcome:r.outcome||undefined,createdAt:r.created_at,updatedAt:r.updated_at||r.created_at});
export function ExecutionProvider({children}:{children:ReactNode}){const {profile}=usePortfolioStore();const [items,setItems]=useState<DealIntervention[]>([]);const [loading,setLoading]=useState(true);const refresh=useCallback(async()=>{if(!profile){setLoading(false);return}setLoading(true);const {data,error}=await supabase.from('deal_interventions').select('*').eq('company_id',profile.company_id).order('due_at',{ascending:true,nullsFirst:false});if(error){console.error(error);setItems([])}else setItems((data||[]).map(map));setLoading(false)},[profile]);useEffect(()=>{void refresh()},[refresh]);const create=async(input:CreateInput)=>{if(!profile)throw new Error('Profile is not ready.');const {error}=await supabase.from('deal_interventions').insert({company_id:profile.company_id,opportunity_id:input.opportunityId,created_by:profile.id,assigned_to:input.assignedTo||profile.id,action:input.action,notes:input.notes||null,risk_score:input.riskScore,risk_level:input.riskLevel,priority:input.priority||'normal',status:input.status||'open',due_at:input.dueAt||null});if(error)throw error;await refresh()};const update=async(id:string,patch:any)=>{const payload:any={};if('assignedTo'in patch)payload.assigned_to=patch.assignedTo||null;if('dueAt'in patch)payload.due_at=patch.dueAt||null;if('priority'in patch)payload.priority=patch.priority;if('status'in patch)payload.status=patch.status;if('outcome'in patch)payload.outcome=patch.outcome||null;if('notes'in patch)payload.notes=patch.notes||null;const {error}=await supabase.from('deal_interventions').update(payload).eq('id',id);if(error)throw error;await refresh()};const value=useMemo(()=>({items,loading,refresh,create,update}),[items,loading,refresh]);return <C.Provider value={value}>{children}</C.Provider>}
export function useExecutionStore(){const x=useContext(C);if(!x)throw new Error('ExecutionProvider missing');return x}
