import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import { supabase } from '../lib/supabase';
import { usePortfolioStore } from './PortfolioStore';
import { useAgencyStore } from './AgencyStore';

export type OfferStatus='submitted'|'owner_countered'|'buyer_countered'|'accepted'|'rejected'|'expired'|'reserved'|'closed';
export interface OfferRound{ id:string; roundNumber:number; actorRole:'buyer'|'employee'|'owner'; action:'offer'|'counter'|'accept'|'reject'|'request_info'; amount?:number; terms?:string; message?:string; createdAt:string; createdBy?:string; }
export interface Offer{ id:string; portfolioId:string; portfolioName:string; agencyId:string; agencyName:string; contactId?:string; employeeId:string; employeeName:string; status:OfferStatus; currentAmount:number; paymentTerms:string; conditions:string; employeeRecommendation:string; createdAt:string; updatedAt:string; expiresAt?:string; rounds:OfferRound[]; }
interface Store{offers:Offer[];loading:boolean;error:string;refresh:()=>Promise<void>;submitOffer:(input:{agencyId:string;contactId?:string;amount:number;paymentTerms:string;conditions:string;recommendation:string;expiresAt?:string})=>Promise<void>;addRound:(offerId:string,input:{actorRole:'buyer'|'employee'|'owner';action:'offer'|'counter'|'accept'|'reject'|'request_info';amount?:number;terms?:string;message?:string})=>Promise<void>;reserve:(offerId:string,input:{paymentDeadline:string;depositRequired:number;reservationExpiresAt:string})=>Promise<void>;}
const Context=createContext<Store|null>(null);
export function NegotiationProvider({children}:{children:ReactNode}){
 const {profile,portfolios,refresh:refreshPortfolios}=usePortfolioStore(); const {agencies}=useAgencyStore();
 const [offers,setOffers]=useState<Offer[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const refresh=useCallback(async()=>{if(!profile){setOffers([]);setLoading(false);return}setLoading(true);setError('');try{const [o,r,p]=await Promise.all([supabase.from('offers').select('*').eq('company_id',profile.company_id).order('created_at',{ascending:false}),supabase.from('offer_rounds').select('*').eq('company_id',profile.company_id).order('round_number',{ascending:true}),supabase.from('profiles').select('id,full_name').eq('company_id',profile.company_id)]);if(o.error)throw o.error;if(r.error)throw r.error;if(p.error)throw p.error;const names=new Map<string,string>((p.data||[]).map((x:any)=>[String(x.id),String(x.full_name)]));setOffers((o.data||[]).map((x:any)=>({id:x.id,portfolioId:x.portfolio_id,portfolioName:portfolios.find(v=>v.id===x.portfolio_id)?.name||'Portfolio',agencyId:x.agency_id,agencyName:agencies.find(v=>v.id===x.agency_id)?.name||'Agency',contactId:x.contact_id||undefined,employeeId:x.employee_id,employeeName:names.get(x.employee_id)||'Employee',status:x.status,currentAmount:Number(x.current_amount),paymentTerms:x.payment_terms||'',conditions:x.conditions||'',employeeRecommendation:x.employee_recommendation||'',createdAt:x.created_at,updatedAt:x.updated_at,expiresAt:x.expires_at||undefined,rounds:(r.data||[]).filter((y:any)=>y.offer_id===x.id).map((y:any)=>({id:y.id,roundNumber:y.round_number,actorRole:y.actor_role,action:y.action,amount:y.amount==null?undefined:Number(y.amount),terms:y.terms||'',message:y.message||'',createdAt:y.created_at,createdBy:y.created_by||undefined}))})))}catch(e){setError(e instanceof Error?e.message:'Unable to load negotiations.')}finally{setLoading(false)}},[profile,portfolios,agencies]);
 useEffect(()=>{refresh()},[refresh]);
 const submitOffer:Store['submitOffer']=async input=>{if(!profile)throw new Error('Profile not ready.');const active=portfolios.find(p=>['active','negotiating'].includes(p.status));if(!active)throw new Error('No active portfolio is available.');const {data,error:e}=await supabase.from('offers').insert({company_id:profile.company_id,portfolio_id:active.id,agency_id:input.agencyId,contact_id:input.contactId||null,employee_id:profile.id,status:'submitted',current_amount:input.amount,payment_terms:input.paymentTerms||null,conditions:input.conditions||null,employee_recommendation:input.recommendation||null,expires_at:input.expiresAt||null}).select('id').single();if(e)throw e;const {error:r}=await supabase.from('offer_rounds').insert({company_id:profile.company_id,offer_id:data.id,round_number:1,actor_role:'buyer',action:'offer',amount:input.amount,terms:input.paymentTerms||null,message:input.conditions||null,created_by:profile.id});if(r)throw r;await supabase.from('portfolios').update({status:'negotiating'}).eq('id',active.id).eq('status','active');await Promise.all([refresh(),refreshPortfolios()]);};
 const addRound:Store['addRound']=async(offerId,input)=>{if(!profile)throw new Error('Profile not ready.');const offer=offers.find(o=>o.id===offerId);if(!offer)throw new Error('Offer not found.');const lastRound=offer.rounds.length?offer.rounds[offer.rounds.length-1]:undefined;const roundNumber=(lastRound?.roundNumber||0)+1;const {error:r}=await supabase.from('offer_rounds').insert({company_id:profile.company_id,offer_id:offerId,round_number:roundNumber,actor_role:input.actorRole,action:input.action,amount:input.amount??null,terms:input.terms||null,message:input.message||null,created_by:profile.id});if(r)throw r;let status:OfferStatus=offer.status;if(input.action==='counter')status=input.actorRole==='buyer'?'buyer_countered':'owner_countered';if(input.action==='accept')status='accepted';if(input.action==='reject')status='rejected';const patch:any={status,updated_at:new Date().toISOString()};if(input.amount!=null)patch.current_amount=input.amount;if(input.terms)patch.payment_terms=input.terms;if(['accept','reject'].includes(input.action))patch.decision_at=new Date().toISOString();const {error:e}=await supabase.from('offers').update(patch).eq('id',offerId);if(e)throw e;await refresh();};
 const reserve:Store['reserve']=async(offerId,input)=>{const {error:e}=await supabase.rpc('dmh_create_reservation',{p_offer_id:offerId,p_payment_deadline:input.paymentDeadline,p_deposit_required:input.depositRequired,p_reservation_expires_at:input.reservationExpiresAt||input.paymentDeadline});if(e)throw e;await Promise.all([refresh(),refreshPortfolios()]);};
 const value=useMemo(()=>({offers,loading,error,refresh,submitOffer,addRound,reserve}),[offers,loading,error,refresh]);return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useNegotiationStore(){const x=useContext(Context);if(!x)throw new Error('NegotiationProvider missing');return x}
