import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import { supabase } from '../lib/supabase';
import { usePortfolioStore } from './PortfolioStore';
export interface EmailTemplate{id:string;name:string;subject:string;body:string;active:boolean;allowedRoles:string[];createdAt:string}
export interface OutreachMessage{id:string;agencyId:string;contactId?:string;employeeId:string;portfolioId?:string;templateId?:string;recipient:string;subject:string;body:string;status:string;provider?:string;createdAt:string;sentAt?:string;deliveredAt?:string;openedAt?:string;clickedAt?:string;repliedAt?:string;bouncedAt?:string;errorMessage?:string}
type TemplateInput={name:string;subject:string;body:string;active:boolean;allowedRoles?:string[]};
type SendInput={agencyId:string;contactId?:string;portfolioId?:string;templateId?:string;recipient:string;subject:string;body:string;followUpAt?:string};
type Store={templates:EmailTemplate[];messages:OutreachMessage[];loading:boolean;error:string;refresh:()=>Promise<void>;addTemplate:(i:TemplateInput)=>Promise<void>;updateTemplate:(id:string,i:TemplateInput)=>Promise<void>;toggleTemplate:(id:string)=>Promise<void>;archiveTemplate:(id:string)=>Promise<void>;queueAndSendEmail:(i:SendInput)=>Promise<void>};
const Context=createContext<Store|null>(null);
const mapTemplate=(r:any):EmailTemplate=>({id:r.id,name:r.name,subject:r.subject,body:r.body,active:Boolean(r.active??r.is_active),allowedRoles:Array.isArray(r.allowed_roles)?r.allowed_roles:['employee','owner'],createdAt:r.created_at});
const mapMessage=(r:any):OutreachMessage=>({id:r.id,agencyId:r.agency_id,contactId:r.contact_id||undefined,employeeId:r.employee_id,portfolioId:r.portfolio_id||undefined,templateId:r.template_id||undefined,recipient:r.recipient,subject:r.subject||'',body:r.body||'',status:r.status,provider:r.provider||undefined,createdAt:r.created_at,sentAt:r.sent_at||undefined,deliveredAt:r.delivered_at||undefined,openedAt:r.opened_at||undefined,clickedAt:r.clicked_at||undefined,repliedAt:r.replied_at||undefined,bouncedAt:r.bounced_at||undefined,errorMessage:r.error_message||undefined});
export function OutreachProvider({children}:{children:ReactNode}){const {profile}=usePortfolioStore();const [templates,setTemplates]=useState<EmailTemplate[]>([]);const [messages,setMessages]=useState<OutreachMessage[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const refresh=useCallback(async()=>{if(!profile){setTemplates([]);setMessages([]);setLoading(false);return}setLoading(true);setError('');const [t,m]=await Promise.all([supabase.from('email_templates').select('*').eq('company_id',profile.company_id).is('archived_at',null).order('created_at'),supabase.from('outreach_messages').select('*').eq('company_id',profile.company_id).order('created_at',{ascending:false}).limit(250)]);if(t.error)setError(t.error.message);else setTemplates((t.data||[]).map(mapTemplate));if(m.error&&m.error.code!=='42P01')setError(m.error.message);else setMessages((m.data||[]).map(mapMessage));setLoading(false)},[profile]);useEffect(()=>{void refresh()},[refresh]);
 const addTemplate=async(i:TemplateInput)=>{if(!profile)throw new Error('Profile is not ready.');const {error:e}=await supabase.from('email_templates').insert({company_id:profile.company_id,name:i.name.trim(),subject:i.subject.trim(),body:i.body,active:i.active,allowed_roles:i.allowedRoles||['employee','owner'],created_by:profile.id});if(e)throw e;await refresh()};
 const updateTemplate=async(id:string,i:TemplateInput)=>{const {error:e}=await supabase.from('email_templates').update({name:i.name.trim(),subject:i.subject.trim(),body:i.body,active:i.active,allowed_roles:i.allowedRoles||['employee','owner'],updated_at:new Date().toISOString()}).eq('id',id);if(e)throw e;await refresh()};
 const toggleTemplate=async(id:string)=>{const t=templates.find(x=>x.id===id);if(!t)return;const {error:e}=await supabase.from('email_templates').update({active:!t.active,updated_at:new Date().toISOString()}).eq('id',id);if(e)throw e;await refresh()};
 const archiveTemplate=async(id:string)=>{const {error:e}=await supabase.from('email_templates').update({active:false,archived_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id);if(e)throw e;await refresh()};
 const queueAndSendEmail=async(i:SendInput)=>{const {data,error:e}=await supabase.rpc('dmh_queue_outreach_email',{p_agency_id:i.agencyId,p_contact_id:i.contactId||null,p_portfolio_id:i.portfolioId||null,p_template_id:i.templateId||null,p_recipient:i.recipient,p_subject:i.subject,p_body:i.body,p_follow_up_at:i.followUpAt||null});if(e)throw e;const {data:fn,error:fnError}=await supabase.functions.invoke('send-outreach-email',{body:{messageId:data}});if(fnError)throw fnError;if(fn?.ok===false)throw new Error(fn.error||'Email could not be sent.');await refresh()};
 const value=useMemo<Store>(()=>({templates,messages,loading,error,refresh,addTemplate,updateTemplate,toggleTemplate,archiveTemplate,queueAndSendEmail}),[templates,messages,loading,error,refresh]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useOutreachStore(){const x=useContext(Context);if(!x)throw new Error('OutreachProvider missing');return x}
