import {createContext,useCallback,useContext,useEffect,useMemo,useState,type ReactNode} from 'react';
import {supabase} from '../lib/supabase';
import {usePortfolioStore} from './PortfolioStore';

export type LeaderboardEmployee={id:string;full_name:string;is_active:boolean;rank:number;sales_month:number;revenue_month:number;sales_lifetime:number;revenue_lifetime:number;avg_sale_price:number;commission_month:number;commission_lifetime:number;commission_pending:number;outreach_count:number;emails:number;calls:number;offers_created:number;won:number;open_deals:number;pipeline_value:number;closing_rate:number};
export type PerformanceSettings={employee_rank_visible:boolean;public_leaderboard_visible:boolean};
export type LeaderboardSummary={monthRevenue:number;monthCommissions:number;filesSold:number;pipelineValue:number;activeEmployees:number};
export type EmployeePerformanceDashboard={employeeName:string;rank:number|null;publicLeaderboardVisible:boolean;commissionEarnedMonth:number;potentialCommission:number;commissionPaidLifetime:number;filesSoldMonth:number;revenueMonth:number;averageSalePrice:number;pipelineValue:number;openDeals:number;offersCreated:number;closingRate:number;outreachCount:number;emails:number;calls:number};
type Store={employees:LeaderboardEmployee[];settings:PerformanceSettings;summary:LeaderboardSummary;employeeDashboard:EmployeePerformanceDashboard|null;loading:boolean;error:string;refresh:()=>Promise<void>;saveSettings:(rankVisible:boolean,publicVisible:boolean)=>Promise<void>};
const zeroSummary={monthRevenue:0,monthCommissions:0,filesSold:0,pipelineValue:0,activeEmployees:0};
const C=createContext<Store|null>(null);const num=(v:any)=>Number(v||0);
export function PerformanceProvider({children}:{children:ReactNode}){const {profile}=usePortfolioStore();const [employees,setEmployees]=useState<LeaderboardEmployee[]>([]);const [settings,setSettings]=useState<PerformanceSettings>({employee_rank_visible:true,public_leaderboard_visible:false});const [summary,setSummary]=useState<LeaderboardSummary>(zeroSummary);const [employeeDashboard,setEmployeeDashboard]=useState<EmployeePerformanceDashboard|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
const refresh=useCallback(async()=>{if(!profile)return;setLoading(true);setError('');const fn=profile.role==='owner'?'dmh_owner_employee_leaderboard':'dmh_employee_performance_dashboard';const {data,error}=await supabase.rpc(fn);if(error)setError(error.message);else if(profile.role==='owner'){const raw:any=data||{};setSettings({employee_rank_visible:raw.settings?.employee_rank_visible!==false,public_leaderboard_visible:Boolean(raw.settings?.public_leaderboard_visible)});setSummary({monthRevenue:num(raw.summary?.monthRevenue),monthCommissions:num(raw.summary?.monthCommissions),filesSold:num(raw.summary?.filesSold),pipelineValue:num(raw.summary?.pipelineValue),activeEmployees:num(raw.summary?.activeEmployees)});setEmployees((raw.employees||[]).map((e:any)=>({...e,rank:num(e.rank),sales_month:num(e.sales_month),revenue_month:num(e.revenue_month),sales_lifetime:num(e.sales_lifetime),revenue_lifetime:num(e.revenue_lifetime),avg_sale_price:num(e.avg_sale_price),commission_month:num(e.commission_month),commission_lifetime:num(e.commission_lifetime),commission_pending:num(e.commission_pending),outreach_count:num(e.outreach_count),emails:num(e.emails),calls:num(e.calls),offers_created:num(e.offers_created),won:num(e.won),open_deals:num(e.open_deals),pipeline_value:num(e.pipeline_value),closing_rate:num(e.closing_rate)})))}else{const r:any=data||{};setEmployeeDashboard({employeeName:r.employeeName||profile.full_name,rank:r.rank==null?null:num(r.rank),publicLeaderboardVisible:Boolean(r.publicLeaderboardVisible),commissionEarnedMonth:num(r.commissionEarnedMonth),potentialCommission:num(r.potentialCommission),commissionPaidLifetime:num(r.commissionPaidLifetime),filesSoldMonth:num(r.filesSoldMonth),revenueMonth:num(r.revenueMonth),averageSalePrice:num(r.averageSalePrice),pipelineValue:num(r.pipelineValue),openDeals:num(r.openDeals),offersCreated:num(r.offersCreated),closingRate:num(r.closingRate),outreachCount:num(r.outreachCount),emails:num(r.emails),calls:num(r.calls)})}setLoading(false)},[profile]);useEffect(()=>{refresh()},[refresh]);
const saveSettings=async(rankVisible:boolean,publicVisible:boolean)=>{const {error}=await supabase.rpc('dmh_set_performance_settings',{p_employee_rank_visible:rankVisible,p_public_leaderboard_visible:publicVisible});if(error)throw error;await refresh()};
const value=useMemo(()=>({employees,settings,summary,employeeDashboard,loading,error,refresh,saveSettings}),[employees,settings,summary,employeeDashboard,loading,error,refresh]);return <C.Provider value={value}>{children}</C.Provider>}
export function usePerformanceStore(){const x=useContext(C);if(!x)throw new Error('PerformanceProvider missing');return x}
