import {createContext,useCallback,useContext,useEffect,useMemo,useState,type ReactNode} from 'react';
import {supabase} from '../lib/supabase';
import {usePortfolioStore} from './PortfolioStore';
export const PIPELINE_STAGES=['new','researching','first_contact','conversation_started','decision_maker_found','portfolio_requested','portfolio_sent','negotiating','verbal_agreement','contracts','closed_won','closed_lost'] as const;
export type PipelineStage=typeof PIPELINE_STAGES[number];
export type Opportunity={id:string;agencyId:string;portfolioId?:string;ownerId?:string;title:string;stage:PipelineStage;askingPrice:number;probability:number;expectedCloseDate?:string;closedAmount?:number;lostReason?:string;createdAt:string;updatedAt:string};
type Store={opportunities:Opportunity[];loading:boolean;refresh:()=>Promise<void>;moveAgency:(agencyId:string,stage:PipelineStage)=>Promise<void>;saveOpportunity:(input:Partial<Opportunity>&{agencyId:string;title:string})=>Promise<void>;removeOpportunity:(id:string)=>Promise<void>};
const C=createContext<Store|null>(null);
const map=(r:any):Opportunity=>({id:r.id,agencyId:r.agency_id,portfolioId:r.portfolio_id||undefined,ownerId:r.owner_id||undefined,title:r.title,stage:r.stage,askingPrice:Number(r.asking_price||0),probability:Number(r.probability||0),expectedCloseDate:r.expected_close_date||undefined,closedAmount:r.closed_amount==null?undefined:Number(r.closed_amount),lostReason:r.lost_reason||undefined,createdAt:r.created_at,updatedAt:r.updated_at});
export function PipelineProvider({children}:{children:ReactNode}){const {profile}=usePortfolioStore();const [opportunities,setOpportunities]=useState<Opportunity[]>([]);const [loading,setLoading]=useState(true);const refresh=useCallback(async()=>{if(!profile){setLoading(false);return}setLoading(true);const {data,error}=await supabase.from('sales_opportunities').select('*').eq('company_id',profile.company_id).order('updated_at',{ascending:false});if(error){console.error(error);setOpportunities([])}else setOpportunities((data||[]).map(map));setLoading(false)},[profile]);useEffect(()=>{refresh()},[refresh]);const moveAgency=async(agencyId:string,stage:PipelineStage)=>{const {error}=await supabase.rpc('dmh_move_pipeline_stage',{p_agency_id:agencyId,p_stage:stage});if(error)throw error;await refresh()};const saveOpportunity=async(input:Partial<Opportunity>&{agencyId:string;title:string})=>{if(!profile)throw new Error('Profile is not ready.');const payload={company_id:profile.company_id,agency_id:input.agencyId,portfolio_id:input.portfolioId||null,owner_id:input.ownerId||profile.id,title:input.title,stage:input.stage||'new',asking_price:input.askingPrice||0,probability:input.probability??10,expected_close_date:input.expectedCloseDate||null,closed_amount:input.closedAmount??null,lost_reason:input.lostReason||null,updated_at:new Date().toISOString()};const q=input.id?supabase.from('sales_opportunities').update(payload).eq('id',input.id):supabase.from('sales_opportunities').insert(payload);const {error}=await q;if(error)throw error;await refresh()};const removeOpportunity=async(id:string)=>{const {error}=await supabase.from('sales_opportunities').delete().eq('id',id);if(error)throw error;await refresh()};const value=useMemo(()=>({opportunities,loading,refresh,moveAgency,saveOpportunity,removeOpportunity}),[opportunities,loading,refresh]);return <C.Provider value={value}>{children}</C.Provider>}
export function usePipelineStore(){const x=useContext(C);if(!x)throw new Error('PipelineProvider missing');return x}
