import {createContext,useCallback,useContext,useMemo,useState,type ReactNode} from 'react';
import {supabase} from '../lib/supabase';
import {usePortfolioStore} from './PortfolioStore';import {usePipelineStore} from './PipelineStore';import {useNegotiationStore} from './NegotiationStore';import {useClosingStore} from './ClosingStore';import {useApprovalStore} from './ApprovalStore';import {useConversationStore} from './ConversationStore';import {useAgencyStore} from './AgencyStore';import {useTransactionAutomation} from './TransactionAutomationStore';import {useExecutionStore} from './ExecutionStore';import {assessDealRisk} from '../engines/dealRisk';
export type RecoveryRun={created:number;escalated:number;skipped:number};
type Store={running:boolean;lastRun?:RecoveryRun;run:()=>Promise<RecoveryRun>};const C=createContext<Store|null>(null);
export function RecoveryProvider({children}:{children:ReactNode}){const {profile}=usePortfolioStore();const pipeline=usePipelineStore(),negotiation=useNegotiationStore(),closing=useClosingStore(),approval=useApprovalStore(),conversation=useConversationStore(),agency=useAgencyStore(),automation=useTransactionAutomation(),execution=useExecutionStore();const [running,setRunning]=useState(false);const [lastRun,setLastRun]=useState<RecoveryRun>();
 const run=useCallback(async()=>{if(!profile)throw new Error('Profile is not ready.');setRunning(true);let created=0,skipped=0;try{for(const opportunity of pipeline.opportunities.filter(o=>!['closed_won','closed_lost'].includes(o.stage))){const offer=negotiation.offers.find(x=>x.agencyId===opportunity.agencyId&&(!opportunity.portfolioId||x.portfolioId===opportunity.portfolioId));const reservation=closing.reservations.find(x=>x.agencyId===opportunity.agencyId&&(!opportunity.portfolioId||x.portfolioId===opportunity.portfolioId));const assessment=assessDealRisk({opportunity,offer,reservation,approvals:approval.requests.filter(x=>x.agencyId===opportunity.agencyId||x.dealId===opportunity.id),conversation:conversation.conversations.find(x=>x.opportunityId===opportunity.id||x.agencyId===opportunity.agencyId),agency:agency.agencies.find(x=>x.id===opportunity.agencyId),alerts:automation.alerts});if(!['critical','at_risk'].includes(assessment.level)){skipped++;continue}const trigger=assessment.signals[0]?.id||'risk';const key=`${opportunity.id}:${trigger}:${opportunity.stage}`;if(execution.items.some(x=>(x as any).automationKey===key||(!['completed','cancelled'].includes(x.status)&&x.opportunityId===opportunity.id&&x.action===assessment.recommendedAction))){skipped++;continue}const due=new Date(Date.now()+(assessment.level==='critical'?4:24)*3600000).toISOString();const {error}=await supabase.from('deal_interventions').insert({company_id:profile.company_id,opportunity_id:opportunity.id,created_by:profile.id,assigned_to:opportunity.ownerId||profile.id,action:assessment.recommendedAction,notes:assessment.signals[0]?.detail||'Automatically created from deal risk.',risk_score:assessment.score,risk_level:assessment.level,priority:assessment.level==='critical'?'critical':'high',status:'open',due_at:due,automation_key:key,trigger_type:trigger,automated:true,protected_revenue:assessment.revenueAtRisk});if(error){if(error.code==='23505')skipped++;else throw error}else created++}
 const {data,error}=await supabase.rpc('dmh_escalate_overdue_interventions');if(error)throw error;const escalated=Number((data as any)?.escalated||0);await execution.refresh();const result={created,escalated,skipped};setLastRun(result);return result}finally{setRunning(false)}},[profile,pipeline.opportunities,negotiation.offers,closing.reservations,approval.requests,conversation.conversations,agency.agencies,automation.alerts,execution]);
 const value=useMemo(()=>({running,lastRun,run}),[running,lastRun,run]);return <C.Provider value={value}>{children}</C.Provider>}
export function useRecoveryStore(){const x=useContext(C);if(!x)throw new Error('RecoveryProvider missing');return x}
