import {createContext,useCallback,useContext,useEffect,useMemo,useState,type ReactNode} from 'react';
import {supabase} from '../lib/supabase';
import {usePortfolioStore} from './PortfolioStore';
export type RevenueDashboard={lifetimeRevenue:number;monthRevenue:number;lifetimeProfit:number;monthProfit:number;pendingCommissions:number;paidCommissions:number;pendingPartnerDistributions:number;paidPartnerDistributions:number;unreconciledSales:number;reconciledSales:number};
export type RevenueSale={id:string;portfolio_id:string;buyer_agency_id:string;winning_employee_id?:string;sale_price:number;gross_revenue?:number;acquisition_cost:number;transaction_costs:number;net_profit?:number;revenue_status:string;closed_at:string};
export type Commission={id:string;sale_id:string;employee_id:string;amount:number;status:string;commission_type:string;rate?:number;notes?:string;created_at:string};
export type Partner={id:string;name:string;email?:string;default_split_type:string;default_rate:number;is_active:boolean};
export type Distribution={id:string;sale_id:string;partner_id:string;amount:number;status:string;distribution_type:string;rate?:number;notes?:string;created_at:string};
type Store={dashboard:RevenueDashboard;sales:RevenueSale[];commissions:Commission[];partners:Partner[];distributions:Distribution[];loading:boolean;error:string;refresh:()=>Promise<void>;reconcile:(id:string,cost:number,fees:number)=>Promise<void>;setCommissionStatus:(id:string,status:string,reference?:string,notes?:string)=>Promise<void>;setDistributionStatus:(id:string,status:string,reference?:string,notes?:string)=>Promise<void>;addPartner:(name:string,email:string,type:string,rate:number)=>Promise<void>;addDistribution:(saleId:string,partnerId:string,type:string,rate:number,amount:number)=>Promise<void>};
const empty={lifetimeRevenue:0,monthRevenue:0,lifetimeProfit:0,monthProfit:0,pendingCommissions:0,paidCommissions:0,pendingPartnerDistributions:0,paidPartnerDistributions:0,unreconciledSales:0,reconciledSales:0};
const C=createContext<Store|null>(null); const n=(v:any)=>Number(v||0);
export function RevenueProvider({children}:{children:ReactNode}){const {profile}=usePortfolioStore();const [dashboard,setDashboard]=useState<RevenueDashboard>(empty);const [sales,setSales]=useState<RevenueSale[]>([]);const [commissions,setCommissions]=useState<Commission[]>([]);const [partners,setPartners]=useState<Partner[]>([]);const [distributions,setDistributions]=useState<Distribution[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
const refresh=useCallback(async()=>{if(!profile)return;setLoading(true);setError('');const [d,s,c,p,x]=await Promise.all([supabase.rpc('dmh_revenue_dashboard'),supabase.from('sales').select('*').eq('company_id',profile.company_id).order('closed_at',{ascending:false}),supabase.from('commissions').select('*').eq('company_id',profile.company_id).order('created_at',{ascending:false}),supabase.from('partner_profiles').select('*').eq('company_id',profile.company_id).order('name'),supabase.from('partner_distributions').select('*').eq('company_id',profile.company_id).order('created_at',{ascending:false})]);const e=d.error||s.error||c.error||p.error||x.error;if(e)setError(e.message);else{const q:any=d.data||{};setDashboard({lifetimeRevenue:n(q.lifetimeRevenue),monthRevenue:n(q.monthRevenue),lifetimeProfit:n(q.lifetimeProfit),monthProfit:n(q.monthProfit),pendingCommissions:n(q.pendingCommissions),paidCommissions:n(q.paidCommissions),pendingPartnerDistributions:n(q.pendingPartnerDistributions),paidPartnerDistributions:n(q.paidPartnerDistributions),unreconciledSales:n(q.unreconciledSales),reconciledSales:n(q.reconciledSales)});setSales((s.data||[]).map((r:any)=>({...r,sale_price:n(r.sale_price),gross_revenue:r.gross_revenue==null?undefined:n(r.gross_revenue),acquisition_cost:n(r.acquisition_cost),transaction_costs:n(r.transaction_costs),net_profit:r.net_profit==null?undefined:n(r.net_profit)})));setCommissions((c.data||[]).map((r:any)=>({...r,amount:n(r.amount),rate:r.rate==null?undefined:n(r.rate)})));setPartners((p.data||[]).map((r:any)=>({...r,default_rate:n(r.default_rate)})));setDistributions((x.data||[]).map((r:any)=>({...r,amount:n(r.amount),rate:r.rate==null?undefined:n(r.rate)})))}setLoading(false)},[profile]);useEffect(()=>{refresh()},[refresh]);
const reconcile=async(id:string,cost:number,fees:number)=>{const {error}=await supabase.rpc('dmh_reconcile_sale',{p_sale_id:id,p_acquisition_cost:cost,p_transaction_costs:fees});if(error)throw error;await refresh()};
const setCommissionStatus=async(id:string,status:string,reference='',notes='')=>{const {error}=await supabase.rpc('dmh_set_commission_status',{p_commission_id:id,p_status:status,p_payment_reference:reference||null,p_notes:notes||null});if(error)throw error;await refresh()};
const setDistributionStatus=async(id:string,status:string,reference='',notes='')=>{const {error}=await supabase.rpc('dmh_set_partner_distribution_status',{p_distribution_id:id,p_status:status,p_payment_reference:reference||null,p_notes:notes||null});if(error)throw error;await refresh()};
const addPartner=async(name:string,email:string,type:string,rate:number)=>{if(!profile)throw new Error('Profile not ready');const {error}=await supabase.from('partner_profiles').insert({company_id:profile.company_id,name,email:email||null,default_split_type:type,default_rate:rate});if(error)throw error;await refresh()};
const addDistribution=async(saleId:string,partnerId:string,type:string,rate:number,amount:number)=>{if(!profile)throw new Error('Profile not ready');const sale=sales.find(s=>s.id===saleId);const base=type==='percent_profit'?sale?.net_profit:type==='percent_revenue'?sale?.sale_price:amount;const {error}=await supabase.from('partner_distributions').insert({company_id:profile.company_id,sale_id:saleId,partner_id:partnerId,distribution_type:type,rate:rate||null,base_amount:base||null,amount,status:'pending'});if(error)throw error;await refresh()};
const value=useMemo(()=>({dashboard,sales,commissions,partners,distributions,loading,error,refresh,reconcile,setCommissionStatus,setDistributionStatus,addPartner,addDistribution}),[dashboard,sales,commissions,partners,distributions,loading,error,refresh]);return <C.Provider value={value}>{children}</C.Provider>}
export function useRevenueStore(){const x=useContext(C);if(!x)throw new Error('RevenueProvider missing');return x}
