import {useRef,useState} from 'react';
import {Download,FileSpreadsheet,LockKeyhole,UploadCloud} from 'lucide-react';
import {Card,PrimaryButton,SecondaryButton} from '../Primitives';
import type {Portfolio,PortfolioFile} from '../../types/domain';
import {usePortfolioStore,type PortfolioFileType} from '../../store/PortfolioStore';

function FileBox({portfolio,file,type,title,detail}:{portfolio:Portfolio;file?:PortfolioFile;type:PortfolioFileType;title:string;detail:string}){
 const input=useRef<HTMLInputElement>(null);const {uploadPortfolioFile,getDownloadUrl}=usePortfolioStore();const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function upload(fileToUpload?:File){if(!fileToUpload)return;setBusy(true);setMessage('');try{await uploadPortfolioFile(portfolio.id,type,fileToUpload);setMessage(`${title} uploaded securely.`)}catch(e){setMessage(e instanceof Error?e.message:'Upload failed.')}finally{setBusy(false);if(input.current)input.current.value=''}}
 async function download(){setBusy(true);try{const url=await getDownloadUrl(portfolio.id,type);if(!url)throw new Error(`${title} is not uploaded.`);window.open(url,'_blank','noopener,noreferrer')}catch(e){setMessage(e instanceof Error?e.message:'Download failed.')}finally{setBusy(false)}}
 return <Card className={`p-5 ${type==='unmasked'?'border-amber-200 bg-amber-50/40':''}`}><div className="flex items-start gap-3">{type==='unmasked'?<LockKeyhole className="text-amber-700"/>:<FileSpreadsheet className="text-emerald-700"/>}<div className="min-w-0 flex-1"><p className="font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p><p className="mt-3 truncate text-sm font-medium">{file?.name||'Not uploaded'}</p></div></div>{message&&<p className="mt-3 text-xs font-medium text-blue-700">{message}</p>}<div className="mt-4 flex gap-2"><input ref={input} className="hidden" type="file" accept=".csv,text/csv" onChange={e=>void upload(e.target.files?.[0])}/><PrimaryButton type="button" disabled={busy} onClick={()=>input.current?.click()}><UploadCloud className="mr-2" size={16}/>{file?'Replace':'Upload'}</PrimaryButton><SecondaryButton type="button" disabled={busy||!file} onClick={()=>void download()}><Download className="mr-2" size={16}/>Download</SecondaryButton></div></Card>
}
export default function PortfolioFileControl({portfolio}:{portfolio:Portfolio}){return <div className="grid gap-4 md:grid-cols-2"><FileBox portfolio={portfolio} type="masked" file={portfolio.maskedFile} title="Masked buyer review file" detail="Employee-visible and available to the buyer only after the NDA is fully executed."/><FileBox portfolio={portfolio} type="unmasked" file={portfolio.unmaskedFile} title="Unmasked final portfolio" detail="Owner-only source file. It remains locked until the purchase agreement is executed, funds are confirmed, and the owner releases it."/></div>}
