import {useEffect,useState} from 'react';
import {CheckCircle2,Download,FileSpreadsheet,LockKeyhole} from 'lucide-react';
import {Card,PrimaryButton} from '../Primitives';
import {useBuyerPortalStore} from '../../store/BuyerPortalStore';

export default function SecureBuyerFilePanel({portfolioId,room}:{portfolioId:string;room:any}){
 const {getDocumentGate,downloadPortfolioFile}=useBuyerPortalStore();const [gate,setGate]=useState({nda_executed:false,purchase_agreement_executed:false});const [busy,setBusy]=useState<'masked'|'unmasked'|null>(null);const [message,setMessage]=useState('');
 useEffect(()=>{getDocumentGate(portfolioId).then(setGate).catch(()=>setGate({nda_executed:false,purchase_agreement_executed:false}))},[portfolioId,getDocumentGate]);
 async function download(type:'masked'|'unmasked'){setBusy(type);setMessage('');try{await downloadPortfolioFile(portfolioId,type);setMessage(`${type==='masked'?'Masked':'Final unmasked'} download authorized and logged.`)}catch(e){setMessage(e instanceof Error?e.message:'Download unavailable.')}finally{setBusy(null)}}
 const finalReady=gate.purchase_agreement_executed&&!!room?.payment_confirmed_at&&!!room?.final_file_released_at;
 return <Card className="p-6"><h2 className="font-semibold">Secure portfolio files</h2><p className="mt-2 text-sm text-slate-500">Each download is temporary, permission-checked, and recorded.</p>{message&&<p className="mt-4 rounded-xl bg-blue-50 p-3 text-xs font-medium text-blue-700">{message}</p>}<div className="mt-5 space-y-4"><div className="rounded-2xl border border-slate-200 p-4"><div className="flex gap-3"><FileSpreadsheet className="text-emerald-700"/><div className="flex-1"><p className="font-semibold">Masked review file</p><p className="mt-1 text-xs text-slate-500">{gate.nda_executed?'NDA fully executed. Download unlocked.':'Sign the NDA to unlock this file.'}</p></div>{gate.nda_executed?<CheckCircle2 className="text-emerald-600"/>:<LockKeyhole className="text-slate-400"/>}</div><PrimaryButton className="mt-4 w-full" disabled={!gate.nda_executed||busy!==null} onClick={()=>void download('masked')}><Download className="mr-2" size={16}/>{busy==='masked'?'Authorizing…':'Download masked file'}</PrimaryButton></div><div className="rounded-2xl border border-amber-200 bg-amber-50/40 p-4"><div className="flex gap-3"><LockKeyhole className="text-amber-700"/><div className="flex-1"><p className="font-semibold">Final unmasked portfolio</p><p className="mt-1 text-xs leading-5 text-slate-500">Requires the fully executed purchase agreement, owner-confirmed cleared funds, and owner release.</p></div>{finalReady?<CheckCircle2 className="text-emerald-600"/>:<LockKeyhole className="text-amber-600"/>}</div><PrimaryButton className="mt-4 w-full" disabled={!finalReady||busy!==null} onClick={()=>void download('unmasked')}><Download className="mr-2" size={16}/>{busy==='unmasked'?'Authorizing…':'Download final file'}</PrimaryButton></div></div></Card>
}
