import {useEffect,useMemo,useState} from 'react';
import {Inbox,MailCheck,Send,UserRoundCheck,Eye,Hand,RefreshCw,StickyNote,CheckCircle2,AlertTriangle,Crown,UserRound,ShieldCheck,Clock3,ArrowRightLeft,Handshake,ExternalLink,Plus} from 'lucide-react';
import {Card,PrimaryButton,SecondaryButton,inputClass,Pill} from '../components/Primitives';
import {useConversationStore} from '../store/ConversationStore';
import {useAgencyStore} from '../store/AgencyStore';
import {usePortfolioStore} from '../store/PortfolioStore';
import {usePipelineStore} from '../store/PipelineStore';
import {supabase} from '../lib/supabase';
import {useNavigate,useSearchParams} from 'react-router-dom';

const dateInput=(iso?:string)=>iso?new Date(new Date(iso).getTime()-new Date(iso).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
const followUpLabel=(iso?:string)=>{if(!iso)return 'No follow-up';const d=new Date(iso),days=Math.ceil((d.getTime()-Date.now())/86400000);if(days<0)return `${Math.abs(days)} day${Math.abs(days)===1?'':'s'} overdue`;if(days===0)return 'Due today';if(days===1)return 'Due tomorrow';return `Due in ${days} days`};
const statusLabel=(value:string)=>value.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());

export default function ConversationCenter(){
 const {profile}=usePortfolioStore();const owner=profile?.role==='owner';const {opportunities,refresh:refreshPipeline}=usePipelineStore();const navigate=useNavigate();const [params]=useSearchParams();
 const {conversations,messages,employees,tests,loading,error,ensure,setState,setWorkflow,markRead,sendReply,addInternalNote,sendTest}=useConversationStore();
 const {agencies}=useAgencyStore();
 const [selected,setSelected]=useState(''),[reply,setReply]=useState(''),[note,setNote]=useState(''),[mode,setMode]=useState<'reply'|'note'>('reply'),[testOpen,setTestOpen]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{const requested=params.get('conversation');if(requested&&conversations.some(c=>c.id===requested))setSelected(requested)},[params,conversations]);
 const current=conversations.find(c=>c.id===(selected||conversations[0]?.id));const agency=agencies.find(a=>a.id===current?.agencyId);
 const thread=useMemo(()=>messages.filter(m=>m.conversationId===current?.id),[messages,current?.id]);
 const unread=(id:string)=>messages.filter(m=>m.conversationId===id&&m.direction==='inbound'&&!m.isRead).length;
 const unanswered=current?.lastInboundAt&&(!current.lastOutboundAt||new Date(current.lastInboundAt)>new Date(current.lastOutboundAt));
 const assignedEmployee=employees.find(e=>e.id===current?.assignedEmployeeId);
 const controller=current?.ownerTakenOver?'Owner':assignedEmployee?.name||'Unassigned';
 const linkedDeal=current?(opportunities.find(o=>o.id===current.opportunityId)||opportunities.find(o=>o.agencyId===current.agencyId&&!['closed_won','closed_lost'].includes(o.stage))):undefined;
 const money=(n=0)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
 async function createDeal(){if(!current||!agency)return;try{const {data,error}=await supabase.rpc('dmh_create_deal_from_conversation',{p_conversation_id:current.id,p_title:`${agency.name} Opportunity`,p_portfolio_id:null,p_asking_price:0});if(error)throw error;await Promise.all([refreshPipeline(),setWorkflow(current.id,{status:'negotiating'})]);navigate(`/deals?deal=${data}`)}catch(e){setNotice(e instanceof Error?e.message:'Unable to create deal.')}}
 async function send(){if(!current||!agency||!reply.trim())return;const recipient=[...thread].reverse().find(m=>m.direction==='inbound')?.fromEmail||agency.generalEmail||agency.contacts[0]?.email;if(!recipient){setNotice('No buyer email is available.');return}try{await sendReply(current.id,agency.id,recipient,current.subject?.startsWith('Re:')?current.subject:`Re: ${current.subject||agency.name}`,reply);setReply('');setNotice('Reply sent from info@debtpaper.com.')}catch(e){setNotice(e instanceof Error?e.message:'Send failed.')}}
 async function saveNote(){if(!current||!note.trim())return;try{await addInternalNote(current.id,note);setNote('');setNotice('Internal note saved.')}catch(e){setNotice(e instanceof Error?e.message:'Note failed.')}}
 if(loading)return <div className="p-10">Loading conversations…</div>;
 return <div className="mx-auto max-w-7xl p-5 md:p-8 lg:p-10">
  <header className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-semibold text-blue-600">Deal-to-Conversation Integration · v1.7.1</p><h2 className="mt-1 text-3xl font-semibold">Company conversations</h2><p className="mt-2 text-slate-500">Clear assignment, control, messaging, follow-ups, and owner handoffs in one workspace.</p></div>{owner&&<PrimaryButton onClick={()=>setTestOpen(v=>!v)}><MailCheck className="mr-2" size={18}/>Send owner test</PrimaryButton>}</header>
  {error&&<div className="mb-4 rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}{testOpen&&owner&&<TestPanel tests={tests} onSend={sendTest}/>} 
  <div className="grid gap-6 lg:grid-cols-[.72fr_1.28fr]">
   <Card className="overflow-hidden"><div className="border-b p-5"><div className="flex items-center gap-2"><Inbox size={19}/><h3 className="font-semibold">Inbox</h3></div></div><div className="max-h-[760px] overflow-y-auto">{conversations.map(c=>{const a=agencies.find(x=>x.id===c.agencyId),n=unread(c.id),late=c.nextFollowUpAt&&new Date(c.nextFollowUpAt)<new Date(),employee=employees.find(e=>e.id===c.assignedEmployeeId);return <button key={c.id} onClick={()=>{setSelected(c.id);void markRead(c.id)}} className={`w-full border-b p-5 text-left hover:bg-slate-50 ${current?.id===c.id?'bg-blue-50/70':''}`}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{a?.name||'Agency'}</p><p className="mt-1 line-clamp-1 text-sm text-slate-500">{c.subject||'Company conversation'}</p></div>{n>0&&<span className="grid h-6 min-w-6 place-items-center rounded-full bg-blue-600 px-2 text-xs font-bold text-white">{n}</span>}</div><div className="mt-3 space-y-1 text-xs text-slate-500"><p><span className="font-semibold text-slate-700">Assigned:</span> {employee?.name||'Unassigned'}</p><p><span className="font-semibold text-slate-700">Controlled by:</span> {c.ownerTakenOver?'Owner':employee?.name||'Unassigned'}</p></div><div className="mt-3 flex flex-wrap gap-2"><Pill tone={c.status==='ready_for_owner'?'warning':'neutral'}>{statusLabel(c.status)}</Pill>{c.ownerTakenOver&&<Pill tone="blue">Owner managing</Pill>}{c.nextFollowUpAt&&<Pill tone={late?'warning':'neutral'}>{followUpLabel(c.nextFollowUpAt)}</Pill>}</div></button>})}{!conversations.length&&<div className="p-8 text-center text-sm text-slate-500">No conversation exists yet. Sending an agency email creates one.</div>}</div></Card>
   <Card className="min-h-[680px] p-6 md:p-8">{current&&agency?<>
    <div className="border-b pb-5"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><h3 className="text-xl font-semibold">{agency.name}</h3><p className="mt-1 text-sm text-slate-500">Shared mailbox · info@debtpaper.com</p>{unanswered&&<p className="mt-2 flex items-center gap-2 text-sm font-medium text-amber-700"><AlertTriangle size={15}/>Buyer reply is waiting for a response.</p>}</div>{!owner&&<PrimaryButton onClick={()=>setWorkflow(current.id,{status:'ready_for_owner'})}><UserRoundCheck className="mr-2" size={16}/>Ready for owner</PrimaryButton>}</div>
     <div className="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center gap-2"><ShieldCheck size={18} className="text-blue-600"/><h4 className="font-semibold">Conversation control</h4></div><div className="mt-4 grid gap-4 md:grid-cols-2"><div className="rounded-xl bg-white p-4 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Assigned to</p><div className="mt-2 flex items-center gap-2"><UserRound size={17}/><span className="font-semibold">{assignedEmployee?.name||'Unassigned'}</span></div></div><div className="rounded-xl bg-white p-4 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Current controller</p><div className="mt-2 flex items-center gap-2">{current.ownerTakenOver?<Crown size={17} className="text-blue-600"/>:<UserRound size={17}/>}<span className="font-semibold">{controller}</span></div></div></div>
      {owner&&<div className="mt-4 flex flex-col gap-3 md:flex-row md:items-center"><select className={`${inputClass} md:max-w-xs`} value={current.assignedEmployeeId||''} onChange={e=>setState(current.id,{assignedEmployeeId:e.target.value||undefined})}><option value="">Unassigned</option>{employees.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><div className="flex flex-wrap gap-2"><SecondaryButton onClick={()=>setState(current.id,{ownerJoined:!current.ownerJoined})}><Eye className="mr-2" size={16}/>{current.ownerJoined?'Leave thread':'Join conversation'}</SecondaryButton>{current.ownerTakenOver?<PrimaryButton onClick={()=>setState(current.id,{releaseOwnership:true})}><ArrowRightLeft className="mr-2" size={16}/>Return to employee</PrimaryButton>:<SecondaryButton onClick={()=>setState(current.id,{takeOwnership:true})}><Hand className="mr-2" size={16}/>Take ownership</SecondaryButton>}</div></div>}
     </div>
     <div className="mt-4 rounded-2xl border border-blue-100 bg-blue-50/70 p-4"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2 text-blue-700"><Handshake size={18}/><h4 className="font-semibold">Linked deal</h4></div>{linkedDeal?<div className="mt-3 grid gap-2 text-sm sm:grid-cols-3"><p><span className="text-slate-500">Stage:</span> <b>{statusLabel(linkedDeal.stage)}</b></p><p><span className="text-slate-500">Value:</span> <b>{money(linkedDeal.askingPrice)}</b></p><p><span className="text-slate-500">Close:</span> <b>{linkedDeal.expectedCloseDate||'Not set'}</b></p></div>:<p className="mt-2 text-sm text-slate-600">No active deal is linked to this buyer conversation.</p>}</div>{linkedDeal?<PrimaryButton onClick={()=>navigate(`/deals?deal=${linkedDeal.id}`)}><ExternalLink className="mr-2" size={16}/>Open deal</PrimaryButton>:<SecondaryButton onClick={createDeal}><Plus className="mr-2" size={16}/>Create linked deal</SecondaryButton>}</div></div>
    </div>
    <div className="mt-5 grid gap-3 md:grid-cols-3"><select className={inputClass} value={current.status} onChange={e=>setWorkflow(current.id,{status:e.target.value})}><option value="open">Open</option><option value="waiting_on_buyer">Waiting on buyer</option><option value="negotiating">Negotiating</option><option value="ready_for_owner">Ready for owner</option><option value="closing">Closing</option><option value="closed">Closed</option></select><select className={inputClass} value={current.priority} onChange={e=>setWorkflow(current.id,{priority:e.target.value})}><option value="low">Low priority</option><option value="normal">Normal priority</option><option value="high">High priority</option><option value="urgent">Urgent</option></select><div className="flex gap-2"><input className={inputClass} type="datetime-local" value={dateInput(current.nextFollowUpAt)} onChange={e=>setWorkflow(current.id,{nextFollowUpAt:e.target.value?new Date(e.target.value).toISOString():undefined,clearFollowUp:!e.target.value})}/>{current.nextFollowUpAt&&<button className="rounded-xl border px-3" title="Complete follow-up" onClick={()=>setWorkflow(current.id,{clearFollowUp:true})}><CheckCircle2 size={18}/></button>}</div></div>
    <div className="my-6 max-h-[410px] space-y-4 overflow-y-auto pr-2">{thread.length?thread.map(m=><div key={m.id} className={`flex ${m.direction==='outbound'?'justify-end':m.direction==='internal'?'justify-center':'justify-start'}`}><div className={`max-w-[84%] rounded-3xl px-5 py-4 shadow-sm ${m.direction==='outbound'?'bg-blue-600 text-white':m.direction==='internal'?'border border-amber-200 bg-amber-50 text-amber-950':'border border-slate-200 bg-white text-slate-800'}`}><div className="flex items-center gap-2 text-xs font-semibold opacity-75">{m.direction==='internal'?<StickyNote size={13}/>:m.direction==='outbound'?<Send size={13}/>:<Inbox size={13}/>}<span>{m.direction==='outbound'?'Data Market House':m.direction==='internal'?'Internal note · not emailed':m.fromEmail||'Buyer'}</span></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{m.body}</p><p className="mt-2 flex items-center gap-1 text-[11px] opacity-60"><Clock3 size={11}/>{new Date(m.createdAt).toLocaleString()}</p></div></div>):<div className="rounded-2xl border border-dashed p-8 text-center text-sm text-slate-500">No messages in this conversation yet.</div>}</div>
    <div className="border-t pt-5"><div className="mb-3 flex gap-2"><button onClick={()=>setMode('reply')} className={`rounded-xl px-4 py-2 text-sm font-semibold ${mode==='reply'?'bg-blue-600 text-white':'bg-slate-100'}`}><Send className="mr-2 inline" size={15}/>Buyer reply</button><button onClick={()=>setMode('note')} className={`rounded-xl px-4 py-2 text-sm font-semibold ${mode==='note'?'bg-amber-500 text-white':'bg-slate-100'}`}><StickyNote className="mr-2 inline" size={15}/>Internal note</button></div>{mode==='reply'?<><textarea className={`${inputClass} min-h-28`} value={reply} onChange={e=>setReply(e.target.value)} placeholder="Reply as Data Market House…"/><div className="mt-3 flex items-center justify-between gap-3"><p className="text-sm text-slate-500">Replies remain in this company-owned thread.</p><PrimaryButton onClick={send}><Send className="mr-2" size={17}/>Send reply</PrimaryButton></div></>:<><textarea className={`${inputClass} min-h-28 border-amber-200 bg-amber-50`} value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a private team note. Buyers never see this."/><div className="mt-3 flex items-center justify-between gap-3"><p className="text-sm text-amber-700">Internal notes stay inside DMH Sales OS.</p><SecondaryButton onClick={saveNote}><StickyNote className="mr-2" size={17}/>Save note</SecondaryButton></div></>}{notice&&<p className="mt-3 text-sm text-slate-600">{notice}</p>}</div>
   </>:<div className="grid min-h-[500px] place-items-center text-center text-slate-500"><div><RefreshCw className="mx-auto mb-3"/><p>Select a conversation to begin.</p>{agencies.length>0&&<SecondaryButton className="mt-4" onClick={async()=>{const id=await ensure(agencies[0].id);setSelected(id)}}>Create first conversation</SecondaryButton>}</div></div>}</Card>
  </div>
 </div>
}

function TestPanel({tests,onSend}:{tests:any[];onSend:(r:string,s:string,b:string)=>Promise<void>}){const [recipient,setRecipient]=useState(''),[subject,setSubject]=useState('DMH Sales OS email test'),[body,setBody]=useState('This is a live delivery test from Data Market House Sales OS.'),[working,setWorking]=useState(false),[message,setMessage]=useState('');return <Card className="mb-6 p-6"><h3 className="text-lg font-semibold">Owner-only email test</h3><p className="mt-1 text-sm text-slate-500">Uses the live provider but does not contact an agency or start suppression.</p><div className="mt-5 grid gap-3 md:grid-cols-3"><input className={inputClass} type="email" placeholder="Your test email" value={recipient} onChange={e=>setRecipient(e.target.value)}/><input className={inputClass} value={subject} onChange={e=>setSubject(e.target.value)}/><PrimaryButton disabled={working} onClick={async()=>{setWorking(true);try{await onSend(recipient,subject,body);setMessage('Test accepted by the email provider.')}catch(e){setMessage(e instanceof Error?e.message:'Test failed.')}finally{setWorking(false)}}}>Send live test</PrimaryButton><textarea className={`${inputClass} md:col-span-3`} value={body} onChange={e=>setBody(e.target.value)}/></div>{message&&<p className="mt-3 text-sm">{message}</p>}{tests[0]&&<div className="mt-4 rounded-2xl bg-slate-50 p-4 text-sm"><b>Latest:</b> {tests[0].recipient} · {tests[0].status} {tests[0].provider_message_id?`· ${tests[0].provider_message_id}`:''}</div>}</Card>}
