import { useCallback,useEffect,useMemo,useState } from 'react';
import { Link } from 'react-router-dom';
import { AlertTriangle,ArrowRight,CheckCircle2,DollarSign,Inbox,MessageSquareText,Tag } from 'lucide-react';
import { Card,Pill,PrimaryButton,inputClass } from '../components/Primitives';
import { supabase } from '../lib/supabase';
import { usePortfolioStore } from '../store/PortfolioStore';
import { useAgencyStore } from '../store/AgencyStore';

type Reply={id:string;campaign_id?:string;recipient_id?:string;conversation_id?:string;agency_id?:string;portfolio_id?:string;message_id?:string;category:string;summary?:string;requires_owner:boolean;action_status:string;assigned_employee_id?:string;created_at:string};
const categoryTone=(x:string)=>x==='offer'?'warning':x==='interested'?'success':x==='declined'?'danger':'blue';
export default function ReplyCommandCenter(){
 const {profile,portfolios}=usePortfolioStore();const {agencies}=useAgencyStore();const [rows,setRows]=useState<Reply[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [filter,setFilter]=useState('open');const [note,setNote]=useState<Record<string,string>>({});
 const refresh=useCallback(async()=>{if(!profile)return;setLoading(true);setError('');const q=supabase.from('campaign_reply_events').select('*').eq('company_id',profile.company_id).order('created_at',{ascending:false}).limit(300);const {data,error:e}=await q;if(e)setError(e.message);else setRows((data||[]) as Reply[]);setLoading(false)},[profile]);
 useEffect(()=>{void refresh()},[refresh]);
 const visible=useMemo(()=>rows.filter(r=>filter==='all'||(filter==='open'&&r.action_status!=='completed')||r.category===filter||r.action_status===filter),[rows,filter]);
 const count=(fn:(r:Reply)=>boolean)=>rows.filter(fn).length;
 const act=async(id:string,action:string)=>{const {error:e}=await supabase.rpc('dmh_action_campaign_reply',{p_reply_event_id:id,p_action:action,p_note:note[id]||null});if(e){setError(e.message);return}await refresh()};
 const cards=[['New replies',count(r=>r.action_status==='new'),Inbox],['Interested',count(r=>r.category==='interested'&&r.action_status!=='completed'),CheckCircle2],['Price requests',count(r=>r.category==='price_request'&&r.action_status!=='completed'),Tag],['Offers',count(r=>r.category==='offer'&&r.action_status!=='completed'),DollarSign],['Owner review',count(r=>r.action_status==='owner_review'),AlertTriangle]] as const;
 return <div className="mx-auto max-w-7xl p-5 md:p-8 lg:p-10"><header className="mb-8"><p className="text-sm font-semibold text-blue-600">Inbound campaign intelligence</p><h2 className="mt-1 text-3xl font-semibold">Reply Command Center</h2><p className="mt-2 text-slate-500">Turn buyer responses into one clear next action.</p></header>
 <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([label,value,Icon])=><Card key={label} className="p-5"><div className="flex items-center justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div><Icon className="text-blue-600"/></div></Card>)}</div>
 <Card className="mb-5 p-4"><div className="flex flex-wrap gap-2">{['open','offer','price_request','interested','owner_review','declined','all'].map(x=><button key={x} onClick={()=>setFilter(x)} className={`rounded-xl px-3 py-2 text-sm font-semibold ${filter===x?'bg-slate-950 text-white':'bg-slate-100 text-slate-600'}`}>{x.replaceAll('_',' ')}</button>)}</div></Card>
 {error&&<Card className="mb-5 border-red-200 p-4 text-red-700">{error}</Card>}
 <div className="space-y-4">{visible.map(r=>{const agency=agencies.find(a=>a.id===r.agency_id);const portfolio=portfolios.find(p=>p.id===r.portfolio_id);return <Card key={r.id} className="p-5 md:p-6"><div className="grid gap-5 xl:grid-cols-[1fr_300px]"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-semibold">{agency?.name||'Unmatched buyer reply'}</h3><Pill tone={categoryTone(r.category) as any}>{r.category.replaceAll('_',' ')}</Pill><Pill>{r.action_status.replaceAll('_',' ')}</Pill></div><p className="mt-2 text-sm text-slate-500">{portfolio?.name||'Portfolio not matched'} · {new Date(r.created_at).toLocaleString()}</p><p className="mt-4 rounded-2xl bg-slate-50 p-4 text-sm leading-6 text-slate-700">{r.summary||'Buyer replied. Open the conversation to review the full message.'}</p><div className="mt-4 flex flex-wrap gap-3">{r.conversation_id&&<Link className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600" to={`${profile?.role==='owner'?'/conversations':'/employee/conversations'}?conversation=${r.conversation_id}`}>Open conversation <ArrowRight size={16}/></Link>}</div></div><div><textarea className={`${inputClass} min-h-24`} placeholder="Action note or decline reason" value={note[r.id]||''} onChange={e=>setNote({...note,[r.id]:e.target.value})}/><div className="mt-3 grid gap-2"><PrimaryButton onClick={()=>void act(r.id,'mark_interested')}>Mark interested</PrimaryButton><button className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold" onClick={()=>void act(r.id,'record_offer')}>Record offer / negotiate</button><button className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold" onClick={()=>void act(r.id,'escalate_owner')}>Escalate to owner</button><button className="rounded-xl border border-red-200 px-4 py-2 text-sm font-semibold text-red-700" onClick={()=>void act(r.id,'mark_declined')}>Mark declined</button><button className="rounded-xl px-4 py-2 text-sm font-semibold text-slate-500" onClick={()=>void act(r.id,'complete')}>Complete action</button></div></div></div></Card>})}{!visible.length&&!loading&&<Card className="p-12 text-center text-slate-400"><MessageSquareText className="mx-auto mb-3"/>No replies in this queue.</Card>}</div></div>
}
