import {FormEvent,useEffect,useMemo,useState} from 'react';
import {ArrowLeft,CheckCircle2,Clock3,Download,FileText,FileWarning,Handshake,LockKeyhole,MessageSquare,ShieldCheck} from 'lucide-react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {Card,Field,Pill,PrimaryButton,SecondaryButton,inputClass} from '../../components/Primitives';
import {useBuyerPortalStore,type DealRoomSnapshot} from '../../store/BuyerPortalStore';
import {supabase} from '../../lib/supabase';
const money=(v:number|null)=>v==null?'Protected':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v);
export default function BuyerDealRoom(){const {id}=useParams();const navigate=useNavigate();const {buyer,portfolios,acknowledge,submitOffer,loadRoom,offerAction,sendMessage}=useBuyerPortalStore();const p=useMemo(()=>portfolios.find(x=>x.id===id),[portfolios,id]);const [room,setRoom]=useState<DealRoomSnapshot|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const reload=async()=>{if(id)setRoom(await loadRoom(id))};useEffect(()=>{reload().catch(()=>{})},[id]);if(!p)return <div className="p-8"><p>Portfolio access unavailable.</p><button onClick={()=>navigate('/buyer')}>Return</button></div>;
async function run(fn:()=>Promise<unknown>,ok:string){setBusy(true);try{await fn();await reload();setMessage(ok)}catch(e){setMessage(e instanceof Error?e.message:'Action failed')}finally{setBusy(false)}}
async function offer(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(()=>submitOffer(p!.id,Number(f.get('amount')),String(f.get('terms')||''),String(f.get('conditions')||'')),'Offer submitted securely.')}
async function counter(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(()=>offerAction(room!.offer.id,'counter',Number(f.get('amount')),String(f.get('message')||'')),'Counteroffer submitted.')}
async function msg(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const body=String(f.get('body')||'');if(!body)return;await run(()=>sendMessage(buyer!.id,p!.id,body,room?.offer?.id),'Message sent.');e.currentTarget.reset()}
async function downloadDocument(d:any){setBusy(true);try{const {data,error}=await supabase.rpc('dmh_log_deal_download',{p_document_id:d.id,p_user_agent:navigator.userAgent});if(error)throw error;const url=String(data||d.external_url||'');if(!url)throw new Error('No download URL is attached to this file.');window.open(url,'_blank','noopener,noreferrer');await reload();setMessage('Secure download recorded.')}catch(e){setMessage(e instanceof Error?e.message:'Download unavailable')}finally{setBusy(false)}}
const r=room?.room,o=room?.offer;return <div className="p-5 lg:p-8"><div className="mx-auto max-w-7xl"><Link to="/buyer" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft size={16}/>Marketplace</Link><div className="mt-5 flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold tracking-[.2em] text-blue-600">SECURE DEAL ROOM</p><h1 className="mt-2 text-3xl font-semibold">{p.name}</h1><p className="mt-2 text-sm text-slate-500">{p.accountCount.toLocaleString()} accounts · {p.category||'Debt portfolio'}</p></div><Pill tone={r?.status==='closed'?'success':'blue'}>{r?.status?.replaceAll('_',' ')||'Authorized access'}</Pill></div>{message&&<p className="mt-5 rounded-2xl bg-blue-50 p-4 text-sm text-blue-700">{message}</p>}
<div className="mt-7 grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><div className="space-y-6"><Card className="p-6"><h2 className="font-semibold">Deal progress</h2><div className="mt-5 grid gap-3 sm:grid-cols-6">{[['Disclosure',p.disclosureSigned],['Offer accepted',!!o?.accepted_at],['Agreement',!!r?.agreement_approved_at],['Payment',!!r?.payment_confirmed_at],['Final files',!!r?.final_file_released_at],['Completed',!!r?.closed_at]].map(([x,done]:any)=><div className={`rounded-2xl p-3 text-xs font-semibold ${done?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`} key={x}>{done?<CheckCircle2 size={16}/>:<LockKeyhole size={16}/>}<p className="mt-2">{x}</p></div>)}</div>{r?.reservation_expires_at&&<p className="mt-4 flex items-center gap-2 text-sm text-amber-700"><Clock3 size={16}/>Reservation expires {new Date(r.reservation_expires_at).toLocaleString()}</p>}{r?.payment_confirmed_at&&<div className="mt-4 rounded-2xl bg-emerald-50 p-4 text-sm text-emerald-800"><p className="font-semibold">Payment verified by Data Market House</p><p className="mt-1">{r.payment_method||'Payment'}{r.payment_reference?` · Reference ${r.payment_reference}`:''}</p></div>}</Card>
<Card className="p-6"><h2 className="font-semibold">Offer timeline</h2><div className="mt-4 space-y-3">{(room?.rounds||[]).map((x:any)=><div key={x.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex justify-between"><p className="font-semibold capitalize">{x.actor_role} · {x.action}</p><p className="font-semibold">{money(x.amount)}</p></div>{x.message&&<p className="mt-2 text-sm text-slate-600">{x.message}</p>}</div>)}</div>{o&&o.status!=='accepted'&&<form className="mt-5 grid gap-3 sm:grid-cols-[1fr_1fr_auto]" onSubmit={counter}><input className={inputClass} name="amount" type="number" min="1" placeholder="Counter amount" required/><input className={inputClass} name="message" placeholder="Message"/><PrimaryButton disabled={busy}>Counter</PrimaryButton></form>}{o&&o.status!=='accepted'&&<div className="mt-3 flex gap-2"><PrimaryButton onClick={()=>run(()=>offerAction(o.id,'accept'), 'Offer accepted.')}>Accept current offer</PrimaryButton><SecondaryButton onClick={()=>run(()=>offerAction(o.id,'withdraw',undefined,'Buyer withdrew offer'),'Offer withdrawn.')}>Withdraw</SecondaryButton></div>}</Card>
<Card className="p-6"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><FileText className="text-blue-600"/><h2 className="font-semibold">Documents</h2></div><Link to={`/buyer/portfolio/${p.id}/documents`} className="text-sm font-semibold text-blue-600">Review & Sign</Link></div><div className="mt-4 space-y-3">{(room?.documents||[]).length===0?<p className="text-sm text-slate-500">Documents will appear here when released by the seller.</p>:(room?.documents||[]).map((d:any)=><div key={d.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-200 p-4"><div><p className="font-semibold">{d.title}</p><p className="mt-1 text-xs capitalize text-slate-500">{d.document_type.replaceAll('_',' ')} · {d.status}</p></div>{d.document_type==='final_portfolio'?<PrimaryButton onClick={()=>downloadDocument(d)} disabled={busy||!r?.final_file_released_at}><Download size={16}/>Download</PrimaryButton>:d.external_url?<a href={d.external_url} target="_blank" rel="noreferrer" className="text-sm font-semibold text-blue-600">Open</a>:null}</div>)}</div></Card>
<Card className="p-6"><div className="flex items-center gap-3"><MessageSquare className="text-blue-600"/><h2 className="font-semibold">Deal messages</h2></div><div className="mt-4 max-h-72 space-y-3 overflow-y-auto">{(room?.messages||[]).map((m:any)=><div key={m.id} className={`rounded-2xl p-3 text-sm ${m.sender_role==='buyer'?'ml-10 bg-blue-600 text-white':'mr-10 bg-slate-100'}`}><p>{m.body}</p><p className="mt-1 text-[10px] opacity-70">{new Date(m.created_at).toLocaleString()}</p></div>)}</div>{r&&<form className="mt-4 flex gap-2" onSubmit={msg}><input className={inputClass} name="body" placeholder="Message Data Market House"/><PrimaryButton disabled={busy}>Send</PrimaryButton></form>}</Card></div>
<div className="space-y-6"><Card className="p-6"><h2 className="font-semibold">Portfolio summary</h2><div className="mt-5 grid grid-cols-2 gap-4"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-400">Face value</p><p className="mt-1 text-xl font-semibold">{money(p.faceValue)}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-400">Asking price</p><p className="mt-1 text-xl font-semibold">{money(p.askingPrice)}</p></div></div><p className="mt-5 text-sm leading-6 text-slate-600">{p.description}</p></Card>
<Card className="p-6"><div className="flex gap-3"><FileWarning className="text-amber-600"/><div><h2 className="font-semibold">AS-IS Disclosure</h2><p className="mt-2 text-sm leading-6 text-slate-600">Buyer accepts independent review, compliance, licensing and collection responsibility.</p></div></div>{p.disclosureSigned?<div className="mt-5 flex items-center gap-2 rounded-2xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700"><ShieldCheck/>Acknowledgment recorded</div>:<PrimaryButton className="mt-5 w-full" onClick={()=>run(()=>acknowledge(p.id),'Disclosure acknowledged.')} disabled={busy}>Acknowledge and continue</PrimaryButton>}</Card>
{!o&&<Card className="p-6"><Handshake className="text-blue-600"/><h2 className="mt-4 text-xl font-semibold">Submit a secure offer</h2><form className="mt-6 space-y-4" onSubmit={offer}><Field label="Offer amount"><input className={inputClass} name="amount" type="number" min="1" step="0.01" required disabled={!p.disclosureSigned}/></Field><Field label="Payment terms"><input className={inputClass} name="terms" placeholder="Wire within 24 hours" disabled={!p.disclosureSigned}/></Field><Field label="Conditions"><textarea className={`${inputClass} min-h-28`} name="conditions" disabled={!p.disclosureSigned}/></Field><PrimaryButton className="w-full" disabled={busy||!p.disclosureSigned}>Submit offer</PrimaryButton></form></Card>}</div></div></div></div>}
