import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import App from './app/App';
import AuthGate from './app/AuthGate';
import ErrorBoundary from './app/ErrorBoundary';
import { PortfolioProvider } from './store/PortfolioStore';
import { AgencyProvider } from './store/AgencyStore';
import { OutreachProvider } from './store/OutreachStore';
import { DistributionProvider } from './store/DistributionStore';
import { NegotiationProvider } from './store/NegotiationStore';
import { ClosingProvider } from './store/ClosingStore';
import { PipelineProvider } from './store/PipelineStore';
import { ConversationProvider } from './store/ConversationStore';
import { MatchingProvider } from './store/MatchingStore';
import { CampaignProvider } from './store/CampaignStore';
import { AsIsReviewProvider } from './store/AsIsReviewStore';
import { ApprovalProvider } from './store/ApprovalStore';
import { RevenueProvider } from './store/RevenueStore';
import { PerformanceProvider } from './store/PerformanceStore';
import { BuyerPortalProvider } from './store/BuyerPortalStore';
import { AgreementProvider } from './store/AgreementStore';
import { TransactionAutomationProvider } from './store/TransactionAutomationStore';
import { ExecutionProvider } from './store/ExecutionStore';
import { RecoveryProvider } from './store/RecoveryStore';
import './styles/index.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><ErrorBoundary><BrowserRouter><AuthGate><PortfolioProvider><AgencyProvider><OutreachProvider><DistributionProvider><NegotiationProvider><ClosingProvider><PipelineProvider><ConversationProvider><MatchingProvider><CampaignProvider><AsIsReviewProvider><ApprovalProvider><RevenueProvider><PerformanceProvider><BuyerPortalProvider><AgreementProvider><TransactionAutomationProvider><ExecutionProvider><RecoveryProvider><App/></RecoveryProvider></ExecutionProvider></TransactionAutomationProvider></AgreementProvider></BuyerPortalProvider></PerformanceProvider></RevenueProvider></ApprovalProvider></AsIsReviewProvider></CampaignProvider></MatchingProvider></ConversationProvider></PipelineProvider></ClosingProvider></NegotiationProvider></DistributionProvider></OutreachProvider></AgencyProvider></PortfolioProvider></AuthGate></BrowserRouter></ErrorBoundary></React.StrictMode>);
