-- ============================================================
-- DMHOUSE Sales OS
-- Migration 071
-- Learning Engine / Practice Intelligence
--
-- Recovered from live production schema.
-- ============================================================


-- ============================================================
-- 1. MISSION-LEVEL LEARNING ACTIVITY
-- ============================================================

create table if not exists public.academy_learning_activity (

  employee_id uuid not null
    references public.profiles(id)
    on delete cascade,

  company_id uuid not null
    references public.companies(id)
    on delete cascade,

  academy_version integer not null
    default 1,

  mission_number integer not null
    check (
      mission_number >= 1
      and mission_number <= 5
    ),

  first_opened_at timestamptz,

  last_activity_at timestamptz,

  completed_at timestamptz,

  active_seconds integer not null
    default 0
    check (
      active_seconds >= 0
    ),

  view_count integer not null
    default 0
    check (
      view_count >= 0
    ),

  practice_attempt_count integer not null
    default 0
    check (
      practice_attempt_count >= 0
    ),

  first_practice_score numeric,

  best_practice_score numeric,

  latest_practice_score numeric,

  created_at timestamptz not null
    default now(),

  updated_at timestamptz not null
    default now(),

  primary key (
    employee_id,
    academy_version,
    mission_number
  )
);


create index if not exists
academy_learning_activity_company_idx
on public.academy_learning_activity(
  company_id,
  employee_id
);


-- ============================================================
-- 2. RAW LEARNING EVENTS
-- ============================================================

create table if not exists public.academy_learning_events (

  id bigint generated by default as identity
    primary key,

  employee_id uuid not null
    references public.profiles(id)
    on delete cascade,

  company_id uuid not null
    references public.companies(id)
    on delete cascade,

  academy_version integer not null
    default 1,

  mission_number integer
    check (
      mission_number is null
      or (
        mission_number >= 1
        and mission_number <= 5
      )
    ),

  event_type text not null
    check (
      event_type in (
        'academy_opened',
        'mission_opened',
        'heartbeat',
        'practice_submitted',
        'mission_completed',
        'academy_deadline_extended'
      )
    ),

  metadata jsonb not null
    default '{}'::jsonb,

  created_at timestamptz not null
    default now()
);


create index if not exists
academy_learning_events_company_idx
on public.academy_learning_events(
  company_id,
  created_at desc
);


create index if not exists
academy_learning_events_employee_idx
on public.academy_learning_events(
  employee_id,
  created_at
);


-- ============================================================
-- 3. ACTIVE STUDY SESSIONS
-- ============================================================

create table if not exists public.academy_learning_sessions (

  id uuid primary key
    default gen_random_uuid(),

  employee_id uuid not null
    references public.profiles(id)
    on delete cascade,

  company_id uuid not null
    references public.companies(id)
    on delete cascade,

  academy_version integer not null
    default 1,

  mission_number integer not null
    check (
      mission_number >= 1
      and mission_number <= 5
    ),

  status text not null
    default 'active'
    check (
      status in (
        'active',
        'ended',
        'abandoned'
      )
    ),

  started_at timestamptz not null
    default now(),

  last_heartbeat_at timestamptz not null
    default now(),

  ended_at timestamptz,

  active_seconds integer not null
    default 0
    check (
      active_seconds >= 0
    ),

  idle_seconds integer not null
    default 0
    check (
      idle_seconds >= 0
    ),

  hidden_seconds integer not null
    default 0
    check (
      hidden_seconds >= 0
    ),

  heartbeat_count integer not null
    default 0
    check (
      heartbeat_count >= 0
    ),

  exit_reason text,

  created_at timestamptz not null
    default now(),

  updated_at timestamptz not null
    default now()
);


create index if not exists
academy_learning_sessions_company_idx
on public.academy_learning_sessions(
  company_id,
  started_at desc
);


create index if not exists
academy_learning_sessions_employee_idx
on public.academy_learning_sessions(
  employee_id,
  started_at desc
);


create unique index if not exists
academy_learning_sessions_one_active_idx
on public.academy_learning_sessions(
  employee_id
)
where status = 'active';


-- ============================================================
-- 4. EVERY PRACTICE ATTEMPT
-- ============================================================

create table if not exists public.academy_practice_attempts (

  id bigint generated by default as identity
    primary key,

  employee_id uuid not null
    references public.profiles(id)
    on delete cascade,

  company_id uuid not null
    references public.companies(id)
    on delete cascade,

  academy_version integer not null
    default 1,

  mission_number integer not null
    check (
      mission_number >= 1
      and mission_number <= 5
    ),

  attempt_number integer not null
    check (
      attempt_number >= 1
    ),

  score numeric not null
    check (
      score >= 0
      and score <= 100
    ),

  question_count integer
    check (
      question_count is null
      or question_count > 0
    ),

  correct_count integer
    check (
      correct_count is null
      or correct_count >= 0
    ),

  passed boolean not null,

  started_at timestamptz,

  submitted_at timestamptz not null
    default now(),

  duration_seconds integer
    check (
      duration_seconds is null
      or duration_seconds >= 0
    ),

  verification_level text not null
    default 'client_reported'
    check (
      verification_level in (
        'client_reported',
        'server_verified'
      )
    ),

  created_at timestamptz not null
    default now(),

  unique (
    employee_id,
    academy_version,
    mission_number,
    attempt_number
  )
);


create index if not exists
academy_practice_attempts_company_idx
on public.academy_practice_attempts(
  company_id,
  created_at desc
);


create index if not exists
academy_practice_attempts_employee_idx
on public.academy_practice_attempts(
  employee_id,
  mission_number,
  attempt_number
);


-- ============================================================
-- 5. UPDATED-AT TRIGGER
-- ============================================================

create or replace function
public.dmh_learning_touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $function$
begin
  new.updated_at := now();
  return new;
end;
$function$;


drop trigger if exists
academy_learning_sessions_touch_updated_at
on public.academy_learning_sessions;


create trigger
academy_learning_sessions_touch_updated_at
before update
on public.academy_learning_sessions
for each row
execute function
public.dmh_learning_touch_updated_at();


-- ============================================================
-- 6. RLS
-- ============================================================

alter table public.academy_learning_activity
  enable row level security;

alter table public.academy_learning_events
  enable row level security;

alter table public.academy_learning_sessions
  enable row level security;

alter table public.academy_practice_attempts
  enable row level security;


drop policy if exists
"candidate reads own learning activity"
on public.academy_learning_activity;

create policy
"candidate reads own learning activity"
on public.academy_learning_activity
for select
to authenticated
using (
  employee_id = auth.uid()
);


drop policy if exists
"owner reads company learning activity"
on public.academy_learning_activity;

create policy
"owner reads company learning activity"
on public.academy_learning_activity
for select
to authenticated
using (
  company_id =
    public.current_company_id()

  and

  public.current_role()::text =
    'owner'
);


drop policy if exists
"candidate reads own learning events"
on public.academy_learning_events;

create policy
"candidate reads own learning events"
on public.academy_learning_events
for select
to authenticated
using (
  employee_id = auth.uid()
);


drop policy if exists
"owner reads company learning events"
on public.academy_learning_events;

create policy
"owner reads company learning events"
on public.academy_learning_events
for select
to authenticated
using (
  company_id =
    public.current_company_id()

  and

  public.current_role()::text =
    'owner'
);


drop policy if exists
"candidate reads own learning sessions"
on public.academy_learning_sessions;

create policy
"candidate reads own learning sessions"
on public.academy_learning_sessions
for select
to authenticated
using (
  employee_id = auth.uid()
);


drop policy if exists
"owner reads company learning sessions"
on public.academy_learning_sessions;

create policy
"owner reads company learning sessions"
on public.academy_learning_sessions
for select
to authenticated
using (
  company_id =
    public.current_company_id()

  and

  public.current_role()::text =
    'owner'
);


drop policy if exists
"candidate reads own practice attempts"
on public.academy_practice_attempts;

create policy
"candidate reads own practice attempts"
on public.academy_practice_attempts
for select
to authenticated
using (
  employee_id = auth.uid()
);


drop policy if exists
"owner reads company practice attempts"
on public.academy_practice_attempts;

create policy
"owner reads company practice attempts"
on public.academy_practice_attempts
for select
to authenticated
using (
  company_id =
    public.current_company_id()

  and

  public.current_role()::text =
    'owner'
);


grant select
on public.academy_learning_activity,
   public.academy_learning_events,
   public.academy_learning_sessions,
   public.academy_practice_attempts
to authenticated;


-- ============================================================
-- 7. START LEARNING SESSION
-- ============================================================

create or replace function
public.dmh_academy_start_learning_session(
  p_mission integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_profile public.profiles%rowtype;
  v_enrollment public.academy_enrollments%rowtype;
  v_session public.academy_learning_sessions%rowtype;
  v_now timestamptz :=
    clock_timestamp();
begin

  if p_mission < 1
     or p_mission > 5
  then
    raise exception
      'Learning sessions apply to Missions 1 through 5.';
  end if;


  select p.*
  into v_profile
  from public.profiles p
  where p.id = auth.uid()
    and p.is_active = true
    and p.role::text in (
      'academy',
      'employee'
    );

  if not found then
    raise exception
      'Academy identity required.';
  end if;


  select e.*
  into v_enrollment
  from public.academy_enrollments e
  where e.employee_id =
    auth.uid();

  if not found then
    raise exception
      'Academy enrollment not found.';
  end if;


  if v_profile.role::text = 'academy'
     and v_enrollment.learning_deadline_at
       is not null
     and v_now >
       v_enrollment.learning_deadline_at
  then

    raise exception
      'Academy learning window has expired. Owner extension is required.';

  end if;


  update public.academy_learning_sessions
  set
    status = 'abandoned',
    ended_at = v_now,

    exit_reason =
      coalesce(
        exit_reason,
        'new_session_started'
      ),

    updated_at = v_now

  where employee_id =
      auth.uid()
    and status = 'active';


  insert into public.academy_learning_sessions(
    employee_id,
    company_id,
    academy_version,
    mission_number,
    status,
    started_at,
    last_heartbeat_at
  )
  values(
    auth.uid(),
    v_profile.company_id,
    v_enrollment.academy_version,
    p_mission,
    'active',
    v_now,
    v_now
  )
  returning *
  into v_session;


  insert into public.academy_learning_activity(
    employee_id,
    company_id,
    academy_version,
    mission_number,
    first_opened_at,
    last_activity_at,
    view_count,
    created_at,
    updated_at
  )
  values(
    auth.uid(),
    v_profile.company_id,
    v_enrollment.academy_version,
    p_mission,
    v_now,
    v_now,
    1,
    v_now,
    v_now
  )

  on conflict(
    employee_id,
    academy_version,
    mission_number
  )

  do update
  set
    first_opened_at =
      coalesce(
        public.academy_learning_activity.first_opened_at,
        excluded.first_opened_at
      ),

    last_activity_at =
      excluded.last_activity_at,

    view_count =
      public.academy_learning_activity.view_count + 1,

    updated_at =
      excluded.updated_at;


  return jsonb_build_object(
    'sessionId',
    v_session.id,

    'missionNumber',
    v_session.mission_number,

    'startedAt',
    v_session.started_at,

    'status',
    v_session.status
  );

end;
$function$;


-- ============================================================
-- 8. LEARNING HEARTBEAT
-- ============================================================

create or replace function
public.dmh_academy_learning_heartbeat(
  p_session_id uuid,
  p_visible boolean,
  p_active boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_session public.academy_learning_sessions%rowtype;

  v_now timestamptz :=
    clock_timestamp();

  v_delta integer := 0;

  v_active_add integer := 0;

  v_idle_add integer := 0;

  v_hidden_add integer := 0;
begin

  select s.*
  into v_session
  from public.academy_learning_sessions s
  where s.id =
      p_session_id
    and s.employee_id =
      auth.uid()
  for update;


  if not found then
    raise exception
      'Learning session not found.';
  end if;


  if v_session.status <> 'active' then

    return jsonb_build_object(
      'sessionId',
      v_session.id,

      'status',
      v_session.status,

      'activeSeconds',
      v_session.active_seconds,

      'idleSeconds',
      v_session.idle_seconds,

      'hiddenSeconds',
      v_session.hidden_seconds
    );

  end if;


  v_delta :=
    least(
      60,

      greatest(
        0,

        floor(
          extract(
            epoch from (
              v_now
              - v_session.last_heartbeat_at
            )
          )
        )::integer
      )
    );


  if not coalesce(
    p_visible,
    false
  )
  then

    v_hidden_add :=
      v_delta;

  elsif coalesce(
    p_active,
    false
  )
  then

    v_active_add :=
      v_delta;

  else

    v_idle_add :=
      v_delta;

  end if;


  update public.academy_learning_sessions
  set
    active_seconds =
      active_seconds +
      v_active_add,

    idle_seconds =
      idle_seconds +
      v_idle_add,

    hidden_seconds =
      hidden_seconds +
      v_hidden_add,

    heartbeat_count =
      heartbeat_count + 1,

    last_heartbeat_at =
      v_now,

    updated_at =
      v_now

  where id =
    p_session_id

  returning *
  into v_session;


  if v_active_add > 0 then

    update public.academy_learning_activity
    set
      active_seconds =
        active_seconds +
        v_active_add,

      last_activity_at =
        v_now,

      updated_at =
        v_now

    where employee_id =
        auth.uid()

      and academy_version =
        v_session.academy_version

      and mission_number =
        v_session.mission_number;

  end if;


  return jsonb_build_object(
    'sessionId',
    v_session.id,

    'status',
    v_session.status,

    'activeSeconds',
    v_session.active_seconds,

    'idleSeconds',
    v_session.idle_seconds,

    'hiddenSeconds',
    v_session.hidden_seconds
  );

end;
$function$;


-- ============================================================
-- 9. END LEARNING SESSION
-- ============================================================

create or replace function
public.dmh_academy_end_learning_session(
  p_session_id uuid,
  p_reason text default 'mission_exit'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_session public.academy_learning_sessions%rowtype;

  v_now timestamptz :=
    clock_timestamp();
begin

  select s.*
  into v_session
  from public.academy_learning_sessions s
  where s.id =
      p_session_id
    and s.employee_id =
      auth.uid()
  for update;


  if not found then
    raise exception
      'Learning session not found.';
  end if;


  if v_session.status = 'active' then

    update public.academy_learning_sessions
    set
      status = 'ended',

      ended_at =
        v_now,

      exit_reason =
        nullif(
          btrim(
            coalesce(
              p_reason,
              ''
            )
          ),
          ''
        ),

      updated_at =
        v_now

    where id =
      p_session_id

    returning *
    into v_session;

  end if;


  return jsonb_build_object(
    'sessionId',
    v_session.id,

    'status',
    v_session.status,

    'startedAt',
    v_session.started_at,

    'endedAt',
    v_session.ended_at,

    'activeSeconds',
    v_session.active_seconds,

    'idleSeconds',
    v_session.idle_seconds,

    'hiddenSeconds',
    v_session.hidden_seconds
  );

end;
$function$;


-- ============================================================
-- 10. LEARNING STATE
-- ============================================================

create or replace function
public.dmh_academy_learning_state()
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_profile public.profiles%rowtype;

  v_enrollment public.academy_enrollments%rowtype;

  v_total_active integer;

  v_completed integer;

  v_average_score numeric;

  v_elapsed interval;

  v_pace text;

  v_remaining_seconds bigint;

  v_next_attempt_seconds bigint;
begin

  select p.*
  into v_profile
  from public.profiles p
  where p.id = auth.uid()
    and p.is_active = true;

  if not found then
    raise exception
      'Active DMHOUSE profile required.';
  end if;


  select e.*
  into v_enrollment
  from public.academy_enrollments e
  where e.employee_id =
    auth.uid();

  if not found then
    raise exception
      'Academy enrollment not found.';
  end if;


  select
    coalesce(
      sum(a.active_seconds),
      0
    ),

    count(*) filter (
      where a.completed_at
        is not null
    ),

    round(
      avg(
        a.best_practice_score
      ),
      2
    )

  into
    v_total_active,
    v_completed,
    v_average_score

  from public.academy_learning_activity a
  where a.employee_id =
    auth.uid()
    and a.academy_version =
      v_enrollment.academy_version;


  v_elapsed :=
    now()
    -
    v_enrollment.learning_started_at;


  if v_enrollment.learning_completed_at
       is not null
  then

    v_pace := 'completed';

  elsif now() >
        v_enrollment.learning_deadline_at
  then

    v_pace := 'expired';

  elsif now() >
        v_enrollment.learning_target_at
  then

    v_pace := 'late';

  elsif now() >
        v_enrollment.learning_started_at
        + interval '24 hours'
  then

    v_pace := 'on_track';

  else

    v_pace := 'excellent';

  end if;


  v_remaining_seconds :=
    greatest(
      0,
      floor(
        extract(
          epoch from (
            v_enrollment.learning_deadline_at
            - now()
          )
        )
      )::bigint
    );


  v_next_attempt_seconds :=
    case

      when v_enrollment.next_final_attempt_at
           is null
      then 0

      else greatest(
        0,
        floor(
          extract(
            epoch from (
              v_enrollment.next_final_attempt_at
              - now()
            )
          )
        )::bigint
      )

    end;


  return jsonb_build_object(

    'learningStartedAt',
    v_enrollment.learning_started_at,

    'learningTargetAt',
    v_enrollment.learning_target_at,

    'learningDeadlineAt',
    v_enrollment.learning_deadline_at,

    'learningCompletedAt',
    v_enrollment.learning_completed_at,

    'learningPace',
    v_pace,

    'secondsUntilExpiration',
    v_remaining_seconds,

    'missionsCompleted',
    v_completed,

    'missionsRequired',
    5,

    'activeLearningSeconds',
    v_total_active,

    'averagePracticeScore',
    v_average_score,

    'finalAttemptsUsed',
    v_enrollment.final_attempts_used,

    'finalAttemptLimit',
    v_enrollment.final_attempt_limit,

    'nextFinalAttemptAt',
    v_enrollment.next_final_attempt_at,

    'secondsUntilNextAttempt',
    v_next_attempt_seconds,

    'finalAssessmentStatus',
    v_enrollment.final_assessment_status
  );

end;
$function$;


-- ============================================================
-- 11. RECORD LEARNING ACTIVITY
-- ============================================================

create or replace function
public.dmh_academy_record_learning_activity(
  p_mission integer,
  p_event text,
  p_score numeric default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_profile public.profiles%rowtype;

  v_enrollment public.academy_enrollments%rowtype;

  v_activity public.academy_learning_activity%rowtype;

  v_increment integer := 0;

  v_now timestamptz :=
    clock_timestamp();
begin

  if p_mission < 1
     or p_mission > 5
  then
    raise exception
      'Learning analytics apply to Missions 1 through 5.';
  end if;


  if p_event not in (
    'open',
    'heartbeat',
    'practice',
    'complete'
  ) then
    raise exception
      'Unsupported Academy learning event.';
  end if;


  if p_score is not null
     and (
       p_score < 0
       or p_score > 100
     )
  then
    raise exception
      'Practice score must be between 0 and 100.';
  end if;


  select p.*
  into v_profile
  from public.profiles p
  where p.id = auth.uid()
    and p.role::text in (
      'academy',
      'employee'
    )
    and p.is_active = true;

  if not found then
    raise exception
      'Academy access required.';
  end if;


  select e.*
  into v_enrollment
  from public.academy_enrollments e
  where e.employee_id =
    auth.uid()
  for update;

  if not found then
    raise exception
      'Academy enrollment not found.';
  end if;


  if v_profile.role::text = 'academy'
     and v_now >
       v_enrollment.learning_deadline_at
  then

    raise exception
      'Academy learning window has expired. Owner extension is required.';

  end if;


  insert into public.academy_learning_activity(
    employee_id,
    company_id,
    academy_version,
    mission_number,
    first_opened_at,
    last_activity_at,
    view_count
  )
  values(
    auth.uid(),
    v_profile.company_id,
    v_enrollment.academy_version,
    p_mission,
    v_now,
    v_now,
    case
      when p_event = 'open'
        then 1
      else 0
    end
  )
  on conflict (
    employee_id,
    academy_version,
    mission_number
  )
  do nothing;


  select a.*
  into v_activity
  from public.academy_learning_activity a
  where a.employee_id =
      auth.uid()
    and a.academy_version =
      v_enrollment.academy_version
    and a.mission_number =
      p_mission
  for update;


  if p_event = 'heartbeat'
     and v_activity.last_activity_at
       is not null
  then

    v_increment :=
      least(
        60,
        greatest(
          0,
          floor(
            extract(
              epoch from (
                v_now
                - v_activity.last_activity_at
              )
            )
          )::integer
        )
      );

  end if;


  update public.academy_learning_activity
  set

    first_opened_at =
      coalesce(
        first_opened_at,
        v_now
      ),

    last_activity_at =
      v_now,

    active_seconds =
      active_seconds
      +
      case
        when p_event = 'heartbeat'
          then v_increment
        else 0
      end,

    view_count =
      view_count
      +
      case
        when p_event = 'open'
          then 1
        else 0
      end,

    practice_attempt_count =
      practice_attempt_count
      +
      case
        when p_event = 'practice'
          then 1
        else 0
      end,

    first_practice_score =
      case
        when p_event = 'practice'
             and first_practice_score
               is null
        then p_score
        else first_practice_score
      end,

    best_practice_score =
      case
        when p_event = 'practice'
        then greatest(
          coalesce(
            best_practice_score,
            0
          ),
          coalesce(
            p_score,
            0
          )
        )
        else best_practice_score
      end,

    latest_practice_score =
      case
        when p_event = 'practice'
          then p_score
        else latest_practice_score
      end,

    completed_at =
      case
        when p_event = 'complete'
        then coalesce(
          completed_at,
          v_now
        )
        else completed_at
      end,

    updated_at =
      v_now

  where employee_id =
      auth.uid()
    and academy_version =
      v_enrollment.academy_version
    and mission_number =
      p_mission;


  insert into public.academy_learning_events(
    employee_id,
    company_id,
    academy_version,
    mission_number,
    event_type,
    metadata
  )
  values(
    auth.uid(),
    v_profile.company_id,
    v_enrollment.academy_version,
    p_mission,

    case p_event
      when 'open'
        then 'mission_opened'
      when 'heartbeat'
        then 'heartbeat'
      when 'practice'
        then 'practice_submitted'
      else 'mission_completed'
    end,

    jsonb_build_object(
      'score',
      p_score,
      'active_seconds_added',
      v_increment
    )
  );


  if p_event = 'complete' then

    if (
      select count(*)
      from public.academy_learning_activity a
      where a.employee_id =
          auth.uid()
        and a.academy_version =
          v_enrollment.academy_version
        and a.completed_at
          is not null
    ) >= 5
    then

      update public.academy_enrollments
      set
        learning_completed_at =
          coalesce(
            learning_completed_at,
            v_now
          ),
        updated_at = now()
      where employee_id =
        auth.uid();

    end if;

  end if;


  return public.dmh_academy_learning_state();

end;
$function$;


-- ============================================================
-- 12. RECORD EVERY PRACTICE ATTEMPT
-- ============================================================

create or replace function
public.dmh_academy_record_practice_attempt(
  p_mission integer,
  p_score numeric,
  p_question_count integer,
  p_correct_count integer,
  p_passed boolean,
  p_started_at timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_profile public.profiles%rowtype;

  v_enrollment public.academy_enrollments%rowtype;

  v_attempt integer;

  v_now timestamptz :=
    clock_timestamp();

  v_duration integer;

  v_first_score numeric;

  v_best_score numeric;

  v_attempt_count bigint;
begin

  if p_mission < 1
     or p_mission > 5
  then
    raise exception
      'Practice attempts apply to Missions 1 through 5.';
  end if;


  if p_score < 0
     or p_score > 100
  then
    raise exception
      'Practice score must be between 0 and 100.';
  end if;


  if p_question_count <= 0 then
    raise exception
      'Question count must be greater than zero.';
  end if;


  if p_correct_count < 0
     or p_correct_count >
       p_question_count
  then
    raise exception
      'Correct count is invalid.';
  end if;


  select p.*
  into v_profile
  from public.profiles p
  where p.id =
      auth.uid()
    and p.is_active =
      true
    and p.role::text in (
      'academy',
      'employee'
    );

  if not found then
    raise exception
      'Academy identity required.';
  end if;


  select e.*
  into v_enrollment
  from public.academy_enrollments e
  where e.employee_id =
    auth.uid();

  if not found then
    raise exception
      'Academy enrollment not found.';
  end if;


  select
    coalesce(
      max(a.attempt_number),
      0
    ) + 1
  into v_attempt
  from public.academy_practice_attempts a
  where a.employee_id =
      auth.uid()

    and a.academy_version =
      v_enrollment.academy_version

    and a.mission_number =
      p_mission;


  v_duration :=
    case

      when p_started_at is null
      then null

      else greatest(
        0,

        floor(
          extract(
            epoch from (
              v_now -
              p_started_at
            )
          )
        )::integer
      )

    end;


  insert into public.academy_practice_attempts(
    employee_id,
    company_id,
    academy_version,
    mission_number,
    attempt_number,
    score,
    question_count,
    correct_count,
    passed,
    started_at,
    submitted_at,
    duration_seconds,
    verification_level
  )
  values(
    auth.uid(),
    v_profile.company_id,
    v_enrollment.academy_version,
    p_mission,
    v_attempt,
    p_score,
    p_question_count,
    p_correct_count,
    p_passed,
    p_started_at,
    v_now,
    v_duration,
    'client_reported'
  );


  insert into public.academy_learning_activity(
    employee_id,
    company_id,
    academy_version,
    mission_number,
    first_opened_at,
    last_activity_at,
    practice_attempt_count,
    first_practice_score,
    best_practice_score,
    latest_practice_score,
    created_at,
    updated_at
  )
  values(
    auth.uid(),
    v_profile.company_id,
    v_enrollment.academy_version,
    p_mission,
    v_now,
    v_now,
    1,
    p_score,
    p_score,
    p_score,
    v_now,
    v_now
  )

  on conflict(
    employee_id,
    academy_version,
    mission_number
  )

  do update
  set
    last_activity_at =
      excluded.last_activity_at,

    practice_attempt_count =
      public.academy_learning_activity.practice_attempt_count + 1,

    first_practice_score =
      coalesce(
        public.academy_learning_activity.first_practice_score,
        excluded.first_practice_score
      ),

    best_practice_score =
      greatest(
        coalesce(
          public.academy_learning_activity.best_practice_score,
          0
        ),
        excluded.best_practice_score
      ),

    latest_practice_score =
      excluded.latest_practice_score,

    updated_at =
      excluded.updated_at;


  select
    min(a.score)
      filter (
        where a.attempt_number = 1
      ),

    max(a.score),

    count(*)

  into
    v_first_score,
    v_best_score,
    v_attempt_count

  from public.academy_practice_attempts a

  where a.employee_id =
      auth.uid()

    and a.academy_version =
      v_enrollment.academy_version

    and a.mission_number =
      p_mission;


  return jsonb_build_object(
    'missionNumber',
    p_mission,

    'attemptNumber',
    v_attempt,

    'score',
    p_score,

    'passed',
    p_passed,

    'firstAttemptScore',
    v_first_score,

    'bestScore',
    v_best_score,

    'attemptCount',
    v_attempt_count
  );

end;
$function$;


-- ============================================================
-- 13. OWNER LEARNING ENGINE DOSSIER
-- ============================================================

create or replace function
public.dmh_owner_learning_engine_summary(
  p_employee_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_profile public.profiles%rowtype;

  v_sessions jsonb;

  v_missions jsonb;

  v_attempts jsonb;

  v_totals jsonb;
begin

  if public.current_role()::text <>
    'owner'
  then
    raise exception
      'Owner access required.';
  end if;


  select p.*
  into v_profile
  from public.profiles p
  where p.id =
      p_employee_id

    and p.company_id =
      public.current_company_id();


  if not found then
    raise exception
      'Candidate or employee not found.';
  end if;


  select jsonb_build_object(

    'sessionCount',
    count(*),

    'activeSeconds',
    coalesce(
      sum(s.active_seconds),
      0
    ),

    'idleSeconds',
    coalesce(
      sum(s.idle_seconds),
      0
    ),

    'hiddenSeconds',
    coalesce(
      sum(s.hidden_seconds),
      0
    ),

    'firstSessionAt',
    min(s.started_at),

    'lastSessionAt',
    max(
      coalesce(
        s.ended_at,
        s.last_heartbeat_at
      )
    )

  )
  into v_totals

  from public.academy_learning_sessions s

  where s.employee_id =
    p_employee_id;


  select coalesce(
    jsonb_agg(
      jsonb_build_object(

        'missionNumber',
        x.mission_number,

        'sessionCount',
        x.session_count,

        'activeSeconds',
        x.active_seconds,

        'idleSeconds',
        x.idle_seconds,

        'hiddenSeconds',
        x.hidden_seconds,

        'firstOpenedAt',
        x.first_opened_at,

        'lastActivityAt',
        x.last_activity_at

      )
      order by
        x.mission_number
    ),

    '[]'::jsonb
  )
  into v_missions

  from (

    select
      s.mission_number,

      count(*)
        as session_count,

      coalesce(
        sum(s.active_seconds),
        0
      )
        as active_seconds,

      coalesce(
        sum(s.idle_seconds),
        0
      )
        as idle_seconds,

      coalesce(
        sum(s.hidden_seconds),
        0
      )
        as hidden_seconds,

      min(s.started_at)
        as first_opened_at,

      max(
        coalesce(
          s.ended_at,
          s.last_heartbeat_at
        )
      )
        as last_activity_at

    from public.academy_learning_sessions s

    where s.employee_id =
      p_employee_id

    group by
      s.mission_number

  ) x;


  select coalesce(
    jsonb_agg(
      jsonb_build_object(

        'id',
        a.id,

        'missionNumber',
        a.mission_number,

        'attemptNumber',
        a.attempt_number,

        'score',
        a.score,

        'passed',
        a.passed,

        'questionCount',
        a.question_count,

        'correctCount',
        a.correct_count,

        'durationSeconds',
        a.duration_seconds,

        'verificationLevel',
        a.verification_level,

        'submittedAt',
        a.submitted_at

      )

      order by
        a.mission_number,
        a.attempt_number
    ),

    '[]'::jsonb
  )
  into v_attempts

  from public.academy_practice_attempts a

  where a.employee_id =
    p_employee_id;


  select coalesce(
    jsonb_agg(
      jsonb_build_object(

        'id',
        s.id,

        'missionNumber',
        s.mission_number,

        'status',
        s.status,

        'startedAt',
        s.started_at,

        'endedAt',
        s.ended_at,

        'activeSeconds',
        s.active_seconds,

        'idleSeconds',
        s.idle_seconds,

        'hiddenSeconds',
        s.hidden_seconds,

        'heartbeatCount',
        s.heartbeat_count,

        'exitReason',
        s.exit_reason

      )

      order by
        s.started_at desc
    ),

    '[]'::jsonb
  )
  into v_sessions

  from public.academy_learning_sessions s

  where s.employee_id =
    p_employee_id;


  return jsonb_build_object(
    'employeeId',
    p_employee_id,

    'totals',
    coalesce(
      v_totals,
      '{}'::jsonb
    ),

    'missions',
    coalesce(
      v_missions,
      '[]'::jsonb
    ),

    'practiceAttempts',
    coalesce(
      v_attempts,
      '[]'::jsonb
    ),

    'sessions',
    coalesce(
      v_sessions,
      '[]'::jsonb
    )
  );

end;
$function$;


-- ============================================================
-- 14. FUNCTION PERMISSIONS
-- ============================================================

revoke all on function
public.dmh_academy_start_learning_session(integer)
from public;

revoke all on function
public.dmh_academy_learning_heartbeat(uuid,boolean,boolean)
from public;

revoke all on function
public.dmh_academy_end_learning_session(uuid,text)
from public;

revoke all on function
public.dmh_academy_learning_state()
from public;

revoke all on function
public.dmh_academy_record_learning_activity(integer,text,numeric)
from public;

revoke all on function
public.dmh_academy_record_practice_attempt(
  integer,
  numeric,
  integer,
  integer,
  boolean,
  timestamptz
)
from public;

revoke all on function
public.dmh_owner_learning_engine_summary(uuid)
from public;


grant execute on function
public.dmh_academy_start_learning_session(integer)
to authenticated;

grant execute on function
public.dmh_academy_learning_heartbeat(uuid,boolean,boolean)
to authenticated;

grant execute on function
public.dmh_academy_end_learning_session(uuid,text)
to authenticated;

grant execute on function
public.dmh_academy_learning_state()
to authenticated;

grant execute on function
public.dmh_academy_record_learning_activity(integer,text,numeric)
to authenticated;

grant execute on function
public.dmh_academy_record_practice_attempt(
  integer,
  numeric,
  integer,
  integer,
  boolean,
  timestamptz
)
to authenticated;

grant execute on function
public.dmh_owner_learning_engine_summary(uuid)
to authenticated;


-- ============================================================
-- END MIGRATION 071
-- ============================================================
