-- ============================================================
-- DMHOUSE Sales OS
-- Migration 072
-- Employee Employment Control Engine
--
-- RECOVERED FROM LIVE PRODUCTION DATABASE
--
-- Owner-controlled employment lifecycle:
--
-- active
--   ↓
-- suspended
--   ↓
-- reinstated
--
-- active / suspended
--   ↓
-- terminated
--   ↓
-- rehire
--
-- Employment history is preserved permanently.
-- ============================================================


-- ============================================================
-- 1. CANONICAL EMPLOYMENT STATE
-- ============================================================

create table if not exists
public.employee_employment_state (

  employee_id uuid primary key
    references public.profiles(id)
    on delete cascade,

  company_id uuid not null
    references public.companies(id)
    on delete cascade,

  status text not null
    default 'active'
    check (
      status in (
        'active',
        'suspended',
        'terminated'
      )
    ),

  suspended_at timestamptz,

  suspended_by uuid,

  suspension_reason text,

  terminated_at timestamptz,

  terminated_by uuid,

  termination_reason text,

  rehired_at timestamptz,

  rehired_by uuid,

  rehire_reason text,

  created_at timestamptz not null
    default now(),

  updated_at timestamptz not null
    default now()
);


create index if not exists
employee_employment_state_company_idx
on public.employee_employment_state(
  company_id,
  status
);


-- ============================================================
-- 2. IMMUTABLE EMPLOYMENT EVENT HISTORY
-- ============================================================

create table if not exists
public.employee_employment_events (

  id bigint generated by default
    as identity
    primary key,

  employee_id uuid not null
    references public.profiles(id)
    on delete cascade,

  company_id uuid not null
    references public.companies(id)
    on delete cascade,

  actor_id uuid,

  event_type text not null
    check (
      event_type in (
        'employee.employment_created',
        'employee.suspended',
        'employee.reinstated',
        'employee.terminated',
        'employee.rehired'
      )
    ),

  reason text,

  metadata jsonb not null
    default '{}'::jsonb,

  created_at timestamptz not null
    default now()
);


create index if not exists
employee_employment_events_company_idx
on public.employee_employment_events(
  company_id,
  created_at desc
);


create index if not exists
employee_employment_events_employee_idx
on public.employee_employment_events(
  employee_id,
  created_at desc
);


-- ============================================================
-- 3. UPDATED-AT ENGINE
-- ============================================================

create or replace function
public.dmh_employment_touch_updated_at()
returns trigger
language plpgsql
set search_path to 'public'
as $function$
begin
  new.updated_at := now();
  return new;
end;
$function$;


drop trigger if exists
employee_employment_state_touch
on public.employee_employment_state;


create trigger
employee_employment_state_touch
before update
on public.employee_employment_state
for each row
execute function
public.dmh_employment_touch_updated_at();


-- ============================================================
-- 4. RLS
-- ============================================================

alter table
public.employee_employment_state
enable row level security;


alter table
public.employee_employment_events
enable row level security;


drop policy if exists
"employee reads own employment state"
on public.employee_employment_state;


create policy
"employee reads own employment state"
on public.employee_employment_state
for select
to authenticated
using (
  employee_id =
    auth.uid()
);


drop policy if exists
"owner reads company employment state"
on public.employee_employment_state;


create policy
"owner reads company employment state"
on public.employee_employment_state
for select
to authenticated
using (
  public.current_role()::text =
    'owner'

  and

  company_id =
    public.current_company_id()
);


drop policy if exists
"employee reads own employment history"
on public.employee_employment_events;


create policy
"employee reads own employment history"
on public.employee_employment_events
for select
to authenticated
using (
  employee_id =
    auth.uid()
);


drop policy if exists
"owner reads company employment events"
on public.employee_employment_events;


create policy
"owner reads company employment events"
on public.employee_employment_events
for select
to authenticated
using (
  public.current_role()::text =
    'owner'

  and

  company_id =
    public.current_company_id()
);


grant select
on public.employee_employment_state
to authenticated;


grant select
on public.employee_employment_events
to authenticated;


-- ============================================================
-- 5. OWNER → EMPLOYEE AUTHORIZATION GATE
-- ============================================================

create or replace function
public.dmh_assert_owner_employee(
  p_employee_id uuid
)
returns public.profiles
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_employee public.profiles%rowtype;
begin

  if public.current_role()::text <> 'owner' then
    raise exception
      'Owner access required.';
  end if;


  select p.*
  into v_employee
  from public.profiles p
  where p.id =
      p_employee_id

    and p.company_id =
      public.current_company_id()

    and p.role::text =
      'employee';


  if not found then
    raise exception
      'Employee not found.';
  end if;


  return v_employee;

end;
$function$;


-- ============================================================
-- 6. OWNER EMPLOYMENT ROSTER
-- ============================================================

create or replace function
public.dmh_owner_employment_roster()
returns table(
  employee_id uuid,
  employment_status text,
  suspended_at timestamptz,
  suspension_reason text,
  terminated_at timestamptz,
  termination_reason text,
  rehired_at timestamptz,
  rehire_reason text,
  updated_at timestamptz
)
language sql
security definer
set search_path to 'public'
as $function$

  select
    s.employee_id,

    s.status
      as employment_status,

    s.suspended_at,

    s.suspension_reason,

    s.terminated_at,

    s.termination_reason,

    s.rehired_at,

    s.rehire_reason,

    s.updated_at

  from public.employee_employment_state s

  where
    public.current_role()::text =
      'owner'

    and

    s.company_id =
      public.current_company_id()

  order by
    s.updated_at desc;

$function$;


-- ============================================================
-- 7. SUSPEND EMPLOYEE
-- ============================================================

create or replace function
public.dmh_owner_suspend_employee(
  p_employee_id uuid,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_employee public.profiles%rowtype;

  v_reason text :=
    nullif(
      btrim(
        coalesce(
          p_reason,
          ''
        )
      ),
      ''
    );

  v_current text;

  v_now timestamptz :=
    clock_timestamp();
begin

  v_employee :=
    public.dmh_assert_owner_employee(
      p_employee_id
    );


  if v_reason is null then
    raise exception
      'Suspension reason is required.';
  end if;


  select status
  into v_current
  from public.employee_employment_state
  where employee_id =
    p_employee_id
  for update;


  if v_current = 'terminated' then
    raise exception
      'Employee is terminated. Use Rehire instead.';
  end if;


  if v_current = 'suspended' then
    raise exception
      'Employee is already suspended.';
  end if;


  update public.employee_employment_state
  set
    status =
      'suspended',

    suspended_at =
      v_now,

    suspended_by =
      auth.uid(),

    suspension_reason =
      v_reason

  where employee_id =
    p_employee_id;


  update public.profiles
  set is_active = false
  where id =
    p_employee_id;


  insert into
  public.employee_employment_events(
    employee_id,
    company_id,
    actor_id,
    event_type,
    reason,
    metadata
  )
  values(
    p_employee_id,
    v_employee.company_id,
    auth.uid(),

    'employee.suspended',

    v_reason,

    jsonb_build_object(
      'previousStatus',
      v_current,

      'newStatus',
      'suspended'
    )
  );


  return jsonb_build_object(
    'employeeId',
    p_employee_id,

    'status',
    'suspended',

    'isActive',
    false,

    'suspendedAt',
    v_now
  );

end;
$function$;


-- ============================================================
-- 8. REINSTATE SUSPENDED EMPLOYEE
-- ============================================================

create or replace function
public.dmh_owner_reinstate_employee(
  p_employee_id uuid,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_employee public.profiles%rowtype;

  v_current text;

  v_reason text :=
    nullif(
      btrim(
        coalesce(
          p_reason,
          ''
        )
      ),
      ''
    );

  v_now timestamptz :=
    clock_timestamp();
begin

  v_employee :=
    public.dmh_assert_owner_employee(
      p_employee_id
    );


  select status
  into v_current
  from public.employee_employment_state
  where employee_id =
    p_employee_id
  for update;


  if v_current = 'terminated' then
    raise exception
      'Terminated employee requires Rehire.';
  end if;


  if v_current <> 'suspended' then
    raise exception
      'Only suspended employees can be reinstated.';
  end if;


  update public.employee_employment_state
  set
    status =
      'active',

    rehired_at =
      null,

    rehired_by =
      null,

    rehire_reason =
      null

  where employee_id =
    p_employee_id;


  update public.profiles
  set is_active = true
  where id =
    p_employee_id;


  insert into
  public.employee_employment_events(
    employee_id,
    company_id,
    actor_id,
    event_type,
    reason,
    metadata
  )
  values(
    p_employee_id,
    v_employee.company_id,
    auth.uid(),

    'employee.reinstated',

    coalesce(
      v_reason,
      'Suspension lifted by Owner.'
    ),

    jsonb_build_object(
      'previousStatus',
      'suspended',

      'newStatus',
      'active'
    )
  );


  return jsonb_build_object(
    'employeeId',
    p_employee_id,

    'status',
    'active',

    'isActive',
    true,

    'reinstatedAt',
    v_now
  );

end;
$function$;


-- ============================================================
-- 9. TERMINATE EMPLOYEE
-- ============================================================

create or replace function
public.dmh_owner_terminate_employee(
  p_employee_id uuid,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_employee public.profiles%rowtype;

  v_current text;

  v_reason text :=
    nullif(
      btrim(
        coalesce(
          p_reason,
          ''
        )
      ),
      ''
    );

  v_now timestamptz :=
    clock_timestamp();

  v_candidate_id uuid;

  v_cycle_id uuid;
begin

  v_employee :=
    public.dmh_assert_owner_employee(
      p_employee_id
    );


  if v_reason is null
     or length(v_reason) < 5
  then

    raise exception
      'A meaningful termination reason is required.';

  end if;


  select status
  into v_current
  from public.employee_employment_state
  where employee_id =
    p_employee_id
  for update;


  if v_current = 'terminated' then
    raise exception
      'Employee is already terminated.';
  end if;


  update public.employee_employment_state
  set
    status =
      'terminated',

    terminated_at =
      v_now,

    terminated_by =
      auth.uid(),

    termination_reason =
      v_reason

  where employee_id =
    p_employee_id;


  -- Sales OS access is revoked.

  update public.profiles
  set is_active = false
  where id =
    p_employee_id;


  insert into
  public.employee_employment_events(
    employee_id,
    company_id,
    actor_id,
    event_type,
    reason,
    metadata
  )
  values(
    p_employee_id,
    v_employee.company_id,
    auth.uid(),

    'employee.terminated',

    v_reason,

    jsonb_build_object(
      'previousStatus',
      v_current,

      'newStatus',
      'terminated',

      'salesOsAccess',
      'revoked'
    )
  );


  -- Mirror important termination event
  -- into Hiring OS history when the employee
  -- originated through Academy.

  select c.id
  into v_candidate_id
  from public.hiring_candidates c
  where c.user_id =
    p_employee_id;


  if v_candidate_id is not null then

    select cy.id
    into v_cycle_id
    from public.hiring_candidate_cycles cy
    where cy.candidate_id =
      v_candidate_id
    order by
      cy.created_at desc
    limit 1;


    insert into public.hiring_events(
      candidate_id,
      cycle_id,
      company_id,
      actor_id,
      event_type,
      source_type,
      source_key,
      metadata,
      created_at
    )
    values(
      v_candidate_id,

      v_cycle_id,

      v_employee.company_id,

      auth.uid(),

      'employee.terminated',

      'employee_employment_events',

      p_employee_id::text
      ||
      ':terminated:'
      ||
      extract(
        epoch from v_now
      )::bigint::text,

      jsonb_build_object(
        'reason',
        v_reason,

        'salesOsAccess',
        'revoked'
      ),

      v_now
    );

  end if;


  return jsonb_build_object(
    'employeeId',
    p_employee_id,

    'status',
    'terminated',

    'isActive',
    false,

    'terminatedAt',
    v_now
  );

end;
$function$;


-- ============================================================
-- 10. REHIRE TERMINATED EMPLOYEE
-- ============================================================

create or replace function
public.dmh_owner_rehire_employee(
  p_employee_id uuid,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_employee public.profiles%rowtype;

  v_current text;

  v_reason text :=
    nullif(
      btrim(
        coalesce(
          p_reason,
          ''
        )
      ),
      ''
    );

  v_now timestamptz :=
    clock_timestamp();
begin

  v_employee :=
    public.dmh_assert_owner_employee(
      p_employee_id
    );


  if v_reason is null then
    raise exception
      'Rehire reason is required.';
  end if;


  select status
  into v_current
  from public.employee_employment_state
  where employee_id =
    p_employee_id
  for update;


  if v_current <> 'terminated' then
    raise exception
      'Only terminated employees use the Rehire action.';
  end if;


  -- IMPORTANT:
  -- Employment state changes FIRST.
  --
  -- Migration 073's profile protection
  -- permits profile activation only after
  -- employment status is no longer terminated.

  update public.employee_employment_state
  set
    status =
      'active',

    rehired_at =
      v_now,

    rehired_by =
      auth.uid(),

    rehire_reason =
      v_reason

  where employee_id =
    p_employee_id;


  update public.profiles
  set is_active = true
  where id =
    p_employee_id;


  insert into
  public.employee_employment_events(
    employee_id,
    company_id,
    actor_id,
    event_type,
    reason,
    metadata
  )
  values(
    p_employee_id,

    v_employee.company_id,

    auth.uid(),

    'employee.rehired',

    v_reason,

    jsonb_build_object(
      'previousStatus',
      'terminated',

      'newStatus',
      'active'
    )
  );


  return jsonb_build_object(
    'employeeId',
    p_employee_id,

    'status',
    'active',

    'isActive',
    true,

    'rehiredAt',
    v_now
  );

end;
$function$;


-- ============================================================
-- 11. FUNCTION SECURITY
-- ============================================================

revoke all on function
public.dmh_assert_owner_employee(uuid)
from public;


revoke all on function
public.dmh_owner_employment_roster()
from public;


revoke all on function
public.dmh_owner_suspend_employee(uuid,text)
from public;


revoke all on function
public.dmh_owner_reinstate_employee(uuid,text)
from public;


revoke all on function
public.dmh_owner_terminate_employee(uuid,text)
from public;


revoke all on function
public.dmh_owner_rehire_employee(uuid,text)
from public;


grant execute on function
public.dmh_owner_employment_roster()
to authenticated;


grant execute on function
public.dmh_owner_suspend_employee(uuid,text)
to authenticated;


grant execute on function
public.dmh_owner_reinstate_employee(uuid,text)
to authenticated;


grant execute on function
public.dmh_owner_terminate_employee(uuid,text)
to authenticated;


grant execute on function
public.dmh_owner_rehire_employee(uuid,text)
to authenticated;


-- ============================================================
-- END MIGRATION 072
-- ============================================================
