-- ============================================================
-- DMHOUSE Sales OS
-- Migration 074
-- Territory Assignment Ledger
--
-- PURPOSE
--
-- Preserve permanent market-assignment history without
-- replacing the existing employee_territories system.
--
-- Existing system remains authoritative for CURRENT access.
--
-- This engine provides:
--
-- • Permanent assignment records
-- • Permanent assignment event history
-- • Employee × territory history
-- • Last-worked intelligence
-- • Cooling-period intelligence
-- • Foundation for Territory Command Center analytics
--
-- IMPORTANT:
--
-- The registry intentionally does NOT foreign-key territory_id
-- to employee_territories.
--
-- Existing UI currently permits deleting a territory.
-- Historical territory intelligence must survive that deletion.
-- ============================================================


-- ============================================================
-- 1. TERRITORY ASSIGNMENT REGISTRY
--
-- One permanent row for every territory assignment.
-- ============================================================

create table if not exists
public.territory_assignment_registry (

  territory_id uuid primary key,

  company_id uuid not null
    references public.companies(id)
    on delete cascade,

  employee_id uuid not null
    references public.profiles(id)
    on delete restrict,

  territory_name text not null,

  center_address text not null,

  center_latitude numeric not null,

  center_longitude numeric not null,

  radius_miles numeric not null,

  /*
    Market identity uses the geocoded center rather than the
    human territory label.

    This prevents labels such as:

      "Antonio · Atlanta"

    from creating separate market histories for the same city.
  */
  market_key text not null,

  starts_at timestamptz not null,

  expires_at timestamptz,

  source_status text not null,

  assignment_status text not null
    check (
      assignment_status in (
        'scheduled',
        'active',
        'completed',
        'expired',
        'disabled',
        'removed'
      )
    ),

  assigned_by uuid
    references public.profiles(id)
    on delete set null,

  first_seen_at timestamptz not null
    default now(),

  last_seen_at timestamptz not null
    default now(),

  completed_at timestamptz,

  removed_at timestamptz,

  last_source_updated_at timestamptz,

  metadata jsonb not null
    default '{}'::jsonb
);


create index if not exists
territory_assignment_registry_company_idx
on public.territory_assignment_registry(
  company_id,
  assignment_status,
  starts_at desc
);


create index if not exists
territory_assignment_registry_employee_idx
on public.territory_assignment_registry(
  company_id,
  employee_id,
  starts_at desc
);


create index if not exists
territory_assignment_registry_market_idx
on public.territory_assignment_registry(
  company_id,
  market_key,
  starts_at desc
);


-- ============================================================
-- 2. IMMUTABLE TERRITORY EVENT LEDGER
-- ============================================================

create table if not exists
public.territory_assignment_events (

  id bigint generated by default
    as identity
    primary key,

  territory_id uuid not null,

  company_id uuid not null
    references public.companies(id)
    on delete cascade,

  employee_id uuid not null
    references public.profiles(id)
    on delete restrict,

  market_key text not null,

  event_type text not null
    check (
      event_type in (
        'baseline_captured',
        'assigned',
        'updated',
        'status_changed',
        'extended',
        'removed'
      )
    ),

  previous_status text,

  new_status text,

  previous_expires_at timestamptz,

  new_expires_at timestamptz,

  actor_id uuid
    references public.profiles(id)
    on delete set null,

  event_at timestamptz not null
    default now(),

  snapshot jsonb not null
    default '{}'::jsonb
);


create index if not exists
territory_assignment_events_market_idx
on public.territory_assignment_events(
  company_id,
  market_key,
  event_at desc
);


create index if not exists
territory_assignment_events_employee_idx
on public.territory_assignment_events(
  company_id,
  employee_id,
  event_at desc
);


create index if not exists
territory_assignment_events_territory_idx
on public.territory_assignment_events(
  territory_id,
  event_at desc
);


-- ============================================================
-- 3. NORMALIZED MARKET KEY
--
-- Geocoder coordinates become the durable market identifier.
-- Four decimal places is sufficiently precise for city-center
-- identity while avoiding insignificant coordinate variation.
-- ============================================================

create or replace function
public.dmh_territory_market_key(
  p_latitude numeric,
  p_longitude numeric
)
returns text
language sql
immutable
set search_path to 'public'
as $function$

  select
    round(p_latitude,4)::text
    ||
    ','
    ||
    round(p_longitude,4)::text;

$function$;


-- ============================================================
-- 4. EFFECTIVE ASSIGNMENT STATUS
-- ============================================================

create or replace function
public.dmh_territory_effective_status(
  p_source_status text,
  p_starts_at timestamptz,
  p_expires_at timestamptz
)
returns text
language sql
stable
set search_path to 'public'
as $function$

  select case

    when p_source_status =
      'disabled'
    then
      'disabled'

    when p_expires_at is not null
      and p_expires_at < now()
    then
      'expired'

    when p_starts_at > now()
    then
      'scheduled'

    else
      'active'

  end;

$function$;


-- ============================================================
-- 5. LEDGER CAPTURE TRIGGER
--
-- Mirrors employee_territories into permanent history.
--
-- Existing employee_territories remains untouched.
-- ============================================================

create or replace function
public.dmh_capture_territory_assignment()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_market_key text;

  v_new_status text;

  v_event text;

  v_actor uuid :=
    auth.uid();
begin

  -- ----------------------------------------------------------
  -- DELETE
  -- ----------------------------------------------------------

  if tg_op = 'DELETE' then

    v_market_key :=
      public.dmh_territory_market_key(
        old.center_latitude::numeric,
        old.center_longitude::numeric
      );


    update public.territory_assignment_registry
    set
      assignment_status =
        'removed',

      source_status =
        old.status::text,

      last_seen_at =
        now(),

      removed_at =
        now(),

      last_source_updated_at =
        old.updated_at

    where territory_id =
      old.id;


    /*
      Safety fallback:
      If this territory predates the registry/backfill,
      preserve it before the source row disappears.
    */

    if not found then

      insert into public.territory_assignment_registry(
        territory_id,
        company_id,
        employee_id,
        territory_name,
        center_address,
        center_latitude,
        center_longitude,
        radius_miles,
        market_key,
        starts_at,
        expires_at,
        source_status,
        assignment_status,
        assigned_by,
        first_seen_at,
        last_seen_at,
        removed_at,
        last_source_updated_at
      )
      values(
        old.id,
        old.company_id,
        old.employee_id,
        old.territory_name,
        old.center_address,
        old.center_latitude,
        old.center_longitude,
        old.radius_miles,
        v_market_key,
        old.starts_at,
        old.expires_at,
        old.status::text,
        'removed',
        old.created_by,
        coalesce(
          old.created_at,
          now()
        ),
        now(),
        now(),
        old.updated_at
      );

    end if;


    insert into public.territory_assignment_events(
      territory_id,
      company_id,
      employee_id,
      market_key,
      event_type,
      previous_status,
      new_status,
      previous_expires_at,
      new_expires_at,
      actor_id,
      snapshot
    )
    values(
      old.id,
      old.company_id,
      old.employee_id,
      v_market_key,
      'removed',
      old.status::text,
      'removed',
      old.expires_at,
      old.expires_at,
      v_actor,
      to_jsonb(old)
    );


    return old;

  end if;


  -- ----------------------------------------------------------
  -- INSERT / UPDATE
  -- ----------------------------------------------------------

  v_market_key :=
    public.dmh_territory_market_key(
      new.center_latitude::numeric,
      new.center_longitude::numeric
    );


  v_new_status :=
    public.dmh_territory_effective_status(
      new.status::text,
      new.starts_at,
      new.expires_at
    );


  insert into public.territory_assignment_registry(
    territory_id,
    company_id,
    employee_id,
    territory_name,
    center_address,
    center_latitude,
    center_longitude,
    radius_miles,
    market_key,
    starts_at,
    expires_at,
    source_status,
    assignment_status,
    assigned_by,
    first_seen_at,
    last_seen_at,
    completed_at,
    removed_at,
    last_source_updated_at
  )
  values(
    new.id,
    new.company_id,
    new.employee_id,
    new.territory_name,
    new.center_address,
    new.center_latitude,
    new.center_longitude,
    new.radius_miles,
    v_market_key,
    new.starts_at,
    new.expires_at,
    new.status::text,
    v_new_status,
    new.created_by,
    coalesce(
      new.created_at,
      now()
    ),
    now(),

    case
      when v_new_status in (
        'expired',
        'disabled'
      )
      then now()
      else null
    end,

    null,

    new.updated_at
  )

  on conflict(territory_id)
  do update
  set
    company_id =
      excluded.company_id,

    employee_id =
      excluded.employee_id,

    territory_name =
      excluded.territory_name,

    center_address =
      excluded.center_address,

    center_latitude =
      excluded.center_latitude,

    center_longitude =
      excluded.center_longitude,

    radius_miles =
      excluded.radius_miles,

    market_key =
      excluded.market_key,

    starts_at =
      excluded.starts_at,

    expires_at =
      excluded.expires_at,

    source_status =
      excluded.source_status,

    assignment_status =
      excluded.assignment_status,

    assigned_by =
      excluded.assigned_by,

    last_seen_at =
      now(),

    completed_at =
      case

        when excluded.assignment_status in (
          'expired',
          'disabled'
        )
        then
          coalesce(
            public.territory_assignment_registry.completed_at,
            now()
          )

        else
          public.territory_assignment_registry.completed_at

      end,

    removed_at =
      null,

    last_source_updated_at =
      excluded.last_source_updated_at;


  if tg_op = 'INSERT' then

    v_event :=
      'assigned';

  elsif old.status::text
        is distinct from
        new.status::text
  then

    v_event :=
      'status_changed';

  elsif old.expires_at
        is distinct from
        new.expires_at
  then

    v_event :=
      case
        when
          new.expires_at is not null

          and (
            old.expires_at is null
            or
            new.expires_at >
              old.expires_at
          )

        then
          'extended'

        else
          'updated'
      end;

  else

    v_event :=
      'updated';

  end if;


  insert into public.territory_assignment_events(
    territory_id,
    company_id,
    employee_id,
    market_key,
    event_type,
    previous_status,
    new_status,
    previous_expires_at,
    new_expires_at,
    actor_id,
    snapshot
  )
  values(
    new.id,
    new.company_id,
    new.employee_id,
    v_market_key,
    v_event,

    case
      when tg_op = 'UPDATE'
      then old.status::text
      else null
    end,

    v_new_status,

    case
      when tg_op = 'UPDATE'
      then old.expires_at
      else null
    end,

    new.expires_at,

    v_actor,

    to_jsonb(new)
  );


  return new;

end;
$function$;


-- ============================================================
-- 6. REGISTER CAPTURE ENGINE
-- ============================================================

drop trigger if exists
capture_territory_assignment
on public.employee_territories;


create trigger
capture_territory_assignment
after insert or update or delete
on public.employee_territories
for each row
execute function
public.dmh_capture_territory_assignment();


-- ============================================================
-- 7. BACKFILL CURRENT TERRITORIES
--
-- Existing assignments immediately become historical records.
-- No existing territory row is modified.
-- ============================================================

insert into public.territory_assignment_registry(
  territory_id,
  company_id,
  employee_id,
  territory_name,
  center_address,
  center_latitude,
  center_longitude,
  radius_miles,
  market_key,
  starts_at,
  expires_at,
  source_status,
  assignment_status,
  assigned_by,
  first_seen_at,
  last_seen_at,
  completed_at,
  last_source_updated_at
)

select
  t.id,

  t.company_id,

  t.employee_id,

  t.territory_name,

  t.center_address,

  t.center_latitude,

  t.center_longitude,

  t.radius_miles,

  public.dmh_territory_market_key(
    t.center_latitude::numeric,
    t.center_longitude::numeric
  ),

  t.starts_at,

  t.expires_at,

  t.status::text,

  public.dmh_territory_effective_status(
    t.status::text,
    t.starts_at,
    t.expires_at
  ),

  t.created_by,

  coalesce(
    t.created_at,
    now()
  ),

  now(),

  case

    when
      public.dmh_territory_effective_status(
        t.status::text,
        t.starts_at,
        t.expires_at
      )
      in (
        'expired',
        'disabled'
      )

    then
      coalesce(
        t.expires_at,
        t.updated_at,
        now()
      )

    else
      null

  end,

  t.updated_at

from public.employee_territories t

on conflict(territory_id)
do nothing;


insert into public.territory_assignment_events(
  territory_id,
  company_id,
  employee_id,
  market_key,
  event_type,
  new_status,
  new_expires_at,
  actor_id,
  event_at,
  snapshot
)

select
  t.id,

  t.company_id,

  t.employee_id,

  public.dmh_territory_market_key(
    t.center_latitude::numeric,
    t.center_longitude::numeric
  ),

  'baseline_captured',

  public.dmh_territory_effective_status(
    t.status::text,
    t.starts_at,
    t.expires_at
  ),

  t.expires_at,

  null,

  now(),

  to_jsonb(t)

from public.employee_territories t

where not exists(

  select 1

  from public.territory_assignment_events e

  where e.territory_id =
    t.id

    and e.event_type =
      'baseline_captured'
);


-- ============================================================
-- 8. RLS
-- ============================================================

alter table
public.territory_assignment_registry
enable row level security;


alter table
public.territory_assignment_events
enable row level security;


drop policy if exists
"owner reads territory registry"
on public.territory_assignment_registry;


create policy
"owner reads territory registry"
on public.territory_assignment_registry
for select
to authenticated
using (
  company_id =
    public.current_company_id()

  and

  public.current_role()::text =
    'owner'
);


drop policy if exists
"employee reads own territory registry"
on public.territory_assignment_registry;


create policy
"employee reads own territory registry"
on public.territory_assignment_registry
for select
to authenticated
using (
  company_id =
    public.current_company_id()

  and

  employee_id =
    auth.uid()
);


drop policy if exists
"owner reads territory events"
on public.territory_assignment_events;


create policy
"owner reads territory events"
on public.territory_assignment_events
for select
to authenticated
using (
  company_id =
    public.current_company_id()

  and

  public.current_role()::text =
    'owner'
);


drop policy if exists
"employee reads own territory events"
on public.territory_assignment_events;


create policy
"employee reads own territory events"
on public.territory_assignment_events
for select
to authenticated
using (
  company_id =
    public.current_company_id()

  and

  employee_id =
    auth.uid()
);


grant select
on public.territory_assignment_registry
to authenticated;


grant select
on public.territory_assignment_events
to authenticated;


-- ============================================================
-- 9. OWNER TERRITORY COMMAND INTELLIGENCE
--
-- 30-day cooldown is the initial default.
-- It is advisory, not a hard prohibition.
-- ============================================================

create or replace function
public.dmh_owner_territory_intelligence(
  p_cooldown_days integer default 30
)
returns table(

  market_key text,

  territory_name text,

  center_address text,

  center_latitude numeric,

  center_longitude numeric,

  radius_miles numeric,

  assignment_count bigint,

  employee_count bigint,

  current_territory_id uuid,

  current_employee_id uuid,

  current_employee_name text,

  current_status text,

  current_starts_at timestamptz,

  current_expires_at timestamptz,

  last_employee_id uuid,

  last_employee_name text,

  last_started_at timestamptz,

  last_worked_at timestamptz,

  days_since_last_worked integer,

  cooldown_days integer,

  recommended_next_assignment_at timestamptz,

  recommendation text
)
language sql
security definer
set search_path to 'public'
as $function$

with authorized as (

  select
    r.*,

    case

      when r.assignment_status =
        'removed'
      then
        'removed'

      else
        public.dmh_territory_effective_status(
          r.source_status,
          r.starts_at,
          r.expires_at
        )

    end
      as effective_assignment_status

  from public.territory_assignment_registry r

  where
    public.current_role()::text =
      'owner'

    and

    r.company_id =
      public.current_company_id()
),


market_rollup as (

  select
    a.market_key,

    count(*)::bigint
      as assignment_count,

    count(
      distinct a.employee_id
    )::bigint
      as employee_count

  from authorized a

  group by
    a.market_key
),


ranked as (

  select
    a.*,

    row_number() over(
      partition by a.market_key
      order by
        a.starts_at desc,
        a.first_seen_at desc,
        a.territory_id desc
    )
      as rn

  from authorized a
),


latest as (

  select
    r.*,
    m.assignment_count,
    m.employee_count

  from ranked r

  join market_rollup m
    on m.market_key =
      r.market_key

  where r.rn = 1
),


resolved as (

  select
    l.*,

    coalesce(
      l.removed_at,

      l.completed_at,

      case
        when l.expires_at is not null
          and l.expires_at <= now()
        then l.expires_at
        else null
      end,

      l.last_seen_at
    )
      as resolved_last_worked_at

  from latest l
)


select

  l.market_key,

  l.territory_name,

  l.center_address,

  l.center_latitude,

  l.center_longitude,

  l.radius_miles,

  l.assignment_count,

  l.employee_count,


  case
    when l.effective_assignment_status in (
      'active',
      'scheduled'
    )
    then l.territory_id
    else null
  end
    as current_territory_id,


  case
    when l.effective_assignment_status in (
      'active',
      'scheduled'
    )
    then l.employee_id
    else null
  end
    as current_employee_id,


  case
    when l.effective_assignment_status in (
      'active',
      'scheduled'
    )
    then current_employee.full_name
    else null
  end
    as current_employee_name,


  l.effective_assignment_status
    as current_status,


  l.starts_at
    as current_starts_at,


  l.expires_at
    as current_expires_at,


  l.employee_id
    as last_employee_id,


  last_employee.full_name
    as last_employee_name,


  l.starts_at
    as last_started_at,


  l.resolved_last_worked_at
    as last_worked_at,


  case

    when l.effective_assignment_status in (
      'active',
      'scheduled'
    )
    then 0

    else greatest(
      0,

      floor(
        extract(
          epoch from (
            now()
            -
            l.resolved_last_worked_at
          )
        )
        /
        86400
      )::integer
    )

  end
    as days_since_last_worked,


  greatest(
    1,
    coalesce(
      p_cooldown_days,
      30
    )
  )
    as cooldown_days,


  case

    when l.effective_assignment_status in (
      'active',
      'scheduled'
    )
    then null

    else
      l.resolved_last_worked_at
      +
      make_interval(
        days =>
          greatest(
            1,
            coalesce(
              p_cooldown_days,
              30
            )
          )
      )

  end
    as recommended_next_assignment_at,


  case

    when l.effective_assignment_status =
      'active'
    then
      'ACTIVE'

    when l.effective_assignment_status =
      'scheduled'
    then
      'SCHEDULED'

    when
      now()
      >=
      l.resolved_last_worked_at
      +
      make_interval(
        days =>
          greatest(
            1,
            coalesce(
              p_cooldown_days,
              30
            )
          )
      )
    then
      'READY'

    else
      'COOLING'

  end
    as recommendation


from resolved l


left join public.profiles current_employee
  on current_employee.id =
    case

      when l.effective_assignment_status in (
        'active',
        'scheduled'
      )

      then l.employee_id

      else null

    end


left join public.profiles last_employee
  on last_employee.id =
    l.employee_id


order by

  case

    when l.effective_assignment_status =
      'active'
    then 1

    when l.effective_assignment_status =
      'scheduled'
    then 2

    when
      now()
      >=
      l.resolved_last_worked_at
      +
      make_interval(
        days =>
          greatest(
            1,
            coalesce(
              p_cooldown_days,
              30
            )
          )
      )
    then 3

    else 4

  end,

  l.starts_at desc;

$function$;


revoke all
on function
public.dmh_owner_territory_intelligence(integer)
from public;


grant execute
on function
public.dmh_owner_territory_intelligence(integer)
to authenticated;


-- ============================================================
-- END MIGRATION 074
-- ============================================================
