import {useEffect,useState} from 'react';
import {AlertTriangle,CheckCircle2,ShieldAlert} from 'lucide-react';
import {Card,PrimaryButton} from '../Primitives';
import {supabase} from '../../lib/supabase';
import type {DealRiskAssessment} from '../../engines/dealRisk';
import {riskLabel} from '../../engines/dealRisk';
import InterventionAssignmentPanel from '../execution/InterventionAssignmentPanel';

type Intervention={id:string;action:string;notes?:string;created_at:string;created_by_name?:string};
const tone={healthy:'text-emerald-700 bg-emerald-50 border-emerald-200',watch:'text-amber-700 bg-amber-50 border-amber-200',at_risk:'text-orange-700 bg-orange-50 border-orange-200',critical:'text-red-700 bg-red-50 border-red-200'} as const;
export default function DealRiskPanel({assessment,companyId,profileId}: {assessment:DealRiskAssessment;companyId?:string;profileId?:string}){
 const [history,setHistory]=useState<Intervention[]>([]);const [notes,setNotes]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
 async function load(){if(!companyId)return;const {data,error}=await supabase.from('deal_interventions').select('id,action,notes,created_at,created_by_name').eq('opportunity_id',assessment.opportunityId).order('created_at',{ascending:false}).limit(20);if(!error)setHistory((data||[]) as Intervention[])}
 useEffect(()=>{void load()},[assessment.opportunityId,companyId]);
 async function record(){if(!companyId||!profileId)return;setBusy(true);setNotice('');const {error}=await supabase.from('deal_interventions').insert({company_id:companyId,opportunity_id:assessment.opportunityId,created_by:profileId,action:assessment.recommendedAction,notes:notes||null,risk_score:assessment.score,risk_level:assessment.level});if(error)setNotice(error.message);else{setNotes('');setNotice('Intervention recorded.');await load()}setBusy(false)}
 return <div className="grid gap-5 xl:grid-cols-[.85fr_1.15fr]">
  <Card className="p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-slate-400">Deal risk</p><h3 className="mt-2 text-2xl font-semibold">{assessment.score}/100</h3></div><span className={`rounded-full border px-3 py-1 text-xs font-semibold ${tone[assessment.level]}`}>{riskLabel(assessment.level)}</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-slate-900" style={{width:`${assessment.score}%`}}/></div><div className="mt-6 rounded-2xl border border-blue-100 bg-blue-50 p-4"><p className="text-xs font-semibold uppercase tracking-[.16em] text-blue-600">Recommended intervention</p><p className="mt-2 text-sm font-semibold text-slate-900">{assessment.recommendedAction}</p></div><div className="mt-4"><InterventionAssignmentPanel assessment={assessment}/></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Add context, owner decision, or outcome…" className="mt-4 min-h-24 w-full rounded-2xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500"/><PrimaryButton onClick={()=>void record()} disabled={busy||!companyId||!profileId} className="mt-3 w-full">{busy?'Recording…':'Record intervention'}</PrimaryButton>{notice&&<p className="mt-3 text-sm text-slate-500">{notice}</p>}</Card>
  <div className="space-y-5"><Card className="p-6"><div className="flex items-center gap-2"><ShieldAlert size={18}/><h3 className="font-semibold">Active risk signals</h3></div><div className="mt-4 space-y-3">{assessment.signals.length?assessment.signals.map(signal=><div key={signal.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-4"><div><p className="font-semibold">{signal.label}</p><p className="mt-1 text-sm text-slate-500">{signal.detail}</p></div><span className="text-sm font-semibold text-slate-500">+{signal.points}</span></div><p className="mt-3 text-xs font-semibold text-blue-600">{signal.action}</p></div>):<div className="flex items-center gap-3 rounded-2xl bg-emerald-50 p-4 text-emerald-700"><CheckCircle2 size={20}/><p className="text-sm font-semibold">No material risk signals detected.</p></div>}</div></Card><Card className="p-6"><div className="flex items-center gap-2"><AlertTriangle size={18}/><h3 className="font-semibold">Intervention history</h3></div><div className="mt-4 space-y-3">{history.length?history.map(item=><div key={item.id} className="border-l-2 border-slate-200 pl-4"><p className="text-sm font-semibold">{item.action}</p>{item.notes&&<p className="mt-1 text-sm text-slate-500">{item.notes}</p>}<p className="mt-1 text-xs text-slate-400">{new Date(item.created_at).toLocaleString()}{item.created_by_name?` · ${item.created_by_name}`:''}</p></div>):<p className="text-sm text-slate-500">No interventions have been recorded.</p>}</div></Card></div>
 </div>
}
