import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors = {'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}});
const decode=(value:string)=>{value=value.replace(/-/g,'+').replace(/_/g,'/');while(value.length%4)value+='=';return new Uint8Array(atob(value).split('').map(c=>c.charCodeAt(0)));};
const encode=(value:string)=>{const bytes=new TextEncoder().encode(value);let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'');};
async function decrypt(value:string,secret:string){const [ivPart,dataPart]=value.split('.');const keyBytes=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(secret)));const key=await crypto.subtle.importKey('raw',keyBytes,{name:'AES-GCM'},false,['decrypt']);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:decode(ivPart)},key,decode(dataPart));return new TextDecoder().decode(plain);}
async function encrypt(value:string,secret:string){const keyBytes=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(secret)));const key=await crypto.subtle.importKey('raw',keyBytes,{name:'AES-GCM'},false,['encrypt']);const iv=crypto.getRandomValues(new Uint8Array(12));const data=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(value)));const b=(x:Uint8Array)=>btoa(String.fromCharCode(...x)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'');return `${b(iv)}.${b(data)}`;}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
 const auth=req.headers.get('Authorization');if(!auth)throw new Error('Missing authorization.');
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const secret=Deno.env.get('EMAIL_TOKEN_ENCRYPTION_KEY');if(!secret)throw new Error('EMAIL_TOKEN_ENCRYPTION_KEY is not configured.');
 const userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}});const admin=createClient(url,service);const {data:{user}}=await userClient.auth.getUser();if(!user)throw new Error('Unauthorized.');
 const {data:profile}=await userClient.from('profiles').select('company_id,role,is_active,full_name').eq('id',user.id).single();if(!profile||profile.role!=='owner'||!profile.is_active)throw new Error('Owner access required.');
 const {recipient}=await req.json();if(!recipient)throw new Error('Test recipient is required.');
 const {data:connection,error}=await admin.from('company_email_connections').select('*').eq('company_id',profile.company_id).eq('provider','google_workspace').single();if(error||!connection||connection.status!=='connected')throw new Error('Google Workspace is not connected.');
 let accessToken=await decrypt(connection.encrypted_access_token,secret);const expires=connection.access_token_expires_at?new Date(connection.access_token_expires_at).getTime():0;
 if(expires<Date.now()+60000){if(!connection.encrypted_refresh_token)throw new Error('Google refresh token is missing. Reconnect the mailbox.');const refreshToken=await decrypt(connection.encrypted_refresh_token,secret);const tokenResponse=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:Deno.env.get('GOOGLE_CLIENT_ID')!,client_secret:Deno.env.get('GOOGLE_CLIENT_SECRET')!,refresh_token:refreshToken,grant_type:'refresh_token'})});const refreshed=await tokenResponse.json();if(!tokenResponse.ok||!refreshed.access_token)throw new Error(refreshed.error_description||'Google token refresh failed.');accessToken=refreshed.access_token;await admin.from('company_email_connections').update({encrypted_access_token:await encrypt(accessToken,secret),access_token_expires_at:new Date(Date.now()+Number(refreshed.expires_in||3600)*1000).toISOString(),last_error:null}).eq('id',connection.id);}
 const subject='DMHOUSE Google Workspace connection test';const body=`Google Workspace is connected to DMHOUSE.\n\nMailbox: ${connection.mailbox_email}\nVerified by: ${profile.full_name}\nTime: ${new Date().toISOString()}`;const mime=[`From: Data Market House <${connection.mailbox_email}>`,`To: ${recipient}`,`Subject: ${subject}`,'MIME-Version: 1.0','Content-Type: text/plain; charset="UTF-8"','',body].join('\r\n');
 const response=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send',{method:'POST',headers:{Authorization:`Bearer ${accessToken}`,'Content-Type':'application/json'},body:JSON.stringify({raw:encode(mime)})});const result=await response.json();if(!response.ok)throw new Error(result.error?.message||'Gmail rejected the test email.');
 await admin.from('company_email_connections').update({last_verified_at:new Date().toISOString(),last_error:null}).eq('id',connection.id);return json({ok:true,id:result.id,mailbox:connection.mailbox_email});
 }catch(error){return json({ok:false,error:error instanceof Error?error.message:'Test email failed.'},400)}});
